# CMake generated Testfile for 
# Source directory: /Users/xitrium/claud/stanrt
# Build directory: /Users/xitrium/claud/stanrt/build-rel
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_smoke "/Users/xitrium/claud/stanrt/build-rel/test_smoke")
set_tests_properties(test_smoke PROPERTIES  WORKING_DIRECTORY "/Users/xitrium/claud/stanrt" _BACKTRACE_TRIPLES "/Users/xitrium/claud/stanrt/CMakeLists.txt;85;add_test;/Users/xitrium/claud/stanrt/CMakeLists.txt;96;stanrt_add_test;/Users/xitrium/claud/stanrt/CMakeLists.txt;0;")
add_test(test_executor "/Users/xitrium/claud/stanrt/build-rel/test_executor")
set_tests_properties(test_executor PROPERTIES  WORKING_DIRECTORY "/Users/xitrium/claud/stanrt" _BACKTRACE_TRIPLES "/Users/xitrium/claud/stanrt/CMakeLists.txt;85;add_test;/Users/xitrium/claud/stanrt/CMakeLists.txt;97;stanrt_add_test;/Users/xitrium/claud/stanrt/CMakeLists.txt;0;")
add_test(test_recorder "/Users/xitrium/claud/stanrt/build-rel/test_recorder")
set_tests_properties(test_recorder PROPERTIES  WORKING_DIRECTORY "/Users/xitrium/claud/stanrt" _BACKTRACE_TRIPLES "/Users/xitrium/claud/stanrt/CMakeLists.txt;85;add_test;/Users/xitrium/claud/stanrt/CMakeLists.txt;98;stanrt_add_test;/Users/xitrium/claud/stanrt/CMakeLists.txt;0;")
add_test(test_densities "/Users/xitrium/claud/stanrt/build-rel/test_densities")
set_tests_properties(test_densities PROPERTIES  WORKING_DIRECTORY "/Users/xitrium/claud/stanrt" _BACKTRACE_TRIPLES "/Users/xitrium/claud/stanrt/CMakeLists.txt;85;add_test;/Users/xitrium/claud/stanrt/CMakeLists.txt;99;stanrt_add_test;/Users/xitrium/claud/stanrt/CMakeLists.txt;0;")
add_test(test_matvec "/Users/xitrium/claud/stanrt/build-rel/test_matvec")
set_tests_properties(test_matvec PROPERTIES  WORKING_DIRECTORY "/Users/xitrium/claud/stanrt" _BACKTRACE_TRIPLES "/Users/xitrium/claud/stanrt/CMakeLists.txt;85;add_test;/Users/xitrium/claud/stanrt/CMakeLists.txt;100;stanrt_add_test;/Users/xitrium/claud/stanrt/CMakeLists.txt;0;")
add_test(test_legacy "/Users/xitrium/claud/stanrt/build-rel/test_legacy")
set_tests_properties(test_legacy PROPERTIES  WORKING_DIRECTORY "/Users/xitrium/claud/stanrt" _BACKTRACE_TRIPLES "/Users/xitrium/claud/stanrt/CMakeLists.txt;85;add_test;/Users/xitrium/claud/stanrt/CMakeLists.txt;101;stanrt_add_test;/Users/xitrium/claud/stanrt/CMakeLists.txt;0;")
add_test(test_eight_schools "/Users/xitrium/claud/stanrt/build-rel/test_eight_schools")
set_tests_properties(test_eight_schools PROPERTIES  WORKING_DIRECTORY "/Users/xitrium/claud/stanrt" _BACKTRACE_TRIPLES "/Users/xitrium/claud/stanrt/CMakeLists.txt;85;add_test;/Users/xitrium/claud/stanrt/CMakeLists.txt;102;stanrt_add_test;/Users/xitrium/claud/stanrt/CMakeLists.txt;0;")
add_test(test_glm "/Users/xitrium/claud/stanrt/build-rel/test_glm")
set_tests_properties(test_glm PROPERTIES  WORKING_DIRECTORY "/Users/xitrium/claud/stanrt" _BACKTRACE_TRIPLES "/Users/xitrium/claud/stanrt/CMakeLists.txt;85;add_test;/Users/xitrium/claud/stanrt/CMakeLists.txt;103;stanrt_add_test;/Users/xitrium/claud/stanrt/CMakeLists.txt;0;")
add_test(test_nuts "/Users/xitrium/claud/stanrt/build-rel/test_nuts")
set_tests_properties(test_nuts PROPERTIES  WORKING_DIRECTORY "/Users/xitrium/claud/stanrt" _BACKTRACE_TRIPLES "/Users/xitrium/claud/stanrt/CMakeLists.txt;85;add_test;/Users/xitrium/claud/stanrt/CMakeLists.txt;104;stanrt_add_test;/Users/xitrium/claud/stanrt/CMakeLists.txt;0;")
add_test(test_sexp "/Users/xitrium/claud/stanrt/build-rel/test_sexp")
set_tests_properties(test_sexp PROPERTIES  WORKING_DIRECTORY "/Users/xitrium/claud/stanrt" _BACKTRACE_TRIPLES "/Users/xitrium/claud/stanrt/CMakeLists.txt;85;add_test;/Users/xitrium/claud/stanrt/CMakeLists.txt;105;stanrt_add_test;/Users/xitrium/claud/stanrt/CMakeLists.txt;0;")
add_test(test_mir "/Users/xitrium/claud/stanrt/build-rel/test_mir")
set_tests_properties(test_mir PROPERTIES  WORKING_DIRECTORY "/Users/xitrium/claud/stanrt" _BACKTRACE_TRIPLES "/Users/xitrium/claud/stanrt/CMakeLists.txt;85;add_test;/Users/xitrium/claud/stanrt/CMakeLists.txt;106;stanrt_add_test;/Users/xitrium/claud/stanrt/CMakeLists.txt;0;")
add_test(test_transforms "/Users/xitrium/claud/stanrt/build-rel/test_transforms")
set_tests_properties(test_transforms PROPERTIES  WORKING_DIRECTORY "/Users/xitrium/claud/stanrt" _BACKTRACE_TRIPLES "/Users/xitrium/claud/stanrt/CMakeLists.txt;85;add_test;/Users/xitrium/claud/stanrt/CMakeLists.txt;107;stanrt_add_test;/Users/xitrium/claud/stanrt/CMakeLists.txt;0;")
add_test(test_eltwise "/Users/xitrium/claud/stanrt/build-rel/test_eltwise")
set_tests_properties(test_eltwise PROPERTIES  WORKING_DIRECTORY "/Users/xitrium/claud/stanrt" _BACKTRACE_TRIPLES "/Users/xitrium/claud/stanrt/CMakeLists.txt;85;add_test;/Users/xitrium/claud/stanrt/CMakeLists.txt;108;stanrt_add_test;/Users/xitrium/claud/stanrt/CMakeLists.txt;0;")
add_test(test_lower "/Users/xitrium/claud/stanrt/build-rel/test_lower")
set_tests_properties(test_lower PROPERTIES  WORKING_DIRECTORY "/Users/xitrium/claud/stanrt" _BACKTRACE_TRIPLES "/Users/xitrium/claud/stanrt/CMakeLists.txt;85;add_test;/Users/xitrium/claud/stanrt/CMakeLists.txt;109;stanrt_add_test;/Users/xitrium/claud/stanrt/CMakeLists.txt;0;")
add_test(test_data "/Users/xitrium/claud/stanrt/build-rel/test_data")
set_tests_properties(test_data PROPERTIES  WORKING_DIRECTORY "/Users/xitrium/claud/stanrt" _BACKTRACE_TRIPLES "/Users/xitrium/claud/stanrt/CMakeLists.txt;85;add_test;/Users/xitrium/claud/stanrt/CMakeLists.txt;110;stanrt_add_test;/Users/xitrium/claud/stanrt/CMakeLists.txt;0;")
add_test(test_e2e "/Users/xitrium/claud/stanrt/build-rel/test_e2e")
set_tests_properties(test_e2e PROPERTIES  WORKING_DIRECTORY "/Users/xitrium/claud/stanrt" _BACKTRACE_TRIPLES "/Users/xitrium/claud/stanrt/CMakeLists.txt;85;add_test;/Users/xitrium/claud/stanrt/CMakeLists.txt;111;stanrt_add_test;/Users/xitrium/claud/stanrt/CMakeLists.txt;0;")
