// STANLI-LIT: PASS
// STANLI-LIT-EXPECT: OK
// STANLI-LIT-DATA: {"context_seed": 0.0}
// STANLI-LIT-TIMEOUT: 180
// Generated by tools/generate_builtin_signature_models.py from the unified FunctionSpec registry
// and `stanc --dump-stan-math-signatures`. Do not edit by hand.
// Partition 16 of 30; 238 overloads.
functions {
  real builtin_signatures_16(real seed) {
    real total = 0;
    // Phi(array[]int)=>array[]real
    {
      array[1] int arg_1 = {1};
      array[1] real value = Phi(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // abs(row_vector)=>row_vector
    {
      row_vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)];
      row_vector[1] value = abs(arg_1);
      total += 1 * sum(value);
    }
    // acos(array[,,,,,]real)=>array[,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{(0.29999999999999999 + 0.0625 * seed)}}}}}};
      array[1, 1, 1, 1, 1, 1] real value = acos(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // acos(array[,]matrix)=>array[,]matrix
    {
      array[1, 1] matrix[1, 1] arg_1 = {{[[(0.29999999999999999 + 0.0625 * seed)]]}};
      array[1, 1] matrix[1, 1] value = acos(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // acosh(array[,,,,,]vector)=>array[,,,,,]vector
    {
      array[1, 1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{{[(1.3499999999999999 + 0.0625 * seed)]'}}}}}};
      array[1, 1, 1, 1, 1, 1] vector[1] value = acosh(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // acosh(array[,,,,]vector)=>array[,,,,]vector
    {
      array[1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{[(1.3499999999999999 + 0.0625 * seed)]'}}}}};
      array[1, 1, 1, 1, 1] vector[1] value = acosh(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // acosh(array[,,]vector)=>array[,,]vector
    {
      array[1, 1, 1] vector[1] arg_1 = {{{[(1.3499999999999999 + 0.0625 * seed)]'}}};
      array[1, 1, 1] vector[1] value = acosh(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // acosh(int)=>real
    {
      int arg_1 = 1;
      real value = acosh(arg_1);
      total += 1.1875 * value;
    }
    // append_array(array[,,,]int,array[,,,]int)=>array[,,,]int
    {
      array[1, 1, 1, 1] int arg_1 = {{{{1}}}};
      array[2, 1, 1, 1] int value = append_array(arg_1, {{{{1}}}});
      if (seed > 1e100)
        print(value);
    }
    // append_col(row_vector,real)=>row_vector
    {
      row_vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)];
      real arg_2 = (1.2 + 0.0625 * seed);
      row_vector[2] value = append_col(arg_1, arg_2);
      total += 1.046875 * sum(value);
    }
    // asinh(array[,,,]int)=>array[,,,]real
    {
      array[1, 1, 1, 1] int arg_1 = {{{{1}}}};
      array[1, 1, 1, 1] real value = asinh(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // asinh(array[]row_vector)=>array[]row_vector
    {
      array[1] row_vector[1] arg_1 = {[(0.45000000000000001 + 0.0625 * seed)]};
      array[1] row_vector[1] value = asinh(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // atan2(array[,,,,,,,]int,int)=>array[,,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{{{0}}}}}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1, 1, 1, 1, 1] real value = atan2(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // atan2(array[,,,,,,]real,int)=>array[,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{{(0.45000000000000001 + 0.0625 * seed)}}}}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1, 1, 1, 1] real value = atan2(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // atan2(array[,,,,,]int,int)=>array[,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{0}}}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1, 1, 1] real value = atan2(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // atan2(array[,,]matrix,array[,,]matrix)=>array[,,]matrix
    {
      array[1, 1, 1] matrix[1, 1] arg_1 = {{{[[(0.45000000000000001 + 0.0625 * seed)]]}}};
      array[1, 1, 1] matrix[1, 1] arg_2 = {{{[[(1.2 + 0.0625 * seed)]]}}};
      array[1, 1, 1] matrix[1, 1] value = atan2(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // atan2(array[,]int,array[,]int)=>array[,]real
    {
      array[1, 1] int arg_1 = {{0}};
      array[1, 1] int arg_2 = {{1}};
      array[1, 1] real value = atan2(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // atan2(real,array[,,,,]vector)=>array[,,,,]vector
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1, 1, 1, 1] vector[1] arg_2 = {{{{{[(1.2 + 0.0625 * seed)]'}}}}};
      array[1, 1, 1, 1, 1] vector[1] value = atan2(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // atan2(row_vector,int)=>row_vector
    {
      row_vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)];
      int arg_2 = 1;
      row_vector[1] value = atan2(arg_1, arg_2);
      total += 1.171875 * sum(value);
    }
    // bessel_first_kind(int,array[]vector)=>array[]vector
    {
      int arg_1 = 2;
      array[1] vector[1] arg_2 = {[(1.3499999999999999 + 0.0625 * seed)]'};
      array[1] vector[1] value = bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // bessel_first_kind(int,vector)=>vector
    {
      int arg_1 = 2;
      vector[1] arg_2 = [(1.3499999999999999 + 0.0625 * seed)]';
      vector[1] value = bessel_first_kind(arg_1, arg_2);
      total += 1.21875 * sum(value);
    }
    // bessel_second_kind(array[,,,,,,,]int,array[,,,,,,]vector)=>array[,,,,,,]vector
    {
      array[1, 1, 1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{{{2}}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] vector[1] arg_2 = {{{{{{{[(1.3499999999999999 + 0.0625 * seed)]'}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] vector[1] value = bessel_second_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // bessel_second_kind(array[,,,,]int,array[,,]matrix)=>array[,,]matrix
    {
      array[1, 1, 1, 1, 1] int arg_1 = {{{{{2}}}}};
      array[1, 1, 1] matrix[1, 1] arg_2 = {{{[[(1.3499999999999999 + 0.0625 * seed)]]}}};
      array[1, 1, 1] matrix[1, 1] value = bessel_second_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // bessel_second_kind(array[,,]int,real)=>array[,,]real
    {
      array[1, 1, 1] int arg_1 = {{{2}}};
      real arg_2 = (1.3499999999999999 + 0.0625 * seed);
      array[1, 1, 1] real value = bessel_second_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // bessel_second_kind(array[,]int,real)=>array[,]real
    {
      array[1, 1] int arg_1 = {{2}};
      real arg_2 = (1.3499999999999999 + 0.0625 * seed);
      array[1, 1] real value = bessel_second_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // bessel_second_kind(int,array[,,]vector)=>array[,,]vector
    {
      int arg_1 = 2;
      array[1, 1, 1] vector[1] arg_2 = {{{[(1.3499999999999999 + 0.0625 * seed)]'}}};
      array[1, 1, 1] vector[1] value = bessel_second_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // beta(array[,,,,,,]real,real)=>array[,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{{(1.95 + 0.0625 * seed)}}}}}}};
      real arg_2 = (2.9500000000000002 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1, 1] real value = beta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // beta(array[,,,,]real,array[,,,,]real)=>array[,,,,]real
    {
      array[1, 1, 1, 1, 1] real arg_1 = {{{{{(1.95 + 0.0625 * seed)}}}}};
      array[1, 1, 1, 1, 1] real arg_2 = {{{{{(2.9500000000000002 + 0.0625 * seed)}}}}};
      array[1, 1, 1, 1, 1] real value = beta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // beta(array[,,,,]row_vector,array[,,,,]row_vector)=>array[,,,,]row_vector
    {
      array[1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{[(1.95 + 0.0625 * seed)]}}}}};
      array[1, 1, 1, 1, 1] row_vector[1] arg_2 = {{{{{[(2.9500000000000002 + 0.0625 * seed)]}}}}};
      array[1, 1, 1, 1, 1] row_vector[1] value = beta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // beta(array[,,,,]row_vector,real)=>array[,,,,]row_vector
    {
      array[1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{[(1.95 + 0.0625 * seed)]}}}}};
      real arg_2 = (2.9500000000000002 + 0.0625 * seed);
      array[1, 1, 1, 1, 1] row_vector[1] value = beta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // beta(array[,,,]vector,real)=>array[,,,]vector
    {
      array[1, 1, 1, 1] vector[1] arg_1 = {{{{[(1.95 + 0.0625 * seed)]'}}}};
      real arg_2 = (2.9500000000000002 + 0.0625 * seed);
      array[1, 1, 1, 1] vector[1] value = beta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // beta(array[,]int,array[,]int)=>array[,]real
    {
      array[1, 1] int arg_1 = {{2}};
      array[1, 1] int arg_2 = {{3}};
      array[1, 1] real value = beta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // beta(array[]real,real)=>array[]real
    {
      array[1] real arg_1 = {(1.95 + 0.0625 * seed)};
      real arg_2 = (2.9500000000000002 + 0.0625 * seed);
      array[1] real value = beta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // beta(int,array[,,,,,,,]int)=>array[,,,,,,,]real
    {
      int arg_1 = 2;
      array[1, 1, 1, 1, 1, 1, 1, 1] int arg_2 = {{{{{{{{3}}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1, 1] real value = beta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // beta(real,array[,,,,,,,]int)=>array[,,,,,,,]real
    {
      real arg_1 = (1.95 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1, 1, 1] int arg_2 = {{{{{{{{3}}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1, 1] real value = beta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // beta(real,array[,,]row_vector)=>array[,,]row_vector
    {
      real arg_1 = (1.95 + 0.0625 * seed);
      array[1, 1, 1] row_vector[1] arg_2 = {{{[(2.9500000000000002 + 0.0625 * seed)]}}};
      array[1, 1, 1] row_vector[1] value = beta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // beta(real,array[,,]vector)=>array[,,]vector
    {
      real arg_1 = (1.95 + 0.0625 * seed);
      array[1, 1, 1] vector[1] arg_2 = {{{[(2.9500000000000002 + 0.0625 * seed)]'}}};
      array[1, 1, 1] vector[1] value = beta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // binary_log_loss(int,array[,,,,,,]vector)=>array[,,,,,,]vector
    {
      int arg_1 = 1;
      array[1, 1, 1, 1, 1, 1, 1] vector[1] arg_2 = {{{{{{{[(0.35000000000000003 + 0.0625 * seed)]'}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] vector[1] value = binary_log_loss(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // binary_log_loss(int,array[,,,,,]real)=>array[,,,,,]real
    {
      int arg_1 = 1;
      array[1, 1, 1, 1, 1, 1] real arg_2 = {{{{{{(0.35000000000000003 + 0.0625 * seed)}}}}}};
      array[1, 1, 1, 1, 1, 1] real value = binary_log_loss(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // binary_log_loss(int,array[,]matrix)=>array[,]matrix
    {
      int arg_1 = 1;
      array[1, 1] matrix[1, 1] arg_2 = {{[[(0.35000000000000003 + 0.0625 * seed)]]}};
      array[1, 1] matrix[1, 1] value = binary_log_loss(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // cbrt(array[,,,,,,]vector)=>array[,,,,,,]vector
    {
      array[1, 1, 1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] vector[1] value = cbrt(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // cbrt(array[,,]row_vector)=>array[,,]row_vector
    {
      array[1, 1, 1] row_vector[1] arg_1 = {{{[(0.45000000000000001 + 0.0625 * seed)]}}};
      array[1, 1, 1] row_vector[1] value = cbrt(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // cbrt(row_vector)=>row_vector
    {
      row_vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)];
      row_vector[1] value = cbrt(arg_1);
      total += 1.15625 * sum(value);
    }
    // ceil(array[,,,,]real)=>array[,,,,]real
    {
      array[1, 1, 1, 1, 1] real arg_1 = {{{{{(0.45000000000000001 + 0.0625 * seed)}}}}};
      array[1, 1, 1, 1, 1] real value = ceil(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // ceil(array[,]real)=>array[,]real
    {
      array[1, 1] real arg_1 = {{(0.45000000000000001 + 0.0625 * seed)}};
      array[1, 1] real value = ceil(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // cosh(array[,,,,,]int)=>array[,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{1}}}}}};
      array[1, 1, 1, 1, 1, 1] real value = cosh(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // cosh(array[,,,]vector)=>array[,,,]vector
    {
      array[1, 1, 1, 1] vector[1] arg_1 = {{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}};
      array[1, 1, 1, 1] vector[1] value = cosh(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // digamma(array[,]matrix)=>array[,]matrix
    {
      array[1, 1] matrix[1, 1] arg_1 = {{[[(1.3499999999999999 + 0.0625 * seed)]]}};
      array[1, 1] matrix[1, 1] value = digamma(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // dims(array[,,,,,,,]int)=>array[]int
    {
      array[1, 1, 1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{{{2}}}}}}}};
      array[8] int value = dims(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // divide(real,row_vector)=>row_vector
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      row_vector[1] arg_2 = [(1.2 + 0.0625 * seed)];
      row_vector[1] value = divide(arg_1, arg_2);
      total += 1.140625 * sum(value);
    }
    // dot_product(array[]real,array[]real)=>real
    {
      array[1] real arg_1 = {(0.45000000000000001 + 0.0625 * seed)};
      array[1] real arg_2 = {(1.2 + 0.0625 * seed)};
      real value = dot_product(arg_1, arg_2);
      total += 1.046875 * value;
    }
    // elt_divide(vector,vector)=>vector
    {
      vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)]';
      vector[1] arg_2 = [(1.2 + 0.0625 * seed)]';
      vector[1] value = elt_divide(arg_1, arg_2);
      total += 1 * sum(value);
    }
    // erfc(array[,,,,,,]row_vector)=>array[,,,,,,]row_vector
    {
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{{{[(0.45000000000000001 + 0.0625 * seed)]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] value = erfc(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // exp(array[,]real)=>array[,]real
    {
      array[1, 1] real arg_1 = {{(0.45000000000000001 + 0.0625 * seed)}};
      array[1, 1] real value = exp(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // exp2(array[,,]int)=>array[,,]real
    {
      array[1, 1, 1] int arg_1 = {{{1}}};
      array[1, 1, 1] real value = exp2(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // exp2(array[,]int)=>array[,]real
    {
      array[1, 1] int arg_1 = {{1}};
      array[1, 1] real value = exp2(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // expm1(array[,,,,]vector)=>array[,,,,]vector
    {
      array[1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}}};
      array[1, 1, 1, 1, 1] vector[1] value = expm1(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // expm1(vector)=>vector
    {
      vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)]';
      vector[1] value = expm1(arg_1);
      total += 1.234375 * sum(value);
    }
    // falling_factorial(array[,,,,]row_vector,array[,,,,,]int)=>array[,,,,]row_vector
    {
      array[1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{[(3.4500000000000002 + 0.0625 * seed)]}}}}};
      array[1, 1, 1, 1, 1, 1] int arg_2 = {{{{{{2}}}}}};
      array[1, 1, 1, 1, 1] row_vector[1] value = falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // falling_factorial(array[,,]vector,int)=>array[,,]vector
    {
      array[1, 1, 1] vector[1] arg_1 = {{{[(3.4500000000000002 + 0.0625 * seed)]'}}};
      int arg_2 = 2;
      array[1, 1, 1] vector[1] value = falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fdim(array[,,,,,,]matrix,array[,,,,,,]matrix)=>array[,,,,,,]matrix
    {
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{{{[[(0.94999999999999996 + 0.0625 * seed)]]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{{{{[[(0.94999999999999996 + 0.0625 * seed)]]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] value = fdim(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fdim(array[,,,,,,]row_vector,int)=>array[,,,,,,]row_vector
    {
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{{{[(0.94999999999999996 + 0.0625 * seed)]}}}}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] value = fdim(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fdim(array[,]row_vector,array[,]row_vector)=>array[,]row_vector
    {
      array[1, 1] row_vector[1] arg_1 = {{[(0.94999999999999996 + 0.0625 * seed)]}};
      array[1, 1] row_vector[1] arg_2 = {{[(0.94999999999999996 + 0.0625 * seed)]}};
      array[1, 1] row_vector[1] value = fdim(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fdim(real,array[,,,,,,]real)=>array[,,,,,,]real
    {
      real arg_1 = (0.94999999999999996 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1, 1] real arg_2 = {{{{{{{(0.94999999999999996 + 0.0625 * seed)}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] real value = fdim(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fdim(real,array[,,,,]int)=>array[,,,,]real
    {
      real arg_1 = (0.94999999999999996 + 0.0625 * seed);
      array[1, 1, 1, 1, 1] int arg_2 = {{{{{1}}}}};
      array[1, 1, 1, 1, 1] real value = fdim(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fdim(real,array[,,,]int)=>array[,,,]real
    {
      real arg_1 = (0.94999999999999996 + 0.0625 * seed);
      array[1, 1, 1, 1] int arg_2 = {{{{1}}}};
      array[1, 1, 1, 1] real value = fdim(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fdim(real,matrix)=>matrix
    {
      real arg_1 = (0.94999999999999996 + 0.0625 * seed);
      matrix[1, 1] arg_2 = [[(0.94999999999999996 + 0.0625 * seed)]];
      matrix[1, 1] value = fdim(arg_1, arg_2);
      total += 1.21875 * sum(value);
    }
    // floor(array[,,,,,]real)=>array[,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{(0.45000000000000001 + 0.0625 * seed)}}}}}};
      array[1, 1, 1, 1, 1, 1] real value = floor(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // fmax(array[,,,,,]int,real)=>array[,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{1}}}}}};
      real arg_2 = (0.94999999999999996 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1] real value = fmax(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmax(array[,,,]int,int)=>array[,,,]real
    {
      array[1, 1, 1, 1] int arg_1 = {{{{1}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1] real value = fmax(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmax(array[,,]matrix,real)=>array[,,]matrix
    {
      array[1, 1, 1] matrix[1, 1] arg_1 = {{{[[(0.94999999999999996 + 0.0625 * seed)]]}}};
      real arg_2 = (0.94999999999999996 + 0.0625 * seed);
      array[1, 1, 1] matrix[1, 1] value = fmax(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmax(array[,,]vector,int)=>array[,,]vector
    {
      array[1, 1, 1] vector[1] arg_1 = {{{[(0.94999999999999996 + 0.0625 * seed)]'}}};
      int arg_2 = 1;
      array[1, 1, 1] vector[1] value = fmax(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmax(array[,]int,int)=>array[,]real
    {
      array[1, 1] int arg_1 = {{1}};
      int arg_2 = 1;
      array[1, 1] real value = fmax(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmax(array[,]real,real)=>array[,]real
    {
      array[1, 1] real arg_1 = {{(0.94999999999999996 + 0.0625 * seed)}};
      real arg_2 = (0.94999999999999996 + 0.0625 * seed);
      array[1, 1] real value = fmax(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmax(real,int)=>real
    {
      real arg_1 = (0.94999999999999996 + 0.0625 * seed);
      int arg_2 = 1;
      real value = fmax(arg_1, arg_2);
      total += 1.234375 * value;
    }
    // fmin(array[,,,]real,array[,,,]real)=>array[,,,]real
    {
      array[1, 1, 1, 1] real arg_1 = {{{{(0.94999999999999996 + 0.0625 * seed)}}}};
      array[1, 1, 1, 1] real arg_2 = {{{{(0.94999999999999996 + 0.0625 * seed)}}}};
      array[1, 1, 1, 1] real value = fmin(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmin(array[,,]vector,array[,,]vector)=>array[,,]vector
    {
      array[1, 1, 1] vector[1] arg_1 = {{{[(0.94999999999999996 + 0.0625 * seed)]'}}};
      array[1, 1, 1] vector[1] arg_2 = {{{[(0.94999999999999996 + 0.0625 * seed)]'}}};
      array[1, 1, 1] vector[1] value = fmin(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmin(int,array[,,,,,,]matrix)=>array[,,,,,,]matrix
    {
      int arg_1 = 1;
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{{{{[[(0.94999999999999996 + 0.0625 * seed)]]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] value = fmin(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmin(int,array[]real)=>array[]real
    {
      int arg_1 = 1;
      array[1] real arg_2 = {(0.94999999999999996 + 0.0625 * seed)};
      array[1] real value = fmin(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmod(array[,]int,real)=>array[,]real
    {
      array[1, 1] int arg_1 = {{2}};
      real arg_2 = (0.94999999999999996 + 0.0625 * seed);
      array[1, 1] real value = fmod(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmod(int,array[,,,,,,]int)=>array[,,,,,,]real
    {
      int arg_1 = 2;
      array[1, 1, 1, 1, 1, 1, 1] int arg_2 = {{{{{{{1}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] real value = fmod(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmod(int,array[,,,,]matrix)=>array[,,,,]matrix
    {
      int arg_1 = 2;
      array[1, 1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{{[[(0.94999999999999996 + 0.0625 * seed)]]}}}}};
      array[1, 1, 1, 1, 1] matrix[1, 1] value = fmod(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmod(int,array[,]matrix)=>array[,]matrix
    {
      int arg_1 = 2;
      array[1, 1] matrix[1, 1] arg_2 = {{[[(0.94999999999999996 + 0.0625 * seed)]]}};
      array[1, 1] matrix[1, 1] value = fmod(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmod(real,array[,,,]real)=>array[,,,]real
    {
      real arg_1 = (2.4500000000000002 + 0.0625 * seed);
      array[1, 1, 1, 1] real arg_2 = {{{{(0.94999999999999996 + 0.0625 * seed)}}}};
      array[1, 1, 1, 1] real value = fmod(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmod(real,real)=>real
    {
      real arg_1 = (2.4500000000000002 + 0.0625 * seed);
      real arg_2 = (0.94999999999999996 + 0.0625 * seed);
      real value = fmod(arg_1, arg_2);
      total += 1.1875 * value;
    }
    // fmod(real,vector)=>vector
    {
      real arg_1 = (2.4500000000000002 + 0.0625 * seed);
      vector[1] arg_2 = [(0.94999999999999996 + 0.0625 * seed)]';
      vector[1] value = fmod(arg_1, arg_2);
      total += 1.140625 * sum(value);
    }
    // fmod(row_vector,row_vector)=>row_vector
    {
      row_vector[1] arg_1 = [(2.4500000000000002 + 0.0625 * seed)];
      row_vector[1] arg_2 = [(0.94999999999999996 + 0.0625 * seed)];
      row_vector[1] value = fmod(arg_1, arg_2);
      total += 1.203125 * sum(value);
    }
    // gamma_p(array[,,,,]matrix,real)=>array[,,,,]matrix
    {
      array[1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{[[(1.95 + 0.0625 * seed)]]}}}}};
      real arg_2 = (1.25 + 0.0625 * seed);
      array[1, 1, 1, 1, 1] matrix[1, 1] value = gamma_p(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // gamma_p(array[,,]row_vector,real)=>array[,,]row_vector
    {
      array[1, 1, 1] row_vector[1] arg_1 = {{{[(1.95 + 0.0625 * seed)]}}};
      real arg_2 = (1.25 + 0.0625 * seed);
      array[1, 1, 1] row_vector[1] value = gamma_p(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // gamma_q(array[,,,]row_vector,array[,,,]row_vector)=>array[,,,]row_vector
    {
      array[1, 1, 1, 1] row_vector[1] arg_1 = {{{{[(1.95 + 0.0625 * seed)]}}}};
      array[1, 1, 1, 1] row_vector[1] arg_2 = {{{{[(1.25 + 0.0625 * seed)]}}}};
      array[1, 1, 1, 1] row_vector[1] value = gamma_q(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // head(array[,,]row_vector,int)=>array[,,]row_vector
    {
      array[1, 1, 1] row_vector[1] arg_1 = {{{[(0.45000000000000001 + 0.0625 * seed)]}}};
      array[1, 1, 1] row_vector[1] value = head(arg_1, 1);
      if (seed > 1e100)
        print(value);
    }
    // hypot(array[,,,,,]row_vector,array[,,,,,]row_vector)=>array[,,,,,]row_vector
    {
      array[1, 1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{{[(0.45000000000000001 + 0.0625 * seed)]}}}}}};
      array[1, 1, 1, 1, 1, 1] row_vector[1] arg_2 = {{{{{{[(1.2 + 0.0625 * seed)]}}}}}};
      array[1, 1, 1, 1, 1, 1] row_vector[1] value = hypot(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // hypot(array[,,,,]real,int)=>array[,,,,]real
    {
      array[1, 1, 1, 1, 1] real arg_1 = {{{{{(0.45000000000000001 + 0.0625 * seed)}}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1, 1] real value = hypot(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // hypot(array[,,,,]vector,array[,,,,]vector)=>array[,,,,]vector
    {
      array[1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}}};
      array[1, 1, 1, 1, 1] vector[1] arg_2 = {{{{{[(1.2 + 0.0625 * seed)]'}}}}};
      array[1, 1, 1, 1, 1] vector[1] value = hypot(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // hypot(array[,,,]matrix,array[,,,]matrix)=>array[,,,]matrix
    {
      array[1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}};
      array[1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{[[(1.2 + 0.0625 * seed)]]}}}};
      array[1, 1, 1, 1] matrix[1, 1] value = hypot(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // hypot(array[]real,real)=>array[]real
    {
      array[1] real arg_1 = {(0.45000000000000001 + 0.0625 * seed)};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1] real value = hypot(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // hypot(int,array[,,,,,]vector)=>array[,,,,,]vector
    {
      int arg_1 = 0;
      array[1, 1, 1, 1, 1, 1] vector[1] arg_2 = {{{{{{[(1.2 + 0.0625 * seed)]'}}}}}};
      array[1, 1, 1, 1, 1, 1] vector[1] value = hypot(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // hypot(int,vector)=>vector
    {
      int arg_1 = 0;
      vector[1] arg_2 = [(1.2 + 0.0625 * seed)]';
      vector[1] value = hypot(arg_1, arg_2);
      total += 1.234375 * sum(value);
    }
    // hypot(real,array[,,,,,]real)=>array[,,,,,]real
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1] real arg_2 = {{{{{{(1.2 + 0.0625 * seed)}}}}}};
      array[1, 1, 1, 1, 1, 1] real value = hypot(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // hypot(real,array[,,,]int)=>array[,,,]real
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1, 1, 1] int arg_2 = {{{{1}}}};
      array[1, 1, 1, 1] real value = hypot(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // hypot(real,array[,,]vector)=>array[,,]vector
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1, 1] vector[1] arg_2 = {{{[(1.2 + 0.0625 * seed)]'}}};
      array[1, 1, 1] vector[1] value = hypot(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // inv(real)=>real
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      real value = inv(arg_1);
      total += 1.25 * value;
    }
    // inv_cloglog(array[,,,]vector)=>array[,,,]vector
    {
      array[1, 1, 1, 1] vector[1] arg_1 = {{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}};
      array[1, 1, 1, 1] vector[1] value = inv_cloglog(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // inv_cloglog(array[,,]real)=>array[,,]real
    {
      array[1, 1, 1] real arg_1 = {{{(0.45000000000000001 + 0.0625 * seed)}}};
      array[1, 1, 1] real value = inv_cloglog(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // inv_erfc(array[,,,,]real)=>array[,,,,]real
    {
      array[1, 1, 1, 1, 1] real arg_1 = {{{{{(0.45000000000000001 + 0.0625 * seed)}}}}};
      array[1, 1, 1, 1, 1] real value = inv_erfc(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // inv_erfc(array[,,]real)=>array[,,]real
    {
      array[1, 1, 1] real arg_1 = {{{(0.45000000000000001 + 0.0625 * seed)}}};
      array[1, 1, 1] real value = inv_erfc(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // inv_erfc(array[,]int)=>array[,]real
    {
      array[1, 1] int arg_1 = {{1}};
      array[1, 1] real value = inv_erfc(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // inv_sqrt(array[,,,,,,]vector)=>array[,,,,,,]vector
    {
      array[1, 1, 1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{{{[(1.3499999999999999 + 0.0625 * seed)]'}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] vector[1] value = inv_sqrt(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // lambert_wm1(array[,,,,]real)=>array[,,,,]real
    {
      array[1, 1, 1, 1, 1] real arg_1 = {{{{{(-0.25 + 0.0625 * seed)}}}}};
      array[1, 1, 1, 1, 1] real value = lambert_wm1(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // lbeta(array[,,,,,,]matrix,array[,,,,,,]matrix)=>array[,,,,,,]matrix
    {
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{{{[[(1.95 + 0.0625 * seed)]]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{{{{[[(2.9500000000000002 + 0.0625 * seed)]]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] value = lbeta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lbeta(array[,,,]vector,array[,,,]vector)=>array[,,,]vector
    {
      array[1, 1, 1, 1] vector[1] arg_1 = {{{{[(1.95 + 0.0625 * seed)]'}}}};
      array[1, 1, 1, 1] vector[1] arg_2 = {{{{[(2.9500000000000002 + 0.0625 * seed)]'}}}};
      array[1, 1, 1, 1] vector[1] value = lbeta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lbeta(array[,,]int,array[,,]int)=>array[,,]real
    {
      array[1, 1, 1] int arg_1 = {{{2}}};
      array[1, 1, 1] int arg_2 = {{{3}}};
      array[1, 1, 1] real value = lbeta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lbeta(int,array[]vector)=>array[]vector
    {
      int arg_1 = 2;
      array[1] vector[1] arg_2 = {[(2.9500000000000002 + 0.0625 * seed)]'};
      array[1] vector[1] value = lbeta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lchoose(array[,]row_vector,array[,]row_vector)=>array[,]row_vector
    {
      array[1, 1] row_vector[1] arg_1 = {{[(3.9500000000000002 + 0.0625 * seed)]}};
      array[1, 1] row_vector[1] arg_2 = {{[(1.95 + 0.0625 * seed)]}};
      array[1, 1] row_vector[1] value = lchoose(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lchoose(array[]row_vector,array[]row_vector)=>array[]row_vector
    {
      array[1] row_vector[1] arg_1 = {[(3.9500000000000002 + 0.0625 * seed)]};
      array[1] row_vector[1] arg_2 = {[(1.95 + 0.0625 * seed)]};
      array[1] row_vector[1] value = lchoose(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lchoose(int,array[,,,,,]row_vector)=>array[,,,,,]row_vector
    {
      int arg_1 = 4;
      array[1, 1, 1, 1, 1, 1] row_vector[1] arg_2 = {{{{{{[(1.95 + 0.0625 * seed)]}}}}}};
      array[1, 1, 1, 1, 1, 1] row_vector[1] value = lchoose(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lchoose(real,array[,,,,,,,]int)=>array[,,,,,,,]real
    {
      real arg_1 = (3.9500000000000002 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1, 1, 1] int arg_2 = {{{{{{{{2}}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1, 1] real value = lchoose(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lchoose(real,array[,,]real)=>array[,,]real
    {
      real arg_1 = (3.9500000000000002 + 0.0625 * seed);
      array[1, 1, 1] real arg_2 = {{{(1.95 + 0.0625 * seed)}}};
      array[1, 1, 1] real value = lchoose(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lchoose(real,array[,]real)=>array[,]real
    {
      real arg_1 = (3.9500000000000002 + 0.0625 * seed);
      array[1, 1] real arg_2 = {{(1.95 + 0.0625 * seed)}};
      array[1, 1] real value = lchoose(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // ldexp(array[,,,,,]real,array[,,,,,]int)=>array[,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{(0.45000000000000001 + 0.0625 * seed)}}}}}};
      array[1, 1, 1, 1, 1, 1] int arg_2 = {{{{{{2}}}}}};
      array[1, 1, 1, 1, 1, 1] real value = ldexp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // ldexp(array[,,,,,]vector,array[,,,,,,]int)=>array[,,,,,]vector
    {
      array[1, 1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] int arg_2 = {{{{{{{2}}}}}}};
      array[1, 1, 1, 1, 1, 1] vector[1] value = ldexp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // ldexp(array[,,,,,]vector,int)=>array[,,,,,]vector
    {
      array[1, 1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}}}};
      int arg_2 = 2;
      array[1, 1, 1, 1, 1, 1] vector[1] value = ldexp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // ldexp(array[,,,]matrix,int)=>array[,,,]matrix
    {
      array[1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}};
      int arg_2 = 2;
      array[1, 1, 1, 1] matrix[1, 1] value = ldexp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // ldexp(matrix,int)=>matrix
    {
      matrix[1, 1] arg_1 = [[(0.45000000000000001 + 0.0625 * seed)]];
      int arg_2 = 2;
      matrix[1, 1] value = ldexp(arg_1, arg_2);
      total += 1.234375 * sum(value);
    }
    // lgamma(array[,,,]row_vector)=>array[,,,]row_vector
    {
      array[1, 1, 1, 1] row_vector[1] arg_1 = {{{{[(1.3499999999999999 + 0.0625 * seed)]}}}};
      array[1, 1, 1, 1] row_vector[1] value = lgamma(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // linspaced_array(int,real,real)=>array[]real
    {
      array[1] real value = linspaced_array(1, -0.050000000000000003, 0.94999999999999996);
      if (seed > 1e100)
        print(value);
    }
    // lmultiply(array[,,,,,,,]real,array[,,,,,,,]real)=>array[,,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{{{(0.45000000000000001 + 0.0625 * seed)}}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1, 1] real arg_2 = {{{{{{{{(1.2 + 0.0625 * seed)}}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1, 1] real value = lmultiply(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lmultiply(array[,,,,,,]matrix,array[,,,,,,]matrix)=>array[,,,,,,]matrix
    {
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{{{{[[(1.2 + 0.0625 * seed)]]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] value = lmultiply(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lmultiply(array[,,,,,]int,array[,,,,,]int)=>array[,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{0}}}}}};
      array[1, 1, 1, 1, 1, 1] int arg_2 = {{{{{{1}}}}}};
      array[1, 1, 1, 1, 1, 1] real value = lmultiply(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lmultiply(array[,,,]vector,int)=>array[,,,]vector
    {
      array[1, 1, 1, 1] vector[1] arg_1 = {{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1] vector[1] value = lmultiply(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lmultiply(array[,,]matrix,int)=>array[,,]matrix
    {
      array[1, 1, 1] matrix[1, 1] arg_1 = {{{[[(0.45000000000000001 + 0.0625 * seed)]]}}};
      int arg_2 = 1;
      array[1, 1, 1] matrix[1, 1] value = lmultiply(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lmultiply(matrix,int)=>matrix
    {
      matrix[1, 1] arg_1 = [[(0.45000000000000001 + 0.0625 * seed)]];
      int arg_2 = 1;
      matrix[1, 1] value = lmultiply(arg_1, arg_2);
      total += 1 * sum(value);
    }
    // lmultiply(real,array[,,,,,,]real)=>array[,,,,,,]real
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1, 1] real arg_2 = {{{{{{{(1.2 + 0.0625 * seed)}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] real value = lmultiply(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lmultiply(real,array[,,,,]matrix)=>array[,,,,]matrix
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{{[[(1.2 + 0.0625 * seed)]]}}}}};
      array[1, 1, 1, 1, 1] matrix[1, 1] value = lmultiply(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lmultiply(real,array[,,,]real)=>array[,,,]real
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1, 1, 1] real arg_2 = {{{{(1.2 + 0.0625 * seed)}}}};
      array[1, 1, 1, 1] real value = lmultiply(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log(array[,,,,,,]matrix)=>array[,,,,,,]matrix
    {
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{{{[[(1.3499999999999999 + 0.0625 * seed)]]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] value = log(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log(array[,,,,,]row_vector)=>array[,,,,,]row_vector
    {
      array[1, 1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{{[(1.3499999999999999 + 0.0625 * seed)]}}}}}};
      array[1, 1, 1, 1, 1, 1] row_vector[1] value = log(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log10(array[,,,,]vector)=>array[,,,,]vector
    {
      array[1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{[(1.3499999999999999 + 0.0625 * seed)]'}}}}};
      array[1, 1, 1, 1, 1] vector[1] value = log10(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log10(array[]int)=>array[]real
    {
      array[1] int arg_1 = {1};
      array[1] real value = log10(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log10(array[]vector)=>array[]vector
    {
      array[1] vector[1] arg_1 = {[(1.3499999999999999 + 0.0625 * seed)]'};
      array[1] vector[1] value = log10(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log1m(array[,,,,]int)=>array[,,,,]real
    {
      array[1, 1, 1, 1, 1] int arg_1 = {{{{{0}}}}};
      array[1, 1, 1, 1, 1] real value = log1m(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log1m_exp(array[,,,,]matrix)=>array[,,,,]matrix
    {
      array[1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{[[(-0.55000000000000004 + 0.0625 * seed)]]}}}}};
      array[1, 1, 1, 1, 1] matrix[1, 1] value = log1m_exp(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log1m_exp(array[,,,,]row_vector)=>array[,,,,]row_vector
    {
      array[1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{[(-0.55000000000000004 + 0.0625 * seed)]}}}}};
      array[1, 1, 1, 1, 1] row_vector[1] value = log1m_exp(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log1m_exp(array[,,,]real)=>array[,,,]real
    {
      array[1, 1, 1, 1] real arg_1 = {{{{(-0.55000000000000004 + 0.0625 * seed)}}}};
      array[1, 1, 1, 1] real value = log1m_exp(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log1m_inv_logit(array[,,,,,]row_vector)=>array[,,,,,]row_vector
    {
      array[1, 1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{{[(0.45000000000000001 + 0.0625 * seed)]}}}}}};
      array[1, 1, 1, 1, 1, 1] row_vector[1] value = log1m_inv_logit(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log1m_inv_logit(row_vector)=>row_vector
    {
      row_vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)];
      row_vector[1] value = log1m_inv_logit(arg_1);
      total += 1.140625 * sum(value);
    }
    // log1p_exp(array[,,,,,]vector)=>array[,,,,,]vector
    {
      array[1, 1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}}}};
      array[1, 1, 1, 1, 1, 1] vector[1] value = log1p_exp(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log_diff_exp(array[,,,,,,]matrix,int)=>array[,,,,,,]matrix
    {
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{{{[[(1.45 + 0.0625 * seed)]]}}}}}}};
      int arg_2 = 0;
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] value = log_diff_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_diff_exp(array[,,,,]real,int)=>array[,,,,]real
    {
      array[1, 1, 1, 1, 1] real arg_1 = {{{{{(1.45 + 0.0625 * seed)}}}}};
      int arg_2 = 0;
      array[1, 1, 1, 1, 1] real value = log_diff_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_diff_exp(array[,,,]real,int)=>array[,,,]real
    {
      array[1, 1, 1, 1] real arg_1 = {{{{(1.45 + 0.0625 * seed)}}}};
      int arg_2 = 0;
      array[1, 1, 1, 1] real value = log_diff_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_diff_exp(int,array[,,,,,,]real)=>array[,,,,,,]real
    {
      int arg_1 = 1;
      array[1, 1, 1, 1, 1, 1, 1] real arg_2 = {{{{{{{(0.45000000000000001 + 0.0625 * seed)}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] real value = log_diff_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_diff_exp(int,array[,,,]real)=>array[,,,]real
    {
      int arg_1 = 1;
      array[1, 1, 1, 1] real arg_2 = {{{{(0.45000000000000001 + 0.0625 * seed)}}}};
      array[1, 1, 1, 1] real value = log_diff_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_diff_exp(int,array[,,]matrix)=>array[,,]matrix
    {
      int arg_1 = 1;
      array[1, 1, 1] matrix[1, 1] arg_2 = {{{[[(0.45000000000000001 + 0.0625 * seed)]]}}};
      array[1, 1, 1] matrix[1, 1] value = log_diff_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_diff_exp(int,array[,,]row_vector)=>array[,,]row_vector
    {
      int arg_1 = 1;
      array[1, 1, 1] row_vector[1] arg_2 = {{{[(0.45000000000000001 + 0.0625 * seed)]}}};
      array[1, 1, 1] row_vector[1] value = log_diff_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_diff_exp(real,array[,,,,,]real)=>array[,,,,,]real
    {
      real arg_1 = (1.45 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1] real arg_2 = {{{{{{(0.45000000000000001 + 0.0625 * seed)}}}}}};
      array[1, 1, 1, 1, 1, 1] real value = log_diff_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_diff_exp(real,array[,,,,]real)=>array[,,,,]real
    {
      real arg_1 = (1.45 + 0.0625 * seed);
      array[1, 1, 1, 1, 1] real arg_2 = {{{{{(0.45000000000000001 + 0.0625 * seed)}}}}};
      array[1, 1, 1, 1, 1] real value = log_diff_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_diff_exp(real,array[,,,]vector)=>array[,,,]vector
    {
      real arg_1 = (1.45 + 0.0625 * seed);
      array[1, 1, 1, 1] vector[1] arg_2 = {{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}};
      array[1, 1, 1, 1] vector[1] value = log_diff_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_diff_exp(real,array[,,]row_vector)=>array[,,]row_vector
    {
      real arg_1 = (1.45 + 0.0625 * seed);
      array[1, 1, 1] row_vector[1] arg_2 = {{{[(0.45000000000000001 + 0.0625 * seed)]}}};
      array[1, 1, 1] row_vector[1] value = log_diff_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_diff_exp(row_vector,int)=>row_vector
    {
      row_vector[1] arg_1 = [(1.45 + 0.0625 * seed)];
      int arg_2 = 0;
      row_vector[1] value = log_diff_exp(arg_1, arg_2);
      total += 1.1875 * sum(value);
    }
    // log_diff_exp(row_vector,real)=>row_vector
    {
      row_vector[1] arg_1 = [(1.45 + 0.0625 * seed)];
      real arg_2 = (0.45000000000000001 + 0.0625 * seed);
      row_vector[1] value = log_diff_exp(arg_1, arg_2);
      total += 1.03125 * sum(value);
    }
    // log_falling_factorial(array[,,,,,]matrix,real)=>array[,,,,,]matrix
    {
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{{[[(3.4500000000000002 + 0.0625 * seed)]]}}}}}};
      real arg_2 = (1.1499999999999999 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] value = log_falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_falling_factorial(real,array[,,,,]matrix)=>array[,,,,]matrix
    {
      real arg_1 = (3.4500000000000002 + 0.0625 * seed);
      array[1, 1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{{[[(1.1499999999999999 + 0.0625 * seed)]]}}}}};
      array[1, 1, 1, 1, 1] matrix[1, 1] value = log_falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_falling_factorial(real,array[,,]real)=>array[,,]real
    {
      real arg_1 = (3.4500000000000002 + 0.0625 * seed);
      array[1, 1, 1] real arg_2 = {{{(1.1499999999999999 + 0.0625 * seed)}}};
      array[1, 1, 1] real value = log_falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_falling_factorial(real,array[]matrix)=>array[]matrix
    {
      real arg_1 = (3.4500000000000002 + 0.0625 * seed);
      array[1] matrix[1, 1] arg_2 = {[[(1.1499999999999999 + 0.0625 * seed)]]};
      array[1] matrix[1, 1] value = log_falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_falling_factorial(vector,vector)=>vector
    {
      vector[1] arg_1 = [(3.4500000000000002 + 0.0625 * seed)]';
      vector[1] arg_2 = [(1.1499999999999999 + 0.0625 * seed)]';
      vector[1] value = log_falling_factorial(arg_1, arg_2);
      total += 1.203125 * sum(value);
    }
    // log_inv_logit(array[,,,,,]vector)=>array[,,,,,]vector
    {
      array[1, 1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}}}};
      array[1, 1, 1, 1, 1, 1] vector[1] value = log_inv_logit(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log_inv_logit(array[,]matrix)=>array[,]matrix
    {
      array[1, 1] matrix[1, 1] arg_1 = {{[[(0.45000000000000001 + 0.0625 * seed)]]}};
      array[1, 1] matrix[1, 1] value = log_inv_logit(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log_inv_logit_diff(array[,,,,,]real,real)=>array[,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{(0.94999999999999996 + 0.0625 * seed)}}}}}};
      real arg_2 = (-0.55000000000000004 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1] real value = log_inv_logit_diff(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_inv_logit_diff(int,array[,,,,]int)=>array[,,,,]real
    {
      int arg_1 = 1;
      array[1, 1, 1, 1, 1] int arg_2 = {{{{{0}}}}};
      array[1, 1, 1, 1, 1] real value = log_inv_logit_diff(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_inv_logit_diff(int,array[,]row_vector)=>array[,]row_vector
    {
      int arg_1 = 1;
      array[1, 1] row_vector[1] arg_2 = {{[(-0.55000000000000004 + 0.0625 * seed)]}};
      array[1, 1] row_vector[1] value = log_inv_logit_diff(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_inv_logit_diff(real,array[,,,,,,]int)=>array[,,,,,,]real
    {
      real arg_1 = (0.94999999999999996 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1, 1] int arg_2 = {{{{{{{0}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] real value = log_inv_logit_diff(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_inv_logit_diff(real,array[,]matrix)=>array[,]matrix
    {
      real arg_1 = (0.94999999999999996 + 0.0625 * seed);
      array[1, 1] matrix[1, 1] arg_2 = {{[[(-0.55000000000000004 + 0.0625 * seed)]]}};
      array[1, 1] matrix[1, 1] value = log_inv_logit_diff(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_modified_bessel_first_kind(array[,,,,,]matrix,int)=>array[,,,,,]matrix
    {
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] value = log_modified_bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_modified_bessel_first_kind(array[,,,]real,array[,,,]real)=>array[,,,]real
    {
      array[1, 1, 1, 1] real arg_1 = {{{{(0.45000000000000001 + 0.0625 * seed)}}}};
      array[1, 1, 1, 1] real arg_2 = {{{{(1.2 + 0.0625 * seed)}}}};
      array[1, 1, 1, 1] real value = log_modified_bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_modified_bessel_first_kind(int,array[,,]int)=>array[,,]real
    {
      int arg_1 = 0;
      array[1, 1, 1] int arg_2 = {{{1}}};
      array[1, 1, 1] real value = log_modified_bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_modified_bessel_first_kind(real,array[,,,,]matrix)=>array[,,,,]matrix
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{{[[(1.2 + 0.0625 * seed)]]}}}}};
      array[1, 1, 1, 1, 1] matrix[1, 1] value = log_modified_bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_rising_factorial(array[,,,,,,]matrix,array[,,,,,,]matrix)=>array[,,,,,,]matrix
    {
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{{{[[(1.45 + 0.0625 * seed)]]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{{{{[[(1.1499999999999999 + 0.0625 * seed)]]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] value = log_rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_rising_factorial(array[,,,,,]vector,int)=>array[,,,,,]vector
    {
      array[1, 1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{{[(1.45 + 0.0625 * seed)]'}}}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1, 1, 1] vector[1] value = log_rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_rising_factorial(array[,]real,real)=>array[,]real
    {
      array[1, 1] real arg_1 = {{(1.45 + 0.0625 * seed)}};
      real arg_2 = (1.1499999999999999 + 0.0625 * seed);
      array[1, 1] real value = log_rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_rising_factorial(array[]matrix,real)=>array[]matrix
    {
      array[1] matrix[1, 1] arg_1 = {[[(1.45 + 0.0625 * seed)]]};
      real arg_2 = (1.1499999999999999 + 0.0625 * seed);
      array[1] matrix[1, 1] value = log_rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_rising_factorial(matrix,matrix)=>matrix
    {
      matrix[1, 1] arg_1 = [[(1.45 + 0.0625 * seed)]];
      matrix[1, 1] arg_2 = [[(1.1499999999999999 + 0.0625 * seed)]];
      matrix[1, 1] value = log_rising_factorial(arg_1, arg_2);
      total += 1.015625 * sum(value);
    }
    // log_rising_factorial(real,array[,,,]matrix)=>array[,,,]matrix
    {
      real arg_1 = (1.45 + 0.0625 * seed);
      array[1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{[[(1.1499999999999999 + 0.0625 * seed)]]}}}};
      array[1, 1, 1, 1] matrix[1, 1] value = log_rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_softmax(vector)=>vector
    {
      vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)]';
      vector[1] value = log_softmax(arg_1);
      total += 1.234375 * sum(value);
    }
    // log_sum_exp(array[,,,,,,,]real,real)=>array[,,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{{{(0.45000000000000001 + 0.0625 * seed)}}}}}}}};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1, 1, 1] real value = log_sum_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_sum_exp(array[,,,]real,int)=>array[,,,]real
    {
      array[1, 1, 1, 1] real arg_1 = {{{{(0.45000000000000001 + 0.0625 * seed)}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1] real value = log_sum_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_sum_exp(array[,,,]real,real)=>array[,,,]real
    {
      array[1, 1, 1, 1] real arg_1 = {{{{(0.45000000000000001 + 0.0625 * seed)}}}};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1, 1, 1, 1] real value = log_sum_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_sum_exp(array[,,,]row_vector,array[,,,]row_vector)=>array[,,,]row_vector
    {
      array[1, 1, 1, 1] row_vector[1] arg_1 = {{{{[(0.45000000000000001 + 0.0625 * seed)]}}}};
      array[1, 1, 1, 1] row_vector[1] arg_2 = {{{{[(1.2 + 0.0625 * seed)]}}}};
      array[1, 1, 1, 1] row_vector[1] value = log_sum_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_sum_exp(array[,,,]row_vector,real)=>array[,,,]row_vector
    {
      array[1, 1, 1, 1] row_vector[1] arg_1 = {{{{[(0.45000000000000001 + 0.0625 * seed)]}}}};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1, 1, 1, 1] row_vector[1] value = log_sum_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_sum_exp(int,array[,,,,,,]int)=>array[,,,,,,]real
    {
      int arg_1 = 0;
      array[1, 1, 1, 1, 1, 1, 1] int arg_2 = {{{{{{{1}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] real value = log_sum_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_sum_exp(int,array[,,,]int)=>array[,,,]real
    {
      int arg_1 = 0;
      array[1, 1, 1, 1] int arg_2 = {{{{1}}}};
      array[1, 1, 1, 1] real value = log_sum_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // logical_gt(real,int)=>int
    {
      int value = logical_gt(0.45000000000000001, 1);
      total += 1.21875 * value;
    }
    // mean(matrix)=>real
    {
      matrix[1, 1] arg_1 = [[(0.45000000000000001 + 0.0625 * seed)]];
      real value = mean(arg_1);
      total += 1.078125 * value;
    }
    // minus(array[,,,,,,]int)=>array[,,,,,,]int
    {
      array[1, 1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{{2}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] int value = minus(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // minus(array[,,,,]row_vector)=>array[,,,,]row_vector
    {
      array[1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{[(0.45000000000000001 + 0.0625 * seed)]}}}}};
      array[1, 1, 1, 1, 1] row_vector[1] value = minus(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // modified_bessel_first_kind(array[,,,,,,]int,real)=>array[,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{{2}}}}}}};
      real arg_2 = (1.3499999999999999 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1, 1] real value = modified_bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // modified_bessel_first_kind(int,array[,]matrix)=>array[,]matrix
    {
      int arg_1 = 2;
      array[1, 1] matrix[1, 1] arg_2 = {{[[(1.3499999999999999 + 0.0625 * seed)]]}};
      array[1, 1] matrix[1, 1] value = modified_bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // modified_bessel_second_kind(int,array[,,,]row_vector)=>array[,,,]row_vector
    {
      int arg_1 = 2;
      array[1, 1, 1, 1] row_vector[1] arg_2 = {{{{[(1.3499999999999999 + 0.0625 * seed)]}}}};
      array[1, 1, 1, 1] row_vector[1] value = modified_bessel_second_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // modified_bessel_second_kind(int,real)=>real
    {
      int arg_1 = 2;
      real arg_2 = (1.3499999999999999 + 0.0625 * seed);
      real value = modified_bessel_second_kind(arg_1, arg_2);
      total += 1.015625 * value;
    }
    // multiply(real,real)=>real
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      real arg_2 = (1.2 + 0.0625 * seed);
      real value = multiply(arg_1, arg_2);
      total += 1.09375 * value;
    }
    // num_elements(array[,,,,,]int)=>int
    {
      array[1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{2}}}}}};
      int value = num_elements(arg_1);
      total += 1.0625 * value;
    }
    // num_elements(array[,,]matrix)=>int
    {
      array[1, 1, 1] matrix[1, 1] arg_1 = {{{[[(0.45000000000000001 + 0.0625 * seed)]]}}};
      int value = num_elements(arg_1);
      total += 1.21875 * value;
    }
    // owens_t(array[,,,,]real,array[,,,,]real)=>array[,,,,]real
    {
      array[1, 1, 1, 1, 1] real arg_1 = {{{{{(0.45000000000000001 + 0.0625 * seed)}}}}};
      array[1, 1, 1, 1, 1] real arg_2 = {{{{{(1.2 + 0.0625 * seed)}}}}};
      array[1, 1, 1, 1, 1] real value = owens_t(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // owens_t(array[,,,]vector,array[,,,]vector)=>array[,,,]vector
    {
      array[1, 1, 1, 1] vector[1] arg_1 = {{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}};
      array[1, 1, 1, 1] vector[1] arg_2 = {{{{[(1.2 + 0.0625 * seed)]'}}}};
      array[1, 1, 1, 1] vector[1] value = owens_t(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // pow(array[,,,,,,]real,int)=>array[,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{{(0.45000000000000001 + 0.0625 * seed)}}}}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1, 1, 1, 1] real value = pow(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // pow(array[,,,,,]matrix,array[,,,,,]matrix)=>array[,,,,,]matrix
    {
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}}}};
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{{{[[(1.2 + 0.0625 * seed)]]}}}}}};
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] value = pow(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // pow(array[,,,,,]vector,real)=>array[,,,,,]vector
    {
      array[1, 1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}}}};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1] vector[1] value = pow(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // pow(array[,]vector,array[,]vector)=>array[,]vector
    {
      array[1, 1] vector[1] arg_1 = {{[(0.45000000000000001 + 0.0625 * seed)]'}};
      array[1, 1] vector[1] arg_2 = {{[(1.2 + 0.0625 * seed)]'}};
      array[1, 1] vector[1] value = pow(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // pow(array[]row_vector,real)=>array[]row_vector
    {
      array[1] row_vector[1] arg_1 = {[(0.45000000000000001 + 0.0625 * seed)]};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1] row_vector[1] value = pow(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // pow(int,array[,,,,,]int)=>array[,,,,,]real
    {
      int arg_1 = 0;
      array[1, 1, 1, 1, 1, 1] int arg_2 = {{{{{{1}}}}}};
      array[1, 1, 1, 1, 1, 1] real value = pow(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // pow(real,array[,,]real)=>array[,,]real
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1, 1] real arg_2 = {{{(1.2 + 0.0625 * seed)}}};
      array[1, 1, 1] real value = pow(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // rep_array(array[]matrix,int,int)=>array[,,]matrix
    {
      array[1] matrix[1, 1] arg_1 = {[[(0.45000000000000001 + 0.0625 * seed)]]};
      array[1, 1, 1] matrix[1, 1] value = rep_array(arg_1, 1, 1);
      if (seed > 1e100)
        print(value);
    }
    // rep_array(array[]row_vector,int,int)=>array[,,]row_vector
    {
      array[1] row_vector[1] arg_1 = {[(0.45000000000000001 + 0.0625 * seed)]};
      array[1, 1, 1] row_vector[1] value = rep_array(arg_1, 1, 1);
      if (seed > 1e100)
        print(value);
    }
    // rep_array(int,int)=>array[]int
    {
      int arg_1 = 1;
      array[1] int value = rep_array(arg_1, 1);
      if (seed > 1e100)
        print(value);
    }
    // rep_array(vector,int,int)=>array[,]vector
    {
      vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)]';
      array[1, 1] vector[1] value = rep_array(arg_1, 1, 1);
      if (seed > 1e100)
        print(value);
    }
    // reverse(array[,,]real)=>array[,,]real
    {
      array[1, 1, 1] real arg_1 = {{{(0.45000000000000001 + 0.0625 * seed)}}};
      array[1, 1, 1] real value = reverse(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // reverse(array[,,]vector)=>array[,,]vector
    {
      array[1, 1, 1] vector[1] arg_1 = {{{[(0.45000000000000001 + 0.0625 * seed)]'}}};
      array[1, 1, 1] vector[1] value = reverse(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // sin(array[]real)=>array[]real
    {
      array[1] real arg_1 = {(0.45000000000000001 + 0.0625 * seed)};
      array[1] real value = sin(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // sinh(vector)=>vector
    {
      vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)]';
      vector[1] value = sinh(arg_1);
      total += 1.25 * sum(value);
    }
    // sqrt(array[,,,,]row_vector)=>array[,,,,]row_vector
    {
      array[1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{[(1.3499999999999999 + 0.0625 * seed)]}}}}};
      array[1, 1, 1, 1, 1] row_vector[1] value = sqrt(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // sqrt(array[,,]vector)=>array[,,]vector
    {
      array[1, 1, 1] vector[1] arg_1 = {{{[(1.3499999999999999 + 0.0625 * seed)]'}}};
      array[1, 1, 1] vector[1] value = sqrt(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // sqrt(array[]real)=>array[]real
    {
      array[1] real arg_1 = {(1.3499999999999999 + 0.0625 * seed)};
      array[1] real value = sqrt(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // square(array[,,,,,]real)=>array[,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{(0.45000000000000001 + 0.0625 * seed)}}}}}};
      array[1, 1, 1, 1, 1, 1] real value = square(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // square(array[,,,,]real)=>array[,,,,]real
    {
      array[1, 1, 1, 1, 1] real arg_1 = {{{{{(0.45000000000000001 + 0.0625 * seed)}}}}};
      array[1, 1, 1, 1, 1] real value = square(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // std_normal_log_qf(array[,,,,]matrix)=>array[,,,,]matrix
    {
      array[1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{[[(-0.55000000000000004 + 0.0625 * seed)]]}}}}};
      array[1, 1, 1, 1, 1] matrix[1, 1] value = std_normal_log_qf(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // std_normal_log_qf(array[,]matrix)=>array[,]matrix
    {
      array[1, 1] matrix[1, 1] arg_1 = {{[[(-0.55000000000000004 + 0.0625 * seed)]]}};
      array[1, 1] matrix[1, 1] value = std_normal_log_qf(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // std_normal_qf(int)=>real
    {
      int arg_1 = 0;
      real value = std_normal_qf(arg_1);
      total += 1.09375 * value;
    }
    // subtract(real,real)=>real
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      real arg_2 = (1.2 + 0.0625 * seed);
      real value = subtract(arg_1, arg_2);
      total += 1.234375 * value;
    }
    // subtract(vector,vector)=>vector
    {
      vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)]';
      vector[1] arg_2 = [(1.2 + 0.0625 * seed)]';
      vector[1] value = subtract(arg_1, arg_2);
      total += 1.09375 * sum(value);
    }
    // tail(array[]real,int)=>array[]real
    {
      array[1] real arg_1 = {(0.45000000000000001 + 0.0625 * seed)};
      array[1] real value = tail(arg_1, 1);
      if (seed > 1e100)
        print(value);
    }
    // tan(int)=>real
    {
      int arg_1 = 1;
      real value = tan(arg_1);
      total += 1.21875 * value;
    }
    // tanh(array[,,,,,]real)=>array[,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{(0.45000000000000001 + 0.0625 * seed)}}}}}};
      array[1, 1, 1, 1, 1, 1] real value = tanh(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // tanh(array[,,,]int)=>array[,,,]real
    {
      array[1, 1, 1, 1] int arg_1 = {{{{1}}}};
      array[1, 1, 1, 1] real value = tanh(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // to_matrix(vector,int,int)=>matrix
    {
      vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)]';
      matrix[1, 1] value = to_matrix(arg_1, 1, 1);
      total += 1.171875 * sum(value);
    }
    // transpose(row_vector)=>vector
    {
      row_vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)];
      vector[1] value = transpose(arg_1);
      total += 1 * sum(value);
    }
    // trigamma(array[,,,,,]int)=>array[,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{1}}}}}};
      array[1, 1, 1, 1, 1, 1] real value = trigamma(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // trigamma(array[,,,]real)=>array[,,,]real
    {
      array[1, 1, 1, 1] real arg_1 = {{{{(1.3499999999999999 + 0.0625 * seed)}}}};
      array[1, 1, 1, 1] real value = trigamma(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // trigamma(array[,]vector)=>array[,]vector
    {
      array[1, 1] vector[1] arg_1 = {{[(1.3499999999999999 + 0.0625 * seed)]'}};
      array[1, 1] vector[1] value = trigamma(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // trunc(array[,,,,,,]int)=>array[,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{{1}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] real value = trunc(arg_1);
      if (seed > 1e100)
        print(value);
    }
    return total;
  }
}
data {
  real context_seed;
}
transformed data {
  real transformed_data_result = builtin_signatures_16(context_seed);
}
parameters {
  real probe;
}
model {
  probe ~ std_normal();
  target += builtin_signatures_16(probe);
  if (probe > -1e100)
    target += builtin_signatures_16(probe);
}
generated quantities {
  real generated_quantities_result = builtin_signatures_16(probe);
}
