// STANLI-LIT: PASS
// STANLI-LIT-EXPECT: OK
// STANLI-LIT-DATA: {"context_seed": 0.0}
// STANLI-LIT-TIMEOUT: 180
// Generated by tools/generate_builtin_signature_models.py from the unified FunctionSpec registry
// and `stanc --dump-stan-math-signatures`. Do not edit by hand.
// Partition 25 of 30; 238 overloads.
functions {
  real builtin_signatures_25(real seed) {
    real total = 0;
    // Phi(array[,,,,]vector)=>array[,,,,]vector
    {
      array[1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}}};
      array[1, 1, 1, 1, 1] vector[1] value = Phi(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // Phi_approx(array[,,,,,]real)=>array[,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{(0.45000000000000001 + 0.0625 * seed)}}}}}};
      array[1, 1, 1, 1, 1, 1] real value = Phi_approx(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // abs(array[,,,,,,]int)=>array[,,,,,,]int
    {
      array[1, 1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{{2}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] int value = abs(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // abs(int)=>int
    {
      int arg_1 = 2;
      int value = abs(arg_1);
      total += 1.203125 * value;
    }
    // acosh(array[,,,,,]row_vector)=>array[,,,,,]row_vector
    {
      array[1, 1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{{[(1.3499999999999999 + 0.0625 * seed)]}}}}}};
      array[1, 1, 1, 1, 1, 1] row_vector[1] value = acosh(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // acosh(array[,]row_vector)=>array[,]row_vector
    {
      array[1, 1] row_vector[1] arg_1 = {{[(1.3499999999999999 + 0.0625 * seed)]}};
      array[1, 1] row_vector[1] value = acosh(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // acosh(array[]int)=>array[]real
    {
      array[1] int arg_1 = {1};
      array[1] real value = acosh(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // acosh(array[]matrix)=>array[]matrix
    {
      array[1] matrix[1, 1] arg_1 = {[[(1.3499999999999999 + 0.0625 * seed)]]};
      array[1] matrix[1, 1] value = acosh(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // append_array(array[,]int,array[,]int)=>array[,]int
    {
      array[1, 1] int arg_1 = {{1}};
      array[2, 1] int value = append_array(arg_1, {{1}});
      if (seed > 1e100)
        print(value);
    }
    // append_array(array[]row_vector,array[]row_vector)=>array[]row_vector
    {
      array[1] row_vector[1] arg_1 = {[(0.45000000000000001 + 0.0625 * seed)]};
      array[1] row_vector[1] arg_2 = {[(1.2 + 0.0625 * seed)]};
      array[2] row_vector[1] value = append_array(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // append_array(array[]vector,array[]vector)=>array[]vector
    {
      array[1] vector[1] arg_1 = {[(0.45000000000000001 + 0.0625 * seed)]'};
      array[1] vector[1] arg_2 = {[(1.2 + 0.0625 * seed)]'};
      array[2] vector[1] value = append_array(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // asin(array[,,,]row_vector)=>array[,,,]row_vector
    {
      array[1, 1, 1, 1] row_vector[1] arg_1 = {{{{[(0.29999999999999999 + 0.0625 * seed)]}}}};
      array[1, 1, 1, 1] row_vector[1] value = asin(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // asin(int)=>real
    {
      int arg_1 = 0;
      real value = asin(arg_1);
      total += 1.03125 * value;
    }
    // atan2(array[,,,,,]vector,array[,,,,,]vector)=>array[,,,,,]vector
    {
      array[1, 1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}}}};
      array[1, 1, 1, 1, 1, 1] vector[1] arg_2 = {{{{{{[(1.2 + 0.0625 * seed)]'}}}}}};
      array[1, 1, 1, 1, 1, 1] vector[1] value = atan2(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // atan2(int,array[,,,]int)=>array[,,,]real
    {
      int arg_1 = 0;
      array[1, 1, 1, 1] int arg_2 = {{{{1}}}};
      array[1, 1, 1, 1] real value = atan2(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // atan2(real,array[,,,,,,]matrix)=>array[,,,,,,]matrix
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{{{{[[(1.2 + 0.0625 * seed)]]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] value = atan2(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // atan2(real,array[,,,,]matrix)=>array[,,,,]matrix
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{{[[(1.2 + 0.0625 * seed)]]}}}}};
      array[1, 1, 1, 1, 1] matrix[1, 1] value = atan2(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // atan2(row_vector,row_vector)=>row_vector
    {
      row_vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)];
      row_vector[1] arg_2 = [(1.2 + 0.0625 * seed)];
      row_vector[1] value = atan2(arg_1, arg_2);
      total += 1.125 * sum(value);
    }
    // bessel_first_kind(array[,,,,,,]int,array[,,,,]matrix)=>array[,,,,]matrix
    {
      array[1, 1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{{2}}}}}}};
      array[1, 1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{{[[(1.3499999999999999 + 0.0625 * seed)]]}}}}};
      array[1, 1, 1, 1, 1] matrix[1, 1] value = bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // bessel_second_kind(array[,,,,,,,]int,array[,,,,,,,]real)=>array[,,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{{{2}}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1, 1] real arg_2 = {{{{{{{{(1.3499999999999999 + 0.0625 * seed)}}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1, 1] real value = bessel_second_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // bessel_second_kind(array[,,,]int,real)=>array[,,,]real
    {
      array[1, 1, 1, 1] int arg_1 = {{{{2}}}};
      real arg_2 = (1.3499999999999999 + 0.0625 * seed);
      array[1, 1, 1, 1] real value = bessel_second_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // bessel_second_kind(int,array[]matrix)=>array[]matrix
    {
      int arg_1 = 2;
      array[1] matrix[1, 1] arg_2 = {[[(1.3499999999999999 + 0.0625 * seed)]]};
      array[1] matrix[1, 1] value = bessel_second_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // beta(array[,,,,]int,int)=>array[,,,,]real
    {
      array[1, 1, 1, 1, 1] int arg_1 = {{{{{2}}}}};
      int arg_2 = 3;
      array[1, 1, 1, 1, 1] real value = beta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // beta(array[,,,]matrix,int)=>array[,,,]matrix
    {
      array[1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{[[(1.95 + 0.0625 * seed)]]}}}};
      int arg_2 = 3;
      array[1, 1, 1, 1] matrix[1, 1] value = beta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // beta(array[,,,]matrix,real)=>array[,,,]matrix
    {
      array[1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{[[(1.95 + 0.0625 * seed)]]}}}};
      real arg_2 = (2.9500000000000002 + 0.0625 * seed);
      array[1, 1, 1, 1] matrix[1, 1] value = beta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // beta(int,array[,,]int)=>array[,,]real
    {
      int arg_1 = 2;
      array[1, 1, 1] int arg_2 = {{{3}}};
      array[1, 1, 1] real value = beta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // beta(int,row_vector)=>row_vector
    {
      int arg_1 = 2;
      row_vector[1] arg_2 = [(2.9500000000000002 + 0.0625 * seed)];
      row_vector[1] value = beta(arg_1, arg_2);
      total += 1.015625 * sum(value);
    }
    // beta(real,array[]vector)=>array[]vector
    {
      real arg_1 = (1.95 + 0.0625 * seed);
      array[1] vector[1] arg_2 = {[(2.9500000000000002 + 0.0625 * seed)]'};
      array[1] vector[1] value = beta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // binary_log_loss(array[,,,,,,,,]int,array[,,,,,,]matrix)=>array[,,,,,,]matrix
    {
      array[1, 1, 1, 1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{{{{1}}}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{{{{[[(0.35000000000000003 + 0.0625 * seed)]]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] value = binary_log_loss(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // binary_log_loss(int,array[,,,,]real)=>array[,,,,]real
    {
      int arg_1 = 1;
      array[1, 1, 1, 1, 1] real arg_2 = {{{{{(0.35000000000000003 + 0.0625 * seed)}}}}};
      array[1, 1, 1, 1, 1] real value = binary_log_loss(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // choose(array[,,,,]int,int)=>array[,,,,]int
    {
      array[1, 1, 1, 1, 1] int arg_1 = {{{{{5}}}}};
      int arg_2 = 2;
      array[1, 1, 1, 1, 1] int value = choose(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // cos(array[,]matrix)=>array[,]matrix
    {
      array[1, 1] matrix[1, 1] arg_1 = {{[[(0.45000000000000001 + 0.0625 * seed)]]}};
      array[1, 1] matrix[1, 1] value = cos(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // cosh(array[,]row_vector)=>array[,]row_vector
    {
      array[1, 1] row_vector[1] arg_1 = {{[(0.45000000000000001 + 0.0625 * seed)]}};
      array[1, 1] row_vector[1] value = cosh(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // digamma(array[,,,,,,]row_vector)=>array[,,,,,,]row_vector
    {
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{{{[(1.3499999999999999 + 0.0625 * seed)]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] value = digamma(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // digamma(array[,,,,]real)=>array[,,,,]real
    {
      array[1, 1, 1, 1, 1] real arg_1 = {{{{{(1.3499999999999999 + 0.0625 * seed)}}}}};
      array[1, 1, 1, 1, 1] real value = digamma(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // digamma(array[,,,]real)=>array[,,,]real
    {
      array[1, 1, 1, 1] real arg_1 = {{{{(1.3499999999999999 + 0.0625 * seed)}}}};
      array[1, 1, 1, 1] real value = digamma(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // digamma(array[,,]int)=>array[,,]real
    {
      array[1, 1, 1] int arg_1 = {{{1}}};
      array[1, 1, 1] real value = digamma(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // digamma(vector)=>vector
    {
      vector[1] arg_1 = [(1.3499999999999999 + 0.0625 * seed)]';
      vector[1] value = digamma(arg_1);
      total += 1.25 * sum(value);
    }
    // dims(vector)=>array[]int
    {
      vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)]';
      array[2] int value = dims(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // elt_divide(row_vector,real)=>row_vector
    {
      row_vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)];
      real arg_2 = (1.2 + 0.0625 * seed);
      row_vector[1] value = elt_divide(arg_1, arg_2);
      total += 1.203125 * sum(value);
    }
    // elt_multiply(matrix,real)=>matrix
    {
      matrix[1, 1] arg_1 = [[(0.45000000000000001 + 0.0625 * seed)]];
      real arg_2 = (1.2 + 0.0625 * seed);
      matrix[1, 1] value = elt_multiply(arg_1, arg_2);
      total += 1.0625 * sum(value);
    }
    // erf(array[,,,,,,]row_vector)=>array[,,,,,,]row_vector
    {
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{{{[(0.45000000000000001 + 0.0625 * seed)]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] value = erf(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // erfc(array[,,,,,]matrix)=>array[,,,,,]matrix
    {
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}}}};
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] value = erfc(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // erfc(array[,,,,]real)=>array[,,,,]real
    {
      array[1, 1, 1, 1, 1] real arg_1 = {{{{{(0.45000000000000001 + 0.0625 * seed)}}}}};
      array[1, 1, 1, 1, 1] real value = erfc(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // erfc(real)=>real
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      real value = erfc(arg_1);
      total += 1.171875 * value;
    }
    // exp(array[,,,,,,]real)=>array[,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{{(0.45000000000000001 + 0.0625 * seed)}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] real value = exp(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // exp(array[,,,,]row_vector)=>array[,,,,]row_vector
    {
      array[1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{[(0.45000000000000001 + 0.0625 * seed)]}}}}};
      array[1, 1, 1, 1, 1] row_vector[1] value = exp(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // exp(array[]row_vector)=>array[]row_vector
    {
      array[1] row_vector[1] arg_1 = {[(0.45000000000000001 + 0.0625 * seed)]};
      array[1] row_vector[1] value = exp(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // exp2(array[,,,,,,]int)=>array[,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{{1}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] real value = exp2(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // expm1(array[,,,]row_vector)=>array[,,,]row_vector
    {
      array[1, 1, 1, 1] row_vector[1] arg_1 = {{{{[(0.45000000000000001 + 0.0625 * seed)]}}}};
      array[1, 1, 1, 1] row_vector[1] value = expm1(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // expm1(array[,,]matrix)=>array[,,]matrix
    {
      array[1, 1, 1] matrix[1, 1] arg_1 = {{{[[(0.45000000000000001 + 0.0625 * seed)]]}}};
      array[1, 1, 1] matrix[1, 1] value = expm1(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // expm1(matrix)=>matrix
    {
      matrix[1, 1] arg_1 = [[(0.45000000000000001 + 0.0625 * seed)]];
      matrix[1, 1] value = expm1(arg_1);
      total += 1.171875 * sum(value);
    }
    // falling_factorial(array[,,,,,]row_vector,array[,,,,,,]int)=>array[,,,,,]row_vector
    {
      array[1, 1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{{[(3.4500000000000002 + 0.0625 * seed)]}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] int arg_2 = {{{{{{{2}}}}}}};
      array[1, 1, 1, 1, 1, 1] row_vector[1] value = falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // falling_factorial(array[,,,,]row_vector,int)=>array[,,,,]row_vector
    {
      array[1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{[(3.4500000000000002 + 0.0625 * seed)]}}}}};
      int arg_2 = 2;
      array[1, 1, 1, 1, 1] row_vector[1] value = falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // falling_factorial(matrix,int)=>matrix
    {
      matrix[1, 1] arg_1 = [[(3.4500000000000002 + 0.0625 * seed)]];
      int arg_2 = 2;
      matrix[1, 1] value = falling_factorial(arg_1, arg_2);
      total += 1.15625 * sum(value);
    }
    // falling_factorial(vector,array[]int)=>vector
    {
      vector[1] arg_1 = [(3.4500000000000002 + 0.0625 * seed)]';
      array[1] int arg_2 = {2};
      vector[1] value = falling_factorial(arg_1, arg_2);
      total += 1.03125 * sum(value);
    }
    // fdim(array[,,,,,,,]int,real)=>array[,,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{{{1}}}}}}}};
      real arg_2 = (0.94999999999999996 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1, 1, 1] real value = fdim(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fdim(array[,,,,,,]int,array[,,,,,,]int)=>array[,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{{1}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] int arg_2 = {{{{{{{1}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] real value = fdim(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fdim(array[,,,,,,]row_vector,real)=>array[,,,,,,]row_vector
    {
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{{{[(0.94999999999999996 + 0.0625 * seed)]}}}}}}};
      real arg_2 = (0.94999999999999996 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] value = fdim(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fdim(int,real)=>real
    {
      int arg_1 = 1;
      real arg_2 = (0.94999999999999996 + 0.0625 * seed);
      real value = fdim(arg_1, arg_2);
      total += 1.1875 * value;
    }
    // floor(array[,,,,]matrix)=>array[,,,,]matrix
    {
      array[1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}}};
      array[1, 1, 1, 1, 1] matrix[1, 1] value = floor(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // floor(array[,,,]int)=>array[,,,]real
    {
      array[1, 1, 1, 1] int arg_1 = {{{{1}}}};
      array[1, 1, 1, 1] real value = floor(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // fmax(array[,,,,,,,]int,real)=>array[,,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{{{1}}}}}}}};
      real arg_2 = (0.94999999999999996 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1, 1, 1] real value = fmax(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmax(array[,,,,,]int,array[,,,,,]int)=>array[,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{1}}}}}};
      array[1, 1, 1, 1, 1, 1] int arg_2 = {{{{{{1}}}}}};
      array[1, 1, 1, 1, 1, 1] real value = fmax(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmax(array[,,]real,array[,,]real)=>array[,,]real
    {
      array[1, 1, 1] real arg_1 = {{{(0.94999999999999996 + 0.0625 * seed)}}};
      array[1, 1, 1] real arg_2 = {{{(0.94999999999999996 + 0.0625 * seed)}}};
      array[1, 1, 1] real value = fmax(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmax(array[,]real,array[,]real)=>array[,]real
    {
      array[1, 1] real arg_1 = {{(0.94999999999999996 + 0.0625 * seed)}};
      array[1, 1] real arg_2 = {{(0.94999999999999996 + 0.0625 * seed)}};
      array[1, 1] real value = fmax(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmax(int,array[,,,]vector)=>array[,,,]vector
    {
      int arg_1 = 1;
      array[1, 1, 1, 1] vector[1] arg_2 = {{{{[(0.94999999999999996 + 0.0625 * seed)]'}}}};
      array[1, 1, 1, 1] vector[1] value = fmax(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmax(real,array[,,,,,]row_vector)=>array[,,,,,]row_vector
    {
      real arg_1 = (0.94999999999999996 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1] row_vector[1] arg_2 = {{{{{{[(0.94999999999999996 + 0.0625 * seed)]}}}}}};
      array[1, 1, 1, 1, 1, 1] row_vector[1] value = fmax(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmax(real,array[]matrix)=>array[]matrix
    {
      real arg_1 = (0.94999999999999996 + 0.0625 * seed);
      array[1] matrix[1, 1] arg_2 = {[[(0.94999999999999996 + 0.0625 * seed)]]};
      array[1] matrix[1, 1] value = fmax(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmax(row_vector,row_vector)=>row_vector
    {
      row_vector[1] arg_1 = [(0.94999999999999996 + 0.0625 * seed)];
      row_vector[1] arg_2 = [(0.94999999999999996 + 0.0625 * seed)];
      row_vector[1] value = fmax(arg_1, arg_2);
      total += 1.203125 * sum(value);
    }
    // fmin(array[,,,,,,,]int,array[,,,,,,,]int)=>array[,,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{{{1}}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1, 1] int arg_2 = {{{{{{{{1}}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1, 1] real value = fmin(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmin(array[,,,,,]vector,real)=>array[,,,,,]vector
    {
      array[1, 1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{{[(0.94999999999999996 + 0.0625 * seed)]'}}}}}};
      real arg_2 = (0.94999999999999996 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1] vector[1] value = fmin(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmin(array[,,,,]matrix,real)=>array[,,,,]matrix
    {
      array[1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{[[(0.94999999999999996 + 0.0625 * seed)]]}}}}};
      real arg_2 = (0.94999999999999996 + 0.0625 * seed);
      array[1, 1, 1, 1, 1] matrix[1, 1] value = fmin(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmin(array[,]int,array[,]int)=>array[,]real
    {
      array[1, 1] int arg_1 = {{1}};
      array[1, 1] int arg_2 = {{1}};
      array[1, 1] real value = fmin(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmin(int,array[,,]int)=>array[,,]real
    {
      int arg_1 = 1;
      array[1, 1, 1] int arg_2 = {{{1}}};
      array[1, 1, 1] real value = fmin(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmin(real,array[,,,]int)=>array[,,,]real
    {
      real arg_1 = (0.94999999999999996 + 0.0625 * seed);
      array[1, 1, 1, 1] int arg_2 = {{{{1}}}};
      array[1, 1, 1, 1] real value = fmin(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmin(real,array[,,]int)=>array[,,]real
    {
      real arg_1 = (0.94999999999999996 + 0.0625 * seed);
      array[1, 1, 1] int arg_2 = {{{1}}};
      array[1, 1, 1] real value = fmin(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmin(real,array[,]row_vector)=>array[,]row_vector
    {
      real arg_1 = (0.94999999999999996 + 0.0625 * seed);
      array[1, 1] row_vector[1] arg_2 = {{[(0.94999999999999996 + 0.0625 * seed)]}};
      array[1, 1] row_vector[1] value = fmin(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmin(real,array[]vector)=>array[]vector
    {
      real arg_1 = (0.94999999999999996 + 0.0625 * seed);
      array[1] vector[1] arg_2 = {[(0.94999999999999996 + 0.0625 * seed)]'};
      array[1] vector[1] value = fmin(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmod(array[,,,,]int,real)=>array[,,,,]real
    {
      array[1, 1, 1, 1, 1] int arg_1 = {{{{{2}}}}};
      real arg_2 = (0.94999999999999996 + 0.0625 * seed);
      array[1, 1, 1, 1, 1] real value = fmod(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmod(int,array[,,,,,]matrix)=>array[,,,,,]matrix
    {
      int arg_1 = 2;
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{{{[[(0.94999999999999996 + 0.0625 * seed)]]}}}}}};
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] value = fmod(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmod(real,array[,,,,]vector)=>array[,,,,]vector
    {
      real arg_1 = (2.4500000000000002 + 0.0625 * seed);
      array[1, 1, 1, 1, 1] vector[1] arg_2 = {{{{{[(0.94999999999999996 + 0.0625 * seed)]'}}}}};
      array[1, 1, 1, 1, 1] vector[1] value = fmod(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmod(vector,real)=>vector
    {
      vector[1] arg_1 = [(2.4500000000000002 + 0.0625 * seed)]';
      real arg_2 = (0.94999999999999996 + 0.0625 * seed);
      vector[1] value = fmod(arg_1, arg_2);
      total += 1.15625 * sum(value);
    }
    // gamma_p(array[,,,,,]vector,real)=>array[,,,,,]vector
    {
      array[1, 1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{{[(1.95 + 0.0625 * seed)]'}}}}}};
      real arg_2 = (1.25 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1] vector[1] value = gamma_p(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // gamma_p(real,real)=>real
    {
      real arg_1 = (1.95 + 0.0625 * seed);
      real arg_2 = (1.25 + 0.0625 * seed);
      real value = gamma_p(arg_1, arg_2);
      total += 1.125 * value;
    }
    // gamma_q(real,array[,,,,,,]matrix)=>array[,,,,,,]matrix
    {
      real arg_1 = (1.95 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{{{{[[(1.25 + 0.0625 * seed)]]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] value = gamma_q(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // gamma_q(real,array[,]matrix)=>array[,]matrix
    {
      real arg_1 = (1.95 + 0.0625 * seed);
      array[1, 1] matrix[1, 1] arg_2 = {{[[(1.25 + 0.0625 * seed)]]}};
      array[1, 1] matrix[1, 1] value = gamma_q(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // hypot(array[,,,,,]row_vector,int)=>array[,,,,,]row_vector
    {
      array[1, 1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{{[(0.45000000000000001 + 0.0625 * seed)]}}}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1, 1, 1] row_vector[1] value = hypot(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // hypot(array[,,,,]vector,int)=>array[,,,,]vector
    {
      array[1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1, 1] vector[1] value = hypot(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // hypot(array[,,,]row_vector,int)=>array[,,,]row_vector
    {
      array[1, 1, 1, 1] row_vector[1] arg_1 = {{{{[(0.45000000000000001 + 0.0625 * seed)]}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1] row_vector[1] value = hypot(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // hypot(array[,,]matrix,array[,,]matrix)=>array[,,]matrix
    {
      array[1, 1, 1] matrix[1, 1] arg_1 = {{{[[(0.45000000000000001 + 0.0625 * seed)]]}}};
      array[1, 1, 1] matrix[1, 1] arg_2 = {{{[[(1.2 + 0.0625 * seed)]]}}};
      array[1, 1, 1] matrix[1, 1] value = hypot(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // hypot(int,array[,,,]int)=>array[,,,]real
    {
      int arg_1 = 0;
      array[1, 1, 1, 1] int arg_2 = {{{{1}}}};
      array[1, 1, 1, 1] real value = hypot(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // hypot(int,array[,]row_vector)=>array[,]row_vector
    {
      int arg_1 = 0;
      array[1, 1] row_vector[1] arg_2 = {{[(1.2 + 0.0625 * seed)]}};
      array[1, 1] row_vector[1] value = hypot(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // hypot(real,array[,]real)=>array[,]real
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1] real arg_2 = {{(1.2 + 0.0625 * seed)}};
      array[1, 1] real value = hypot(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // inv_Phi(array[,,,]row_vector)=>array[,,,]row_vector
    {
      array[1, 1, 1, 1] row_vector[1] arg_1 = {{{{[(0.45000000000000001 + 0.0625 * seed)]}}}};
      array[1, 1, 1, 1] row_vector[1] value = inv_Phi(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // inv_Phi(array[,,,]vector)=>array[,,,]vector
    {
      array[1, 1, 1, 1] vector[1] arg_1 = {{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}};
      array[1, 1, 1, 1] vector[1] value = inv_Phi(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // inv_Phi(array[,]vector)=>array[,]vector
    {
      array[1, 1] vector[1] arg_1 = {{[(0.45000000000000001 + 0.0625 * seed)]'}};
      array[1, 1] vector[1] value = inv_Phi(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // inv_Phi(array[]real)=>array[]real
    {
      array[1] real arg_1 = {(0.45000000000000001 + 0.0625 * seed)};
      array[1] real value = inv_Phi(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // inv_cloglog(array[]vector)=>array[]vector
    {
      array[1] vector[1] arg_1 = {[(0.45000000000000001 + 0.0625 * seed)]'};
      array[1] vector[1] value = inv_cloglog(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // inv_cloglog(int)=>real
    {
      int arg_1 = 1;
      real value = inv_cloglog(arg_1);
      total += 1.015625 * value;
    }
    // inv_square(array[,,,,,]int)=>array[,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{1}}}}}};
      array[1, 1, 1, 1, 1, 1] real value = inv_square(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // inv_square(array[,,,,]matrix)=>array[,,,,]matrix
    {
      array[1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}}};
      array[1, 1, 1, 1, 1] matrix[1, 1] value = inv_square(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // lambert_w0(array[,,,,]vector)=>array[,,,,]vector
    {
      array[1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}}};
      array[1, 1, 1, 1, 1] vector[1] value = lambert_w0(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // lambert_w0(array[]row_vector)=>array[]row_vector
    {
      array[1] row_vector[1] arg_1 = {[(0.45000000000000001 + 0.0625 * seed)]};
      array[1] row_vector[1] value = lambert_w0(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // lambert_wm1(array[,,,,,,]int)=>array[,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{{0}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] real value = lambert_wm1(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // lambert_wm1(array[,,,]vector)=>array[,,,]vector
    {
      array[1, 1, 1, 1] vector[1] arg_1 = {{{{[(-0.25 + 0.0625 * seed)]'}}}};
      array[1, 1, 1, 1] vector[1] value = lambert_wm1(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // lambert_wm1(array[,]row_vector)=>array[,]row_vector
    {
      array[1, 1] row_vector[1] arg_1 = {{[(-0.25 + 0.0625 * seed)]}};
      array[1, 1] row_vector[1] value = lambert_wm1(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // lambert_wm1(array[]row_vector)=>array[]row_vector
    {
      array[1] row_vector[1] arg_1 = {[(-0.25 + 0.0625 * seed)]};
      array[1] row_vector[1] value = lambert_wm1(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // lbeta(array[,,,]matrix,real)=>array[,,,]matrix
    {
      array[1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{[[(1.95 + 0.0625 * seed)]]}}}};
      real arg_2 = (2.9500000000000002 + 0.0625 * seed);
      array[1, 1, 1, 1] matrix[1, 1] value = lbeta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lbeta(array[,,]real,int)=>array[,,]real
    {
      array[1, 1, 1] real arg_1 = {{{(1.95 + 0.0625 * seed)}}};
      int arg_2 = 3;
      array[1, 1, 1] real value = lbeta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lbeta(array[,]real,array[,]real)=>array[,]real
    {
      array[1, 1] real arg_1 = {{(1.95 + 0.0625 * seed)}};
      array[1, 1] real arg_2 = {{(2.9500000000000002 + 0.0625 * seed)}};
      array[1, 1] real value = lbeta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lbeta(array[,]row_vector,real)=>array[,]row_vector
    {
      array[1, 1] row_vector[1] arg_1 = {{[(1.95 + 0.0625 * seed)]}};
      real arg_2 = (2.9500000000000002 + 0.0625 * seed);
      array[1, 1] row_vector[1] value = lbeta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lbeta(array[]real,array[]real)=>array[]real
    {
      array[1] real arg_1 = {(1.95 + 0.0625 * seed)};
      array[1] real arg_2 = {(2.9500000000000002 + 0.0625 * seed)};
      array[1] real value = lbeta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lbeta(array[]real,real)=>array[]real
    {
      array[1] real arg_1 = {(1.95 + 0.0625 * seed)};
      real arg_2 = (2.9500000000000002 + 0.0625 * seed);
      array[1] real value = lbeta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lbeta(int,array[,,,,,]row_vector)=>array[,,,,,]row_vector
    {
      int arg_1 = 2;
      array[1, 1, 1, 1, 1, 1] row_vector[1] arg_2 = {{{{{{[(2.9500000000000002 + 0.0625 * seed)]}}}}}};
      array[1, 1, 1, 1, 1, 1] row_vector[1] value = lbeta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lbeta(int,array[]matrix)=>array[]matrix
    {
      int arg_1 = 2;
      array[1] matrix[1, 1] arg_2 = {[[(2.9500000000000002 + 0.0625 * seed)]]};
      array[1] matrix[1, 1] value = lbeta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lbeta(real,array[]int)=>array[]real
    {
      real arg_1 = (1.95 + 0.0625 * seed);
      array[1] int arg_2 = {3};
      array[1] real value = lbeta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lchoose(array[,,,,,,]int,array[,,,,,,]int)=>array[,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{{4}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] int arg_2 = {{{{{{{2}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] real value = lchoose(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lchoose(array[,,,,,]row_vector,array[,,,,,]row_vector)=>array[,,,,,]row_vector
    {
      array[1, 1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{{[(3.9500000000000002 + 0.0625 * seed)]}}}}}};
      array[1, 1, 1, 1, 1, 1] row_vector[1] arg_2 = {{{{{{[(1.95 + 0.0625 * seed)]}}}}}};
      array[1, 1, 1, 1, 1, 1] row_vector[1] value = lchoose(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lchoose(array[,,,,,]vector,array[,,,,,]vector)=>array[,,,,,]vector
    {
      array[1, 1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{{[(3.9500000000000002 + 0.0625 * seed)]'}}}}}};
      array[1, 1, 1, 1, 1, 1] vector[1] arg_2 = {{{{{{[(1.95 + 0.0625 * seed)]'}}}}}};
      array[1, 1, 1, 1, 1, 1] vector[1] value = lchoose(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lchoose(array[,]int,array[,]int)=>array[,]real
    {
      array[1, 1] int arg_1 = {{4}};
      array[1, 1] int arg_2 = {{2}};
      array[1, 1] real value = lchoose(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lchoose(array[]vector,int)=>array[]vector
    {
      array[1] vector[1] arg_1 = {[(3.9500000000000002 + 0.0625 * seed)]'};
      int arg_2 = 2;
      array[1] vector[1] value = lchoose(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lchoose(int,array[,]int)=>array[,]real
    {
      int arg_1 = 4;
      array[1, 1] int arg_2 = {{2}};
      array[1, 1] real value = lchoose(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lchoose(real,array[,,,,,,]int)=>array[,,,,,,]real
    {
      real arg_1 = (3.9500000000000002 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1, 1] int arg_2 = {{{{{{{2}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] real value = lchoose(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // ldexp(array[]vector,int)=>array[]vector
    {
      array[1] vector[1] arg_1 = {[(0.45000000000000001 + 0.0625 * seed)]'};
      int arg_2 = 2;
      array[1] vector[1] value = ldexp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // ldexp(real,array[,,,,,]int)=>array[,,,,,]real
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1] int arg_2 = {{{{{{2}}}}}};
      array[1, 1, 1, 1, 1, 1] real value = ldexp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // ldexp(real,array[,,,]int)=>array[,,,]real
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1, 1, 1] int arg_2 = {{{{2}}}};
      array[1, 1, 1, 1] real value = ldexp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lmgamma(array[,,,,,,,]int,array[,,,,,]matrix)=>array[,,,,,]matrix
    {
      array[1, 1, 1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{{{2}}}}}}}};
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{{{[[(1.95 + 0.0625 * seed)]]}}}}}};
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] value = lmgamma(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lmgamma(array[,,,,,,]int,array[,,,,]matrix)=>array[,,,,]matrix
    {
      array[1, 1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{{2}}}}}}};
      array[1, 1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{{[[(1.95 + 0.0625 * seed)]]}}}}};
      array[1, 1, 1, 1, 1] matrix[1, 1] value = lmgamma(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lmgamma(int,array[,,,,,,,]real)=>array[,,,,,,,]real
    {
      int arg_1 = 2;
      array[1, 1, 1, 1, 1, 1, 1, 1] real arg_2 = {{{{{{{{(1.95 + 0.0625 * seed)}}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1, 1] real value = lmgamma(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lmgamma(int,array[]real)=>array[]real
    {
      int arg_1 = 2;
      array[1] real arg_2 = {(1.95 + 0.0625 * seed)};
      array[1] real value = lmgamma(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lmultiply(array[,,,]row_vector,array[,,,]row_vector)=>array[,,,]row_vector
    {
      array[1, 1, 1, 1] row_vector[1] arg_1 = {{{{[(0.45000000000000001 + 0.0625 * seed)]}}}};
      array[1, 1, 1, 1] row_vector[1] arg_2 = {{{{[(1.2 + 0.0625 * seed)]}}}};
      array[1, 1, 1, 1] row_vector[1] value = lmultiply(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lmultiply(int,array[]matrix)=>array[]matrix
    {
      int arg_1 = 0;
      array[1] matrix[1, 1] arg_2 = {[[(1.2 + 0.0625 * seed)]]};
      array[1] matrix[1, 1] value = lmultiply(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lmultiply(real,array[,,,,,]vector)=>array[,,,,,]vector
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1] vector[1] arg_2 = {{{{{{[(1.2 + 0.0625 * seed)]'}}}}}};
      array[1, 1, 1, 1, 1, 1] vector[1] value = lmultiply(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lmultiply(real,array[,]row_vector)=>array[,]row_vector
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1] row_vector[1] arg_2 = {{[(1.2 + 0.0625 * seed)]}};
      array[1, 1] row_vector[1] value = lmultiply(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log(vector)=>vector
    {
      vector[1] arg_1 = [(1.3499999999999999 + 0.0625 * seed)]';
      vector[1] value = log(arg_1);
      total += 1.015625 * sum(value);
    }
    // log10(array[,,,]matrix)=>array[,,,]matrix
    {
      array[1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{[[(1.3499999999999999 + 0.0625 * seed)]]}}}};
      array[1, 1, 1, 1] matrix[1, 1] value = log10(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log1m(array[,,,,]vector)=>array[,,,,]vector
    {
      array[1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{[(0.29999999999999999 + 0.0625 * seed)]'}}}}};
      array[1, 1, 1, 1, 1] vector[1] value = log1m(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log1m(array[]real)=>array[]real
    {
      array[1] real arg_1 = {(0.29999999999999999 + 0.0625 * seed)};
      array[1] real value = log1m(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log1m_exp(matrix)=>matrix
    {
      matrix[1, 1] arg_1 = [[(-0.55000000000000004 + 0.0625 * seed)]];
      matrix[1, 1] value = log1m_exp(arg_1);
      total += 1.0625 * sum(value);
    }
    // log1m_inv_logit(array[]matrix)=>array[]matrix
    {
      array[1] matrix[1, 1] arg_1 = {[[(0.45000000000000001 + 0.0625 * seed)]]};
      array[1] matrix[1, 1] value = log1m_inv_logit(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log_diff_exp(array[,,,,]real,array[,,,,]real)=>array[,,,,]real
    {
      array[1, 1, 1, 1, 1] real arg_1 = {{{{{(1.45 + 0.0625 * seed)}}}}};
      array[1, 1, 1, 1, 1] real arg_2 = {{{{{(0.45000000000000001 + 0.0625 * seed)}}}}};
      array[1, 1, 1, 1, 1] real value = log_diff_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_diff_exp(array[,,,]vector,array[,,,]vector)=>array[,,,]vector
    {
      array[1, 1, 1, 1] vector[1] arg_1 = {{{{[(1.45 + 0.0625 * seed)]'}}}};
      array[1, 1, 1, 1] vector[1] arg_2 = {{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}};
      array[1, 1, 1, 1] vector[1] value = log_diff_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_diff_exp(array[,,]real,int)=>array[,,]real
    {
      array[1, 1, 1] real arg_1 = {{{(1.45 + 0.0625 * seed)}}};
      int arg_2 = 0;
      array[1, 1, 1] real value = log_diff_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_diff_exp(int,array[,,,,,,]int)=>array[,,,,,,]real
    {
      int arg_1 = 1;
      array[1, 1, 1, 1, 1, 1, 1] int arg_2 = {{{{{{{0}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] real value = log_diff_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_diff_exp(int,array[,,]vector)=>array[,,]vector
    {
      int arg_1 = 1;
      array[1, 1, 1] vector[1] arg_2 = {{{[(0.45000000000000001 + 0.0625 * seed)]'}}};
      array[1, 1, 1] vector[1] value = log_diff_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_diff_exp(real,array[,,,,,,]vector)=>array[,,,,,,]vector
    {
      real arg_1 = (1.45 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1, 1] vector[1] arg_2 = {{{{{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] vector[1] value = log_diff_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_diff_exp(real,array[]vector)=>array[]vector
    {
      real arg_1 = (1.45 + 0.0625 * seed);
      array[1] vector[1] arg_2 = {[(0.45000000000000001 + 0.0625 * seed)]'};
      array[1] vector[1] value = log_diff_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_diff_exp(real,int)=>real
    {
      real arg_1 = (1.45 + 0.0625 * seed);
      int arg_2 = 0;
      real value = log_diff_exp(arg_1, arg_2);
      total += 1.171875 * value;
    }
    // log_diff_exp(vector,int)=>vector
    {
      vector[1] arg_1 = [(1.45 + 0.0625 * seed)]';
      int arg_2 = 0;
      vector[1] value = log_diff_exp(arg_1, arg_2);
      total += 1.25 * sum(value);
    }
    // log_falling_factorial(array[,,,,]real,int)=>array[,,,,]real
    {
      array[1, 1, 1, 1, 1] real arg_1 = {{{{{(3.4500000000000002 + 0.0625 * seed)}}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1, 1] real value = log_falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_falling_factorial(array[,,,,]row_vector,array[,,,,]row_vector)=>array[,,,,]row_vector
    {
      array[1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{[(3.4500000000000002 + 0.0625 * seed)]}}}}};
      array[1, 1, 1, 1, 1] row_vector[1] arg_2 = {{{{{[(1.1499999999999999 + 0.0625 * seed)]}}}}};
      array[1, 1, 1, 1, 1] row_vector[1] value = log_falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_falling_factorial(array[,,,]row_vector,array[,,,]row_vector)=>array[,,,]row_vector
    {
      array[1, 1, 1, 1] row_vector[1] arg_1 = {{{{[(3.4500000000000002 + 0.0625 * seed)]}}}};
      array[1, 1, 1, 1] row_vector[1] arg_2 = {{{{[(1.1499999999999999 + 0.0625 * seed)]}}}};
      array[1, 1, 1, 1] row_vector[1] value = log_falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_falling_factorial(array[,]real,array[,]real)=>array[,]real
    {
      array[1, 1] real arg_1 = {{(3.4500000000000002 + 0.0625 * seed)}};
      array[1, 1] real arg_2 = {{(1.1499999999999999 + 0.0625 * seed)}};
      array[1, 1] real value = log_falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_falling_factorial(array[]matrix,int)=>array[]matrix
    {
      array[1] matrix[1, 1] arg_1 = {[[(3.4500000000000002 + 0.0625 * seed)]]};
      int arg_2 = 1;
      array[1] matrix[1, 1] value = log_falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_falling_factorial(int,vector)=>vector
    {
      int arg_1 = 3;
      vector[1] arg_2 = [(1.1499999999999999 + 0.0625 * seed)]';
      vector[1] value = log_falling_factorial(arg_1, arg_2);
      total += 1.203125 * sum(value);
    }
    // log_falling_factorial(real,array[,,,,]row_vector)=>array[,,,,]row_vector
    {
      real arg_1 = (3.4500000000000002 + 0.0625 * seed);
      array[1, 1, 1, 1, 1] row_vector[1] arg_2 = {{{{{[(1.1499999999999999 + 0.0625 * seed)]}}}}};
      array[1, 1, 1, 1, 1] row_vector[1] value = log_falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_falling_factorial(real,array[]int)=>array[]real
    {
      real arg_1 = (3.4500000000000002 + 0.0625 * seed);
      array[1] int arg_2 = {1};
      array[1] real value = log_falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_inv_logit(array[,,,]row_vector)=>array[,,,]row_vector
    {
      array[1, 1, 1, 1] row_vector[1] arg_1 = {{{{[(0.45000000000000001 + 0.0625 * seed)]}}}};
      array[1, 1, 1, 1] row_vector[1] value = log_inv_logit(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log_inv_logit(array[]real)=>array[]real
    {
      array[1] real arg_1 = {(0.45000000000000001 + 0.0625 * seed)};
      array[1] real value = log_inv_logit(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log_inv_logit_diff(array[,]row_vector,int)=>array[,]row_vector
    {
      array[1, 1] row_vector[1] arg_1 = {{[(0.94999999999999996 + 0.0625 * seed)]}};
      int arg_2 = 0;
      array[1, 1] row_vector[1] value = log_inv_logit_diff(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_inv_logit_diff(real,real)=>real
    {
      real arg_1 = (0.94999999999999996 + 0.0625 * seed);
      real arg_2 = (-0.55000000000000004 + 0.0625 * seed);
      real value = log_inv_logit_diff(arg_1, arg_2);
      total += 1.25 * value;
    }
    // log_inv_logit_diff(row_vector,row_vector)=>row_vector
    {
      row_vector[1] arg_1 = [(0.94999999999999996 + 0.0625 * seed)];
      row_vector[1] arg_2 = [(-0.55000000000000004 + 0.0625 * seed)];
      row_vector[1] value = log_inv_logit_diff(arg_1, arg_2);
      total += 1 * sum(value);
    }
    // log_modified_bessel_first_kind(array[,,,,,]vector,int)=>array[,,,,,]vector
    {
      array[1, 1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1, 1, 1] vector[1] value = log_modified_bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_modified_bessel_first_kind(array[,,,,]matrix,array[,,,,]matrix)=>array[,,,,]matrix
    {
      array[1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}}};
      array[1, 1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{{[[(1.2 + 0.0625 * seed)]]}}}}};
      array[1, 1, 1, 1, 1] matrix[1, 1] value = log_modified_bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_modified_bessel_first_kind(array[,,,,]row_vector,int)=>array[,,,,]row_vector
    {
      array[1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{[(0.45000000000000001 + 0.0625 * seed)]}}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1, 1] row_vector[1] value = log_modified_bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_modified_bessel_first_kind(int,array[,,,,,,]row_vector)=>array[,,,,,,]row_vector
    {
      int arg_1 = 0;
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] arg_2 = {{{{{{{[(1.2 + 0.0625 * seed)]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] value = log_modified_bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_modified_bessel_first_kind(int,array[,]real)=>array[,]real
    {
      int arg_1 = 0;
      array[1, 1] real arg_2 = {{(1.2 + 0.0625 * seed)}};
      array[1, 1] real value = log_modified_bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_modified_bessel_first_kind(real,array[,,]vector)=>array[,,]vector
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1, 1] vector[1] arg_2 = {{{[(1.2 + 0.0625 * seed)]'}}};
      array[1, 1, 1] vector[1] value = log_modified_bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_rising_factorial(array[,,,]int,array[,,,]int)=>array[,,,]real
    {
      array[1, 1, 1, 1] int arg_1 = {{{{1}}}};
      array[1, 1, 1, 1] int arg_2 = {{{{1}}}};
      array[1, 1, 1, 1] real value = log_rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_rising_factorial(array[]real,real)=>array[]real
    {
      array[1] real arg_1 = {(1.45 + 0.0625 * seed)};
      real arg_2 = (1.1499999999999999 + 0.0625 * seed);
      array[1] real value = log_rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_rising_factorial(int,array[,,,,,,]matrix)=>array[,,,,,,]matrix
    {
      int arg_1 = 1;
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{{{{[[(1.1499999999999999 + 0.0625 * seed)]]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] value = log_rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_rising_factorial(int,array[,,,,,,]real)=>array[,,,,,,]real
    {
      int arg_1 = 1;
      array[1, 1, 1, 1, 1, 1, 1] real arg_2 = {{{{{{{(1.1499999999999999 + 0.0625 * seed)}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] real value = log_rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_rising_factorial(real,array[]row_vector)=>array[]row_vector
    {
      real arg_1 = (1.45 + 0.0625 * seed);
      array[1] row_vector[1] arg_2 = {[(1.1499999999999999 + 0.0625 * seed)]};
      array[1] row_vector[1] value = log_rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_rising_factorial(row_vector,real)=>row_vector
    {
      row_vector[1] arg_1 = [(1.45 + 0.0625 * seed)];
      real arg_2 = (1.1499999999999999 + 0.0625 * seed);
      row_vector[1] value = log_rising_factorial(arg_1, arg_2);
      total += 1.15625 * sum(value);
    }
    // log_softmax(row_vector)=>row_vector
    {
      row_vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)];
      row_vector[1] value = log_softmax(arg_1);
      total += 1.125 * sum(value);
    }
    // log_sum_exp(array[,,,,,,]vector,real)=>array[,,,,,,]vector
    {
      array[1, 1, 1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}}}}};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1, 1] vector[1] value = log_sum_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_sum_exp(array[,,,,,]real,array[,,,,,]real)=>array[,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{(0.45000000000000001 + 0.0625 * seed)}}}}}};
      array[1, 1, 1, 1, 1, 1] real arg_2 = {{{{{{(1.2 + 0.0625 * seed)}}}}}};
      array[1, 1, 1, 1, 1, 1] real value = log_sum_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_sum_exp(array[,,,,]matrix,real)=>array[,,,,]matrix
    {
      array[1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}}};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1, 1, 1, 1, 1] matrix[1, 1] value = log_sum_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_sum_exp(int,array[,,,,,,,]real)=>array[,,,,,,,]real
    {
      int arg_1 = 0;
      array[1, 1, 1, 1, 1, 1, 1, 1] real arg_2 = {{{{{{{{(1.2 + 0.0625 * seed)}}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1, 1] real value = log_sum_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_sum_exp(int,array[,,,,,]int)=>array[,,,,,]real
    {
      int arg_1 = 0;
      array[1, 1, 1, 1, 1, 1] int arg_2 = {{{{{{1}}}}}};
      array[1, 1, 1, 1, 1, 1] real value = log_sum_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_sum_exp(int,array[,,,,]matrix)=>array[,,,,]matrix
    {
      int arg_1 = 0;
      array[1, 1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{{[[(1.2 + 0.0625 * seed)]]}}}}};
      array[1, 1, 1, 1, 1] matrix[1, 1] value = log_sum_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_sum_exp(int,array[]int)=>array[]real
    {
      int arg_1 = 0;
      array[1] int arg_2 = {1};
      array[1] real value = log_sum_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_sum_exp(real,array[,,,,]real)=>array[,,,,]real
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1, 1, 1, 1] real arg_2 = {{{{{(1.2 + 0.0625 * seed)}}}}};
      array[1, 1, 1, 1, 1] real value = log_sum_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_sum_exp(real,array[,,,,]row_vector)=>array[,,,,]row_vector
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1, 1, 1, 1] row_vector[1] arg_2 = {{{{{[(1.2 + 0.0625 * seed)]}}}}};
      array[1, 1, 1, 1, 1] row_vector[1] value = log_sum_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_sum_exp(real,real)=>real
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      real arg_2 = (1.2 + 0.0625 * seed);
      real value = log_sum_exp(arg_1, arg_2);
      total += 1.109375 * value;
    }
    // logit(vector)=>vector
    {
      vector[1] arg_1 = [(0.29999999999999999 + 0.0625 * seed)]';
      vector[1] value = logit(arg_1);
      total += 1.03125 * sum(value);
    }
    // mdivide_left_tri_low(matrix,matrix)=>matrix
    {
      matrix[1, 1] arg_1 = [[(0.45000000000000001 + 0.0625 * seed)]];
      matrix[1, 1] arg_2 = [[(1.2 + 0.0625 * seed)]];
      matrix[1, 1] value = mdivide_left_tri_low(arg_1, arg_2);
      total += 1.15625 * sum(value);
    }
    // mean(vector)=>real
    {
      vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)]';
      real value = mean(arg_1);
      total += 1.03125 * value;
    }
    // modified_bessel_first_kind(array[,,,,,,]int,array[,,,,,]vector)=>array[,,,,,]vector
    {
      array[1, 1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{{2}}}}}}};
      array[1, 1, 1, 1, 1, 1] vector[1] arg_2 = {{{{{{[(1.3499999999999999 + 0.0625 * seed)]'}}}}}};
      array[1, 1, 1, 1, 1, 1] vector[1] value = modified_bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // modified_bessel_first_kind(int,array[,]row_vector)=>array[,]row_vector
    {
      int arg_1 = 2;
      array[1, 1] row_vector[1] arg_2 = {{[(1.3499999999999999 + 0.0625 * seed)]}};
      array[1, 1] row_vector[1] value = modified_bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // modified_bessel_first_kind(int,real)=>real
    {
      int arg_1 = 2;
      real arg_2 = (1.3499999999999999 + 0.0625 * seed);
      real value = modified_bessel_first_kind(arg_1, arg_2);
      total += 1.109375 * value;
    }
    // modified_bessel_second_kind(array[,,,,,]int,real)=>array[,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{2}}}}}};
      real arg_2 = (1.3499999999999999 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1] real value = modified_bessel_second_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // modified_bessel_second_kind(int,array[]matrix)=>array[]matrix
    {
      int arg_1 = 2;
      array[1] matrix[1, 1] arg_2 = {[[(1.3499999999999999 + 0.0625 * seed)]]};
      array[1] matrix[1, 1] value = modified_bessel_second_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // owens_t(array[,,,,,,]real,real)=>array[,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{{(0.45000000000000001 + 0.0625 * seed)}}}}}}};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1, 1] real value = owens_t(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // owens_t(array[,,,,]matrix,real)=>array[,,,,]matrix
    {
      array[1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}}};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1, 1, 1, 1, 1] matrix[1, 1] value = owens_t(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // owens_t(array[,,,,]vector,array[,,,,]vector)=>array[,,,,]vector
    {
      array[1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}}};
      array[1, 1, 1, 1, 1] vector[1] arg_2 = {{{{{[(1.2 + 0.0625 * seed)]'}}}}};
      array[1, 1, 1, 1, 1] vector[1] value = owens_t(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // owens_t(array[,,,]real,array[,,,]real)=>array[,,,]real
    {
      array[1, 1, 1, 1] real arg_1 = {{{{(0.45000000000000001 + 0.0625 * seed)}}}};
      array[1, 1, 1, 1] real arg_2 = {{{{(1.2 + 0.0625 * seed)}}}};
      array[1, 1, 1, 1] real value = owens_t(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // owens_t(matrix,matrix)=>matrix
    {
      matrix[1, 1] arg_1 = [[(0.45000000000000001 + 0.0625 * seed)]];
      matrix[1, 1] arg_2 = [[(1.2 + 0.0625 * seed)]];
      matrix[1, 1] value = owens_t(arg_1, arg_2);
      total += 1 * sum(value);
    }
    // owens_t(real,array[,,,,,]matrix)=>array[,,,,,]matrix
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{{{[[(1.2 + 0.0625 * seed)]]}}}}}};
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] value = owens_t(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // owens_t(real,array[,,,]row_vector)=>array[,,,]row_vector
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1, 1, 1] row_vector[1] arg_2 = {{{{[(1.2 + 0.0625 * seed)]}}}};
      array[1, 1, 1, 1] row_vector[1] value = owens_t(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // owens_t(real,array[,,]matrix)=>array[,,]matrix
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1, 1] matrix[1, 1] arg_2 = {{{[[(1.2 + 0.0625 * seed)]]}}};
      array[1, 1, 1] matrix[1, 1] value = owens_t(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // owens_t(real,array[]real)=>array[]real
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1] real arg_2 = {(1.2 + 0.0625 * seed)};
      array[1] real value = owens_t(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // owens_t(real,array[]vector)=>array[]vector
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1] vector[1] arg_2 = {[(1.2 + 0.0625 * seed)]'};
      array[1] vector[1] value = owens_t(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // owens_t(row_vector,row_vector)=>row_vector
    {
      row_vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)];
      row_vector[1] arg_2 = [(1.2 + 0.0625 * seed)];
      row_vector[1] value = owens_t(arg_1, arg_2);
      total += 1.21875 * sum(value);
    }
    // pow(array[]real,real)=>array[]real
    {
      array[1] real arg_1 = {(0.45000000000000001 + 0.0625 * seed)};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1] real value = pow(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // pow(real,array[,,,,,,]real)=>array[,,,,,,]real
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1, 1] real arg_2 = {{{{{{{(1.2 + 0.0625 * seed)}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] real value = pow(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // pow(real,array[,]real)=>array[,]real
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1] real arg_2 = {{(1.2 + 0.0625 * seed)}};
      array[1, 1] real value = pow(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // pow(real,array[,]vector)=>array[,]vector
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1] vector[1] arg_2 = {{[(1.2 + 0.0625 * seed)]'}};
      array[1, 1] vector[1] value = pow(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // rep_array(array[,]row_vector,int,int,int)=>array[,,,,]row_vector
    {
      array[1, 1] row_vector[1] arg_1 = {{[(0.45000000000000001 + 0.0625 * seed)]}};
      array[1, 1, 1, 1, 1] row_vector[1] value = rep_array(arg_1, 1, 1, 1);
      if (seed > 1e100)
        print(value);
    }
    // rep_array(array[]int,int)=>array[,]int
    {
      array[1] int arg_1 = {1};
      array[1, 1] int value = rep_array(arg_1, 1);
      if (seed > 1e100)
        print(value);
    }
    // rep_matrix(vector,int)=>matrix
    {
      vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)]';
      matrix[1, 1] value = rep_matrix(arg_1, 1);
      total += 1.015625 * sum(value);
    }
    // rising_factorial(array[,,]row_vector,array[,,,]int)=>array[,,]row_vector
    {
      array[1, 1, 1] row_vector[1] arg_1 = {{{[(1.45 + 0.0625 * seed)]}}};
      array[1, 1, 1, 1] int arg_2 = {{{{2}}}};
      array[1, 1, 1] row_vector[1] value = rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // rising_factorial(array[,]row_vector,int)=>array[,]row_vector
    {
      array[1, 1] row_vector[1] arg_1 = {{[(1.45 + 0.0625 * seed)]}};
      int arg_2 = 2;
      array[1, 1] row_vector[1] value = rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // rising_factorial(real,int)=>real
    {
      real arg_1 = (1.45 + 0.0625 * seed);
      int arg_2 = 2;
      real value = rising_factorial(arg_1, arg_2);
      total += 1.03125 * value;
    }
    // sd(vector)=>real
    {
      vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)]';
      real value = sd(arg_1);
      total += 1 * value;
    }
    // segment(array[]int,int,int)=>array[]int
    {
      array[1] int arg_1 = {1};
      array[1] int value = segment(arg_1, 1, 1);
      if (seed > 1e100)
        print(value);
    }
    // sin(array[,,,]vector)=>array[,,,]vector
    {
      array[1, 1, 1, 1] vector[1] arg_1 = {{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}};
      array[1, 1, 1, 1] vector[1] value = sin(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // size(array[,,,,,,]int)=>int
    {
      array[1, 1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{{2}}}}}}};
      int value = size(arg_1);
      total += 1.09375 * value;
    }
    // size(array[,,,,,]row_vector)=>int
    {
      array[1, 1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{{[(0.45000000000000001 + 0.0625 * seed)]}}}}}};
      int value = size(arg_1);
      total += 1.171875 * value;
    }
    // size(array[]int)=>int
    {
      array[1] int arg_1 = {2};
      int value = size(arg_1);
      total += 1.1875 * value;
    }
    // sqrt(array[,,,,,]matrix)=>array[,,,,,]matrix
    {
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{{[[(1.3499999999999999 + 0.0625 * seed)]]}}}}}};
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] value = sqrt(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // square(array[,,,,]matrix)=>array[,,,,]matrix
    {
      array[1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}}};
      array[1, 1, 1, 1, 1] matrix[1, 1] value = square(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // square(array[,,,,]row_vector)=>array[,,,,]row_vector
    {
      array[1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{[(0.45000000000000001 + 0.0625 * seed)]}}}}};
      array[1, 1, 1, 1, 1] row_vector[1] value = square(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // square(array[,]matrix)=>array[,]matrix
    {
      array[1, 1] matrix[1, 1] arg_1 = {{[[(0.45000000000000001 + 0.0625 * seed)]]}};
      array[1, 1] matrix[1, 1] value = square(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // std_normal_log_qf(array[,,,,,,]real)=>array[,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{{(-0.55000000000000004 + 0.0625 * seed)}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] real value = std_normal_log_qf(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // std_normal_qf(array[,,,,,,]row_vector)=>array[,,,,,,]row_vector
    {
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{{{[(0.45000000000000001 + 0.0625 * seed)]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] value = std_normal_qf(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // std_normal_qf(array[,,,,,]int)=>array[,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{0}}}}}};
      array[1, 1, 1, 1, 1, 1] real value = std_normal_qf(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // std_normal_qf(array[,,]int)=>array[,,]real
    {
      array[1, 1, 1] int arg_1 = {{{0}}};
      array[1, 1, 1] real value = std_normal_qf(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // tan(array[,,,,,,]matrix)=>array[,,,,,,]matrix
    {
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] value = tan(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // tanh(array[,,,,,]matrix)=>array[,,,,,]matrix
    {
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}}}};
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] value = tanh(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // tanh(array[,]row_vector)=>array[,]row_vector
    {
      array[1, 1] row_vector[1] arg_1 = {{[(0.45000000000000001 + 0.0625 * seed)]}};
      array[1, 1] row_vector[1] value = tanh(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // tgamma(array[,,,,,,]row_vector)=>array[,,,,,,]row_vector
    {
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{{{[(0.45000000000000001 + 0.0625 * seed)]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] value = tgamma(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // to_matrix(array[]row_vector)=>matrix
    {
      array[1] row_vector[1] arg_1 = {[(0.45000000000000001 + 0.0625 * seed)]};
      matrix[1, 1] value = to_matrix(arg_1);
      total += 1.25 * sum(value);
    }
    // trigamma(array[,,,,]vector)=>array[,,,,]vector
    {
      array[1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{[(1.3499999999999999 + 0.0625 * seed)]'}}}}};
      array[1, 1, 1, 1, 1] vector[1] value = trigamma(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // trunc(array[,,,,,]int)=>array[,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{1}}}}}};
      array[1, 1, 1, 1, 1, 1] real value = trunc(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // trunc(array[,]real)=>array[,]real
    {
      array[1, 1] real arg_1 = {{(0.45000000000000001 + 0.0625 * seed)}};
      array[1, 1] real value = trunc(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // variance(vector)=>real
    {
      vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)]';
      real value = variance(arg_1);
      total += 1.109375 * value;
    }
    return total;
  }
}
data {
  real context_seed;
}
transformed data {
  real transformed_data_result = builtin_signatures_25(context_seed);
}
parameters {
  real probe;
}
model {
  probe ~ std_normal();
  target += builtin_signatures_25(probe);
  if (probe > -1e100)
    target += builtin_signatures_25(probe);
}
generated quantities {
  real generated_quantities_result = builtin_signatures_25(probe);
}
