// STANLI-LIT: PASS
// STANLI-LIT-EXPECT: OK
// STANLI-LIT-DATA: {"context_seed": 0.0}
// STANLI-LIT-TIMEOUT: 180
// Generated by tools/generate_builtin_signature_models.py from the unified FunctionSpec registry
// and `stanc --dump-stan-math-signatures`. Do not edit by hand.
// Partition 4 of 30; 237 overloads.
functions {
  real builtin_signatures_04(real seed) {
    real total = 0;
    // Phi(array[,,,,,]vector)=>array[,,,,,]vector
    {
      array[1, 1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}}}};
      array[1, 1, 1, 1, 1, 1] vector[1] value = Phi(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // Phi(array[]matrix)=>array[]matrix
    {
      array[1] matrix[1, 1] arg_1 = {[[(0.45000000000000001 + 0.0625 * seed)]]};
      array[1] matrix[1, 1] value = Phi(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // abs(array[]vector)=>array[]vector
    {
      array[1] vector[1] arg_1 = {[(0.45000000000000001 + 0.0625 * seed)]'};
      array[1] vector[1] value = abs(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // acos(array[,,]int)=>array[,,]real
    {
      array[1, 1, 1] int arg_1 = {{{0}}};
      array[1, 1, 1] real value = acos(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // append_array(array[,,]matrix,array[,,]matrix)=>array[,,]matrix
    {
      array[1, 1, 1] matrix[1, 1] arg_1 = {{{[[(0.45000000000000001 + 0.0625 * seed)]]}}};
      array[1, 1, 1] matrix[1, 1] arg_2 = {{{[[(1.2 + 0.0625 * seed)]]}}};
      array[2, 1, 1] matrix[1, 1] value = append_array(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // asin(array[,,,,]matrix)=>array[,,,,]matrix
    {
      array[1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{[[(0.29999999999999999 + 0.0625 * seed)]]}}}}};
      array[1, 1, 1, 1, 1] matrix[1, 1] value = asin(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // asin(array[,,]real)=>array[,,]real
    {
      array[1, 1, 1] real arg_1 = {{{(0.29999999999999999 + 0.0625 * seed)}}};
      array[1, 1, 1] real value = asin(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // asin(array[,]vector)=>array[,]vector
    {
      array[1, 1] vector[1] arg_1 = {{[(0.29999999999999999 + 0.0625 * seed)]'}};
      array[1, 1] vector[1] value = asin(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // asin(real)=>real
    {
      real arg_1 = (0.29999999999999999 + 0.0625 * seed);
      real value = asin(arg_1);
      total += 1.25 * value;
    }
    // asinh(array[,,]real)=>array[,,]real
    {
      array[1, 1, 1] real arg_1 = {{{(0.45000000000000001 + 0.0625 * seed)}}};
      array[1, 1, 1] real value = asinh(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // asinh(int)=>real
    {
      int arg_1 = 1;
      real value = asinh(arg_1);
      total += 1.15625 * value;
    }
    // atan(array[,,]matrix)=>array[,,]matrix
    {
      array[1, 1, 1] matrix[1, 1] arg_1 = {{{[[(0.45000000000000001 + 0.0625 * seed)]]}}};
      array[1, 1, 1] matrix[1, 1] value = atan(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // atan2(array[,,,,,]row_vector,int)=>array[,,,,,]row_vector
    {
      array[1, 1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{{[(0.45000000000000001 + 0.0625 * seed)]}}}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1, 1, 1] row_vector[1] value = atan2(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // atan2(array[,,,]matrix,real)=>array[,,,]matrix
    {
      array[1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1, 1, 1, 1] matrix[1, 1] value = atan2(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // atan2(array[,]row_vector,int)=>array[,]row_vector
    {
      array[1, 1] row_vector[1] arg_1 = {{[(0.45000000000000001 + 0.0625 * seed)]}};
      int arg_2 = 1;
      array[1, 1] row_vector[1] value = atan2(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // atan2(int,array[,,,,,,]real)=>array[,,,,,,]real
    {
      int arg_1 = 0;
      array[1, 1, 1, 1, 1, 1, 1] real arg_2 = {{{{{{{(1.2 + 0.0625 * seed)}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] real value = atan2(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // atan2(int,array[,,]int)=>array[,,]real
    {
      int arg_1 = 0;
      array[1, 1, 1] int arg_2 = {{{1}}};
      array[1, 1, 1] real value = atan2(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // atan2(real,array[,,,,,]int)=>array[,,,,,]real
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1] int arg_2 = {{{{{{1}}}}}};
      array[1, 1, 1, 1, 1, 1] real value = atan2(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // atan2(real,real)=>real
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      real arg_2 = (1.2 + 0.0625 * seed);
      real value = atan2(arg_1, arg_2);
      total += 1.109375 * value;
    }
    // atanh(row_vector)=>row_vector
    {
      row_vector[1] arg_1 = [(0.29999999999999999 + 0.0625 * seed)];
      row_vector[1] value = atanh(arg_1);
      total += 1.203125 * sum(value);
    }
    // bessel_first_kind(array[,,,]int,array[,]matrix)=>array[,]matrix
    {
      array[1, 1, 1, 1] int arg_1 = {{{{2}}}};
      array[1, 1] matrix[1, 1] arg_2 = {{[[(1.3499999999999999 + 0.0625 * seed)]]}};
      array[1, 1] matrix[1, 1] value = bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // bessel_second_kind(int,array[,,,,]matrix)=>array[,,,,]matrix
    {
      int arg_1 = 2;
      array[1, 1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{{[[(1.3499999999999999 + 0.0625 * seed)]]}}}}};
      array[1, 1, 1, 1, 1] matrix[1, 1] value = bessel_second_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // bessel_second_kind(int,array[,,,,]real)=>array[,,,,]real
    {
      int arg_1 = 2;
      array[1, 1, 1, 1, 1] real arg_2 = {{{{{(1.3499999999999999 + 0.0625 * seed)}}}}};
      array[1, 1, 1, 1, 1] real value = bessel_second_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // beta(array[,,]real,int)=>array[,,]real
    {
      array[1, 1, 1] real arg_1 = {{{(1.95 + 0.0625 * seed)}}};
      int arg_2 = 3;
      array[1, 1, 1] real value = beta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // beta(array[]real,int)=>array[]real
    {
      array[1] real arg_1 = {(1.95 + 0.0625 * seed)};
      int arg_2 = 3;
      array[1] real value = beta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // beta(real,array[,,,,,]int)=>array[,,,,,]real
    {
      real arg_1 = (1.95 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1] int arg_2 = {{{{{{3}}}}}};
      array[1, 1, 1, 1, 1, 1] real value = beta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // beta(real,array[,,,,,]vector)=>array[,,,,,]vector
    {
      real arg_1 = (1.95 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1] vector[1] arg_2 = {{{{{{[(2.9500000000000002 + 0.0625 * seed)]'}}}}}};
      array[1, 1, 1, 1, 1, 1] vector[1] value = beta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // beta(real,array[]row_vector)=>array[]row_vector
    {
      real arg_1 = (1.95 + 0.0625 * seed);
      array[1] row_vector[1] arg_2 = {[(2.9500000000000002 + 0.0625 * seed)]};
      array[1] row_vector[1] value = beta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // binary_log_loss(int,array[,]vector)=>array[,]vector
    {
      int arg_1 = 1;
      array[1, 1] vector[1] arg_2 = {{[(0.35000000000000003 + 0.0625 * seed)]'}};
      array[1, 1] vector[1] value = binary_log_loss(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // cbrt(array[,,,,]row_vector)=>array[,,,,]row_vector
    {
      array[1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{[(0.45000000000000001 + 0.0625 * seed)]}}}}};
      array[1, 1, 1, 1, 1] row_vector[1] value = cbrt(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // ceil(array[,,,,,]row_vector)=>array[,,,,,]row_vector
    {
      array[1, 1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{{[(0.45000000000000001 + 0.0625 * seed)]}}}}}};
      array[1, 1, 1, 1, 1, 1] row_vector[1] value = ceil(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // cols(row_vector)=>int
    {
      row_vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)];
      int value = cols(arg_1);
      total += 1.046875 * value;
    }
    // cos(array[,,,,]matrix)=>array[,,,,]matrix
    {
      array[1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}}};
      array[1, 1, 1, 1, 1] matrix[1, 1] value = cos(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // digamma(array[]matrix)=>array[]matrix
    {
      array[1] matrix[1, 1] arg_1 = {[[(1.3499999999999999 + 0.0625 * seed)]]};
      array[1] matrix[1, 1] value = digamma(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // dot_product(row_vector,vector)=>real
    {
      row_vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)];
      vector[1] arg_2 = [(1.2 + 0.0625 * seed)]';
      real value = dot_product(arg_1, arg_2);
      total += 1 * value;
    }
    // erf(array[,,,,,]vector)=>array[,,,,,]vector
    {
      array[1, 1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}}}};
      array[1, 1, 1, 1, 1, 1] vector[1] value = erf(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // erf(array[,,,,]int)=>array[,,,,]real
    {
      array[1, 1, 1, 1, 1] int arg_1 = {{{{{1}}}}};
      array[1, 1, 1, 1, 1] real value = erf(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // erf(array[,,,,]vector)=>array[,,,,]vector
    {
      array[1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}}};
      array[1, 1, 1, 1, 1] vector[1] value = erf(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // erf(array[,,]real)=>array[,,]real
    {
      array[1, 1, 1] real arg_1 = {{{(0.45000000000000001 + 0.0625 * seed)}}};
      array[1, 1, 1] real value = erf(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // exp(array[,,,,,,]vector)=>array[,,,,,,]vector
    {
      array[1, 1, 1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] vector[1] value = exp(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // exp(array[,,,]row_vector)=>array[,,,]row_vector
    {
      array[1, 1, 1, 1] row_vector[1] arg_1 = {{{{[(0.45000000000000001 + 0.0625 * seed)]}}}};
      array[1, 1, 1, 1] row_vector[1] value = exp(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // exp2(array[,]matrix)=>array[,]matrix
    {
      array[1, 1] matrix[1, 1] arg_1 = {{[[(0.45000000000000001 + 0.0625 * seed)]]}};
      array[1, 1] matrix[1, 1] value = exp2(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // exp2(array[,]vector)=>array[,]vector
    {
      array[1, 1] vector[1] arg_1 = {{[(0.45000000000000001 + 0.0625 * seed)]'}};
      array[1, 1] vector[1] value = exp2(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // exp2(matrix)=>matrix
    {
      matrix[1, 1] arg_1 = [[(0.45000000000000001 + 0.0625 * seed)]];
      matrix[1, 1] value = exp2(arg_1);
      total += 1.046875 * sum(value);
    }
    // falling_factorial(array[,,,]matrix,int)=>array[,,,]matrix
    {
      array[1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{[[(3.4500000000000002 + 0.0625 * seed)]]}}}};
      int arg_2 = 2;
      array[1, 1, 1, 1] matrix[1, 1] value = falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // falling_factorial(array[,,,]vector,array[,,,,]int)=>array[,,,]vector
    {
      array[1, 1, 1, 1] vector[1] arg_1 = {{{{[(3.4500000000000002 + 0.0625 * seed)]'}}}};
      array[1, 1, 1, 1, 1] int arg_2 = {{{{{2}}}}};
      array[1, 1, 1, 1] vector[1] value = falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // falling_factorial(array[,]vector,int)=>array[,]vector
    {
      array[1, 1] vector[1] arg_1 = {{[(3.4500000000000002 + 0.0625 * seed)]'}};
      int arg_2 = 2;
      array[1, 1] vector[1] value = falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // falling_factorial(real,array[,,,,,,]int)=>array[,,,,,,]real
    {
      real arg_1 = (3.4500000000000002 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1, 1] int arg_2 = {{{{{{{2}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] real value = falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // falling_factorial(vector,int)=>vector
    {
      vector[1] arg_1 = [(3.4500000000000002 + 0.0625 * seed)]';
      int arg_2 = 2;
      vector[1] value = falling_factorial(arg_1, arg_2);
      total += 1.140625 * sum(value);
    }
    // fdim(array[,,,,]int,array[,,,,]int)=>array[,,,,]real
    {
      array[1, 1, 1, 1, 1] int arg_1 = {{{{{1}}}}};
      array[1, 1, 1, 1, 1] int arg_2 = {{{{{1}}}}};
      array[1, 1, 1, 1, 1] real value = fdim(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fdim(array[,,,,]row_vector,real)=>array[,,,,]row_vector
    {
      array[1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{[(0.94999999999999996 + 0.0625 * seed)]}}}}};
      real arg_2 = (0.94999999999999996 + 0.0625 * seed);
      array[1, 1, 1, 1, 1] row_vector[1] value = fdim(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fdim(array[,,]vector,real)=>array[,,]vector
    {
      array[1, 1, 1] vector[1] arg_1 = {{{[(0.94999999999999996 + 0.0625 * seed)]'}}};
      real arg_2 = (0.94999999999999996 + 0.0625 * seed);
      array[1, 1, 1] vector[1] value = fdim(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fdim(array[,]real,int)=>array[,]real
    {
      array[1, 1] real arg_1 = {{(0.94999999999999996 + 0.0625 * seed)}};
      int arg_2 = 1;
      array[1, 1] real value = fdim(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fdim(matrix,int)=>matrix
    {
      matrix[1, 1] arg_1 = [[(0.94999999999999996 + 0.0625 * seed)]];
      int arg_2 = 1;
      matrix[1, 1] value = fdim(arg_1, arg_2);
      total += 1.25 * sum(value);
    }
    // fdim(real,array[,,,]real)=>array[,,,]real
    {
      real arg_1 = (0.94999999999999996 + 0.0625 * seed);
      array[1, 1, 1, 1] real arg_2 = {{{{(0.94999999999999996 + 0.0625 * seed)}}}};
      array[1, 1, 1, 1] real value = fdim(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // floor(array[,]row_vector)=>array[,]row_vector
    {
      array[1, 1] row_vector[1] arg_1 = {{[(0.45000000000000001 + 0.0625 * seed)]}};
      array[1, 1] row_vector[1] value = floor(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // fmax(int,array[]row_vector)=>array[]row_vector
    {
      int arg_1 = 1;
      array[1] row_vector[1] arg_2 = {[(0.94999999999999996 + 0.0625 * seed)]};
      array[1] row_vector[1] value = fmax(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmax(real,array[,,]row_vector)=>array[,,]row_vector
    {
      real arg_1 = (0.94999999999999996 + 0.0625 * seed);
      array[1, 1, 1] row_vector[1] arg_2 = {{{[(0.94999999999999996 + 0.0625 * seed)]}}};
      array[1, 1, 1] row_vector[1] value = fmax(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmin(array[,,,,]vector,int)=>array[,,,,]vector
    {
      array[1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{[(0.94999999999999996 + 0.0625 * seed)]'}}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1, 1] vector[1] value = fmin(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmin(int,array[,,,,,,,]real)=>array[,,,,,,,]real
    {
      int arg_1 = 1;
      array[1, 1, 1, 1, 1, 1, 1, 1] real arg_2 = {{{{{{{{(0.94999999999999996 + 0.0625 * seed)}}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1, 1] real value = fmin(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmod(array[,,,,,]int,array[,,,,,]int)=>array[,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{2}}}}}};
      array[1, 1, 1, 1, 1, 1] int arg_2 = {{{{{{1}}}}}};
      array[1, 1, 1, 1, 1, 1] real value = fmod(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmod(array[,,,,]row_vector,int)=>array[,,,,]row_vector
    {
      array[1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{[(2.4500000000000002 + 0.0625 * seed)]}}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1, 1] row_vector[1] value = fmod(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmod(int,array[]matrix)=>array[]matrix
    {
      int arg_1 = 2;
      array[1] matrix[1, 1] arg_2 = {[[(0.94999999999999996 + 0.0625 * seed)]]};
      array[1] matrix[1, 1] value = fmod(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmod(matrix,real)=>matrix
    {
      matrix[1, 1] arg_1 = [[(2.4500000000000002 + 0.0625 * seed)]];
      real arg_2 = (0.94999999999999996 + 0.0625 * seed);
      matrix[1, 1] value = fmod(arg_1, arg_2);
      total += 1.0625 * sum(value);
    }
    // fmod(real,array[,,,,]matrix)=>array[,,,,]matrix
    {
      real arg_1 = (2.4500000000000002 + 0.0625 * seed);
      array[1, 1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{{[[(0.94999999999999996 + 0.0625 * seed)]]}}}}};
      array[1, 1, 1, 1, 1] matrix[1, 1] value = fmod(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // gamma_p(array[,,,,,,]vector,array[,,,,,,]vector)=>array[,,,,,,]vector
    {
      array[1, 1, 1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{{{[(1.95 + 0.0625 * seed)]'}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] vector[1] arg_2 = {{{{{{{[(1.25 + 0.0625 * seed)]'}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] vector[1] value = gamma_p(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // gamma_p(array[,,,]vector,array[,,,]vector)=>array[,,,]vector
    {
      array[1, 1, 1, 1] vector[1] arg_1 = {{{{[(1.95 + 0.0625 * seed)]'}}}};
      array[1, 1, 1, 1] vector[1] arg_2 = {{{{[(1.25 + 0.0625 * seed)]'}}}};
      array[1, 1, 1, 1] vector[1] value = gamma_p(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // gamma_p(array[,]vector,real)=>array[,]vector
    {
      array[1, 1] vector[1] arg_1 = {{[(1.95 + 0.0625 * seed)]'}};
      real arg_2 = (1.25 + 0.0625 * seed);
      array[1, 1] vector[1] value = gamma_p(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // gamma_p(real,array[,,,,,,]vector)=>array[,,,,,,]vector
    {
      real arg_1 = (1.95 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1, 1] vector[1] arg_2 = {{{{{{{[(1.25 + 0.0625 * seed)]'}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] vector[1] value = gamma_p(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // gamma_p(real,array[,,,,,]row_vector)=>array[,,,,,]row_vector
    {
      real arg_1 = (1.95 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1] row_vector[1] arg_2 = {{{{{{[(1.25 + 0.0625 * seed)]}}}}}};
      array[1, 1, 1, 1, 1, 1] row_vector[1] value = gamma_p(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // gamma_p(real,array[,,]matrix)=>array[,,]matrix
    {
      real arg_1 = (1.95 + 0.0625 * seed);
      array[1, 1, 1] matrix[1, 1] arg_2 = {{{[[(1.25 + 0.0625 * seed)]]}}};
      array[1, 1, 1] matrix[1, 1] value = gamma_p(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // gamma_q(array[]matrix,real)=>array[]matrix
    {
      array[1] matrix[1, 1] arg_1 = {[[(1.95 + 0.0625 * seed)]]};
      real arg_2 = (1.25 + 0.0625 * seed);
      array[1] matrix[1, 1] value = gamma_q(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // hypot(array[,,,,,,,]real,int)=>array[,,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{{{(0.45000000000000001 + 0.0625 * seed)}}}}}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1, 1, 1, 1, 1] real value = hypot(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // hypot(array[,,,,,]matrix,int)=>array[,,,,,]matrix
    {
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] value = hypot(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // hypot(array[,,,,]int,array[,,,,]int)=>array[,,,,]real
    {
      array[1, 1, 1, 1, 1] int arg_1 = {{{{{0}}}}};
      array[1, 1, 1, 1, 1] int arg_2 = {{{{{1}}}}};
      array[1, 1, 1, 1, 1] real value = hypot(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // hypot(array[,,,,]matrix,real)=>array[,,,,]matrix
    {
      array[1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}}};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1, 1, 1, 1, 1] matrix[1, 1] value = hypot(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // hypot(array[,,,]real,real)=>array[,,,]real
    {
      array[1, 1, 1, 1] real arg_1 = {{{{(0.45000000000000001 + 0.0625 * seed)}}}};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1, 1, 1, 1] real value = hypot(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // hypot(array[,,,]row_vector,real)=>array[,,,]row_vector
    {
      array[1, 1, 1, 1] row_vector[1] arg_1 = {{{{[(0.45000000000000001 + 0.0625 * seed)]}}}};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1, 1, 1, 1] row_vector[1] value = hypot(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // hypot(int,array[,]vector)=>array[,]vector
    {
      int arg_1 = 0;
      array[1, 1] vector[1] arg_2 = {{[(1.2 + 0.0625 * seed)]'}};
      array[1, 1] vector[1] value = hypot(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // hypot(real,array[,,,,,,]matrix)=>array[,,,,,,]matrix
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{{{{[[(1.2 + 0.0625 * seed)]]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] value = hypot(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // hypot(real,array[,,,]vector)=>array[,,,]vector
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1, 1, 1] vector[1] arg_2 = {{{{[(1.2 + 0.0625 * seed)]'}}}};
      array[1, 1, 1, 1] vector[1] value = hypot(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // hypot(real,array[,,]matrix)=>array[,,]matrix
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1, 1] matrix[1, 1] arg_2 = {{{[[(1.2 + 0.0625 * seed)]]}}};
      array[1, 1, 1] matrix[1, 1] value = hypot(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // inv(array[,,]row_vector)=>array[,,]row_vector
    {
      array[1, 1, 1] row_vector[1] arg_1 = {{{[(0.45000000000000001 + 0.0625 * seed)]}}};
      array[1, 1, 1] row_vector[1] value = inv(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // inv(array[]real)=>array[]real
    {
      array[1] real arg_1 = {(0.45000000000000001 + 0.0625 * seed)};
      array[1] real value = inv(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // inv_Phi(array[,,,,,,]vector)=>array[,,,,,,]vector
    {
      array[1, 1, 1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] vector[1] value = inv_Phi(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // inv_Phi(array[,,,,]real)=>array[,,,,]real
    {
      array[1, 1, 1, 1, 1] real arg_1 = {{{{{(0.45000000000000001 + 0.0625 * seed)}}}}};
      array[1, 1, 1, 1, 1] real value = inv_Phi(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // inv_cloglog(array[,,]matrix)=>array[,,]matrix
    {
      array[1, 1, 1] matrix[1, 1] arg_1 = {{{[[(0.45000000000000001 + 0.0625 * seed)]]}}};
      array[1, 1, 1] matrix[1, 1] value = inv_cloglog(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // inv_logit(array[,,,,,,]matrix)=>array[,,,,,,]matrix
    {
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] value = inv_logit(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // inv_sqrt(array[]int)=>array[]real
    {
      array[1] int arg_1 = {1};
      array[1] real value = inv_sqrt(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // inv_square(array[,,,,]real)=>array[,,,,]real
    {
      array[1, 1, 1, 1, 1] real arg_1 = {{{{{(0.45000000000000001 + 0.0625 * seed)}}}}};
      array[1, 1, 1, 1, 1] real value = inv_square(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // lambert_w0(array[,,,,,]real)=>array[,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{(0.45000000000000001 + 0.0625 * seed)}}}}}};
      array[1, 1, 1, 1, 1, 1] real value = lambert_w0(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // lambert_w0(array[,,,,]int)=>array[,,,,]real
    {
      array[1, 1, 1, 1, 1] int arg_1 = {{{{{1}}}}};
      array[1, 1, 1, 1, 1] real value = lambert_w0(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // lambert_w0(array[,,]int)=>array[,,]real
    {
      array[1, 1, 1] int arg_1 = {{{1}}};
      array[1, 1, 1] real value = lambert_w0(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // lbeta(array[,,,,,,]real,int)=>array[,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{{(1.95 + 0.0625 * seed)}}}}}}};
      int arg_2 = 3;
      array[1, 1, 1, 1, 1, 1, 1] real value = lbeta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lbeta(array[,,,,,,]row_vector,array[,,,,,,]row_vector)=>array[,,,,,,]row_vector
    {
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{{{[(1.95 + 0.0625 * seed)]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] arg_2 = {{{{{{{[(2.9500000000000002 + 0.0625 * seed)]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] value = lbeta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lbeta(array[,,]matrix,int)=>array[,,]matrix
    {
      array[1, 1, 1] matrix[1, 1] arg_1 = {{{[[(1.95 + 0.0625 * seed)]]}}};
      int arg_2 = 3;
      array[1, 1, 1] matrix[1, 1] value = lbeta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lbeta(array[,]int,array[,]int)=>array[,]real
    {
      array[1, 1] int arg_1 = {{2}};
      array[1, 1] int arg_2 = {{3}};
      array[1, 1] real value = lbeta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lbeta(array[]vector,real)=>array[]vector
    {
      array[1] vector[1] arg_1 = {[(1.95 + 0.0625 * seed)]'};
      real arg_2 = (2.9500000000000002 + 0.0625 * seed);
      array[1] vector[1] value = lbeta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lbeta(int,array[,,,,]matrix)=>array[,,,,]matrix
    {
      int arg_1 = 2;
      array[1, 1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{{[[(2.9500000000000002 + 0.0625 * seed)]]}}}}};
      array[1, 1, 1, 1, 1] matrix[1, 1] value = lbeta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lbeta(matrix,int)=>matrix
    {
      matrix[1, 1] arg_1 = [[(1.95 + 0.0625 * seed)]];
      int arg_2 = 3;
      matrix[1, 1] value = lbeta(arg_1, arg_2);
      total += 1.15625 * sum(value);
    }
    // lbeta(real,array[,,,,]vector)=>array[,,,,]vector
    {
      real arg_1 = (1.95 + 0.0625 * seed);
      array[1, 1, 1, 1, 1] vector[1] arg_2 = {{{{{[(2.9500000000000002 + 0.0625 * seed)]'}}}}};
      array[1, 1, 1, 1, 1] vector[1] value = lbeta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lbeta(real,array[,,,]matrix)=>array[,,,]matrix
    {
      real arg_1 = (1.95 + 0.0625 * seed);
      array[1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{[[(2.9500000000000002 + 0.0625 * seed)]]}}}};
      array[1, 1, 1, 1] matrix[1, 1] value = lbeta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lbeta(real,array[,]real)=>array[,]real
    {
      real arg_1 = (1.95 + 0.0625 * seed);
      array[1, 1] real arg_2 = {{(2.9500000000000002 + 0.0625 * seed)}};
      array[1, 1] real value = lbeta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lchoose(array[,,,,,]row_vector,int)=>array[,,,,,]row_vector
    {
      array[1, 1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{{[(3.9500000000000002 + 0.0625 * seed)]}}}}}};
      int arg_2 = 2;
      array[1, 1, 1, 1, 1, 1] row_vector[1] value = lchoose(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lchoose(array[,,,,]row_vector,int)=>array[,,,,]row_vector
    {
      array[1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{[(3.9500000000000002 + 0.0625 * seed)]}}}}};
      int arg_2 = 2;
      array[1, 1, 1, 1, 1] row_vector[1] value = lchoose(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lchoose(array[,,]row_vector,array[,,]row_vector)=>array[,,]row_vector
    {
      array[1, 1, 1] row_vector[1] arg_1 = {{{[(3.9500000000000002 + 0.0625 * seed)]}}};
      array[1, 1, 1] row_vector[1] arg_2 = {{{[(1.95 + 0.0625 * seed)]}}};
      array[1, 1, 1] row_vector[1] value = lchoose(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lchoose(int,array[,,,,,,]int)=>array[,,,,,,]real
    {
      int arg_1 = 4;
      array[1, 1, 1, 1, 1, 1, 1] int arg_2 = {{{{{{{2}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] real value = lchoose(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // ldexp(array[,,,,]real,array[,,,,]int)=>array[,,,,]real
    {
      array[1, 1, 1, 1, 1] real arg_1 = {{{{{(0.45000000000000001 + 0.0625 * seed)}}}}};
      array[1, 1, 1, 1, 1] int arg_2 = {{{{{2}}}}};
      array[1, 1, 1, 1, 1] real value = ldexp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // ldexp(array[,,]vector,int)=>array[,,]vector
    {
      array[1, 1, 1] vector[1] arg_1 = {{{[(0.45000000000000001 + 0.0625 * seed)]'}}};
      int arg_2 = 2;
      array[1, 1, 1] vector[1] value = ldexp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // ldexp(matrix,array[,]int)=>matrix
    {
      matrix[1, 1] arg_1 = [[(0.45000000000000001 + 0.0625 * seed)]];
      array[1, 1] int arg_2 = {{2}};
      matrix[1, 1] value = ldexp(arg_1, arg_2);
      total += 1.125 * sum(value);
    }
    // lgamma(array[,,,,,,]matrix)=>array[,,,,,,]matrix
    {
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{{{[[(1.3499999999999999 + 0.0625 * seed)]]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] value = lgamma(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // lgamma(array[]row_vector)=>array[]row_vector
    {
      array[1] row_vector[1] arg_1 = {[(1.3499999999999999 + 0.0625 * seed)]};
      array[1] row_vector[1] value = lgamma(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // linspaced_row_vector(int,real,real)=>row_vector
    {
      row_vector[1] value = linspaced_row_vector(1, -0.050000000000000003, 0.94999999999999996);
      total += 1.140625 * sum(value);
    }
    // linspaced_vector(int,real,real)=>vector
    {
      vector[1] value = linspaced_vector(1, -0.050000000000000003, 0.94999999999999996);
      total += 1.25 * sum(value);
    }
    // lmgamma(array[,,,]int,array[,,]vector)=>array[,,]vector
    {
      array[1, 1, 1, 1] int arg_1 = {{{{2}}}};
      array[1, 1, 1] vector[1] arg_2 = {{{[(1.95 + 0.0625 * seed)]'}}};
      array[1, 1, 1] vector[1] value = lmgamma(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lmgamma(array[,,]int,array[,]row_vector)=>array[,]row_vector
    {
      array[1, 1, 1] int arg_1 = {{{2}}};
      array[1, 1] row_vector[1] arg_2 = {{[(1.95 + 0.0625 * seed)]}};
      array[1, 1] row_vector[1] value = lmgamma(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lmgamma(int,array[,,]real)=>array[,,]real
    {
      int arg_1 = 2;
      array[1, 1, 1] real arg_2 = {{{(1.95 + 0.0625 * seed)}}};
      array[1, 1, 1] real value = lmgamma(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lmultiply(array[,,,,,]row_vector,array[,,,,,]row_vector)=>array[,,,,,]row_vector
    {
      array[1, 1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{{[(0.45000000000000001 + 0.0625 * seed)]}}}}}};
      array[1, 1, 1, 1, 1, 1] row_vector[1] arg_2 = {{{{{{[(1.2 + 0.0625 * seed)]}}}}}};
      array[1, 1, 1, 1, 1, 1] row_vector[1] value = lmultiply(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lmultiply(array[,,,,]matrix,array[,,,,]matrix)=>array[,,,,]matrix
    {
      array[1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}}};
      array[1, 1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{{[[(1.2 + 0.0625 * seed)]]}}}}};
      array[1, 1, 1, 1, 1] matrix[1, 1] value = lmultiply(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lmultiply(array[,,,,]real,int)=>array[,,,,]real
    {
      array[1, 1, 1, 1, 1] real arg_1 = {{{{{(0.45000000000000001 + 0.0625 * seed)}}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1, 1] real value = lmultiply(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lmultiply(array[,,,]real,int)=>array[,,,]real
    {
      array[1, 1, 1, 1] real arg_1 = {{{{(0.45000000000000001 + 0.0625 * seed)}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1] real value = lmultiply(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lmultiply(array[,]int,array[,]int)=>array[,]real
    {
      array[1, 1] int arg_1 = {{0}};
      array[1, 1] int arg_2 = {{1}};
      array[1, 1] real value = lmultiply(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lmultiply(int,array[,]vector)=>array[,]vector
    {
      int arg_1 = 0;
      array[1, 1] vector[1] arg_2 = {{[(1.2 + 0.0625 * seed)]'}};
      array[1, 1] vector[1] value = lmultiply(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lmultiply(int,array[]real)=>array[]real
    {
      int arg_1 = 0;
      array[1] real arg_2 = {(1.2 + 0.0625 * seed)};
      array[1] real value = lmultiply(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lmultiply(real,array[,,,,,,,]int)=>array[,,,,,,,]real
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1, 1, 1] int arg_2 = {{{{{{{{1}}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1, 1] real value = lmultiply(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lmultiply(real,array[,,,,,,,]real)=>array[,,,,,,,]real
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1, 1, 1] real arg_2 = {{{{{{{{(1.2 + 0.0625 * seed)}}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1, 1] real value = lmultiply(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log(array[,,,,,,]vector)=>array[,,,,,,]vector
    {
      array[1, 1, 1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{{{[(1.3499999999999999 + 0.0625 * seed)]'}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] vector[1] value = log(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log(array[,,,]int)=>array[,,,]real
    {
      array[1, 1, 1, 1] int arg_1 = {{{{1}}}};
      array[1, 1, 1, 1] real value = log(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log(int)=>real
    {
      int arg_1 = 1;
      real value = log(arg_1);
      total += 1.109375 * value;
    }
    // log10(array[]matrix)=>array[]matrix
    {
      array[1] matrix[1, 1] arg_1 = {[[(1.3499999999999999 + 0.0625 * seed)]]};
      array[1] matrix[1, 1] value = log10(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log10(array[]row_vector)=>array[]row_vector
    {
      array[1] row_vector[1] arg_1 = {[(1.3499999999999999 + 0.0625 * seed)]};
      array[1] row_vector[1] value = log10(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log1m(array[,,,,,]matrix)=>array[,,,,,]matrix
    {
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{{[[(0.29999999999999999 + 0.0625 * seed)]]}}}}}};
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] value = log1m(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log1m_inv_logit(array[]int)=>array[]real
    {
      array[1] int arg_1 = {1};
      array[1] real value = log1m_inv_logit(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log1p(array[,,,,,,]int)=>array[,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{{1}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] real value = log1p(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log1p(array[,,,]row_vector)=>array[,,,]row_vector
    {
      array[1, 1, 1, 1] row_vector[1] arg_1 = {{{{[(0.45000000000000001 + 0.0625 * seed)]}}}};
      array[1, 1, 1, 1] row_vector[1] value = log1p(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log1p(array[,,]row_vector)=>array[,,]row_vector
    {
      array[1, 1, 1] row_vector[1] arg_1 = {{{[(0.45000000000000001 + 0.0625 * seed)]}}};
      array[1, 1, 1] row_vector[1] value = log1p(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log1p(array[,]row_vector)=>array[,]row_vector
    {
      array[1, 1] row_vector[1] arg_1 = {{[(0.45000000000000001 + 0.0625 * seed)]}};
      array[1, 1] row_vector[1] value = log1p(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log1p_exp(array[,,,,]vector)=>array[,,,,]vector
    {
      array[1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}}};
      array[1, 1, 1, 1, 1] vector[1] value = log1p_exp(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log1p_exp(array[,]real)=>array[,]real
    {
      array[1, 1] real arg_1 = {{(0.45000000000000001 + 0.0625 * seed)}};
      array[1, 1] real value = log1p_exp(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log1p_exp(array[]matrix)=>array[]matrix
    {
      array[1] matrix[1, 1] arg_1 = {[[(0.45000000000000001 + 0.0625 * seed)]]};
      array[1] matrix[1, 1] value = log1p_exp(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log2(array[,,,,,,]row_vector)=>array[,,,,,,]row_vector
    {
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{{{[(1.3499999999999999 + 0.0625 * seed)]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] value = log2(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log_diff_exp(array[,,,,,]real,array[,,,,,]real)=>array[,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{(1.45 + 0.0625 * seed)}}}}}};
      array[1, 1, 1, 1, 1, 1] real arg_2 = {{{{{{(0.45000000000000001 + 0.0625 * seed)}}}}}};
      array[1, 1, 1, 1, 1, 1] real value = log_diff_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_diff_exp(array[,,,,,]vector,real)=>array[,,,,,]vector
    {
      array[1, 1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{{[(1.45 + 0.0625 * seed)]'}}}}}};
      real arg_2 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1] vector[1] value = log_diff_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_diff_exp(array[,,,,]vector,int)=>array[,,,,]vector
    {
      array[1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{[(1.45 + 0.0625 * seed)]'}}}}};
      int arg_2 = 0;
      array[1, 1, 1, 1, 1] vector[1] value = log_diff_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_diff_exp(array[,,,]matrix,real)=>array[,,,]matrix
    {
      array[1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{[[(1.45 + 0.0625 * seed)]]}}}};
      real arg_2 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1, 1, 1] matrix[1, 1] value = log_diff_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_diff_exp(array[]matrix,int)=>array[]matrix
    {
      array[1] matrix[1, 1] arg_1 = {[[(1.45 + 0.0625 * seed)]]};
      int arg_2 = 0;
      array[1] matrix[1, 1] value = log_diff_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_diff_exp(int,array[,,,,,]row_vector)=>array[,,,,,]row_vector
    {
      int arg_1 = 1;
      array[1, 1, 1, 1, 1, 1] row_vector[1] arg_2 = {{{{{{[(0.45000000000000001 + 0.0625 * seed)]}}}}}};
      array[1, 1, 1, 1, 1, 1] row_vector[1] value = log_diff_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_diff_exp(int,array[,,]real)=>array[,,]real
    {
      int arg_1 = 1;
      array[1, 1, 1] real arg_2 = {{{(0.45000000000000001 + 0.0625 * seed)}}};
      array[1, 1, 1] real value = log_diff_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_diff_exp(vector,vector)=>vector
    {
      vector[1] arg_1 = [(1.45 + 0.0625 * seed)]';
      vector[1] arg_2 = [(0.45000000000000001 + 0.0625 * seed)]';
      vector[1] value = log_diff_exp(arg_1, arg_2);
      total += 1.203125 * sum(value);
    }
    // log_falling_factorial(array[,,,,,,]int,array[,,,,,,]int)=>array[,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{{3}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] int arg_2 = {{{{{{{1}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] real value = log_falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_falling_factorial(array[,,,,,]real,array[,,,,,]real)=>array[,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{(3.4500000000000002 + 0.0625 * seed)}}}}}};
      array[1, 1, 1, 1, 1, 1] real arg_2 = {{{{{{(1.1499999999999999 + 0.0625 * seed)}}}}}};
      array[1, 1, 1, 1, 1, 1] real value = log_falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_falling_factorial(array[,,,,,]real,real)=>array[,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{(3.4500000000000002 + 0.0625 * seed)}}}}}};
      real arg_2 = (1.1499999999999999 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1] real value = log_falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_falling_factorial(array[,,,]matrix,array[,,,]matrix)=>array[,,,]matrix
    {
      array[1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{[[(3.4500000000000002 + 0.0625 * seed)]]}}}};
      array[1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{[[(1.1499999999999999 + 0.0625 * seed)]]}}}};
      array[1, 1, 1, 1] matrix[1, 1] value = log_falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_falling_factorial(array[,,,]vector,array[,,,]vector)=>array[,,,]vector
    {
      array[1, 1, 1, 1] vector[1] arg_1 = {{{{[(3.4500000000000002 + 0.0625 * seed)]'}}}};
      array[1, 1, 1, 1] vector[1] arg_2 = {{{{[(1.1499999999999999 + 0.0625 * seed)]'}}}};
      array[1, 1, 1, 1] vector[1] value = log_falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_falling_factorial(array[,,]matrix,real)=>array[,,]matrix
    {
      array[1, 1, 1] matrix[1, 1] arg_1 = {{{[[(3.4500000000000002 + 0.0625 * seed)]]}}};
      real arg_2 = (1.1499999999999999 + 0.0625 * seed);
      array[1, 1, 1] matrix[1, 1] value = log_falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_falling_factorial(int,array[,,,,,]real)=>array[,,,,,]real
    {
      int arg_1 = 3;
      array[1, 1, 1, 1, 1, 1] real arg_2 = {{{{{{(1.1499999999999999 + 0.0625 * seed)}}}}}};
      array[1, 1, 1, 1, 1, 1] real value = log_falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_falling_factorial(int,array[,,,,]matrix)=>array[,,,,]matrix
    {
      int arg_1 = 3;
      array[1, 1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{{[[(1.1499999999999999 + 0.0625 * seed)]]}}}}};
      array[1, 1, 1, 1, 1] matrix[1, 1] value = log_falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_falling_factorial(int,array[,,,,]row_vector)=>array[,,,,]row_vector
    {
      int arg_1 = 3;
      array[1, 1, 1, 1, 1] row_vector[1] arg_2 = {{{{{[(1.1499999999999999 + 0.0625 * seed)]}}}}};
      array[1, 1, 1, 1, 1] row_vector[1] value = log_falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_falling_factorial(matrix,int)=>matrix
    {
      matrix[1, 1] arg_1 = [[(3.4500000000000002 + 0.0625 * seed)]];
      int arg_2 = 1;
      matrix[1, 1] value = log_falling_factorial(arg_1, arg_2);
      total += 1.046875 * sum(value);
    }
    // log_falling_factorial(real,array[,,,,,,]real)=>array[,,,,,,]real
    {
      real arg_1 = (3.4500000000000002 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1, 1] real arg_2 = {{{{{{{(1.1499999999999999 + 0.0625 * seed)}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] real value = log_falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_falling_factorial(vector,int)=>vector
    {
      vector[1] arg_1 = [(3.4500000000000002 + 0.0625 * seed)]';
      int arg_2 = 1;
      vector[1] value = log_falling_factorial(arg_1, arg_2);
      total += 1.25 * sum(value);
    }
    // log_inv_logit_diff(array[,,,]matrix,int)=>array[,,,]matrix
    {
      array[1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{[[(0.94999999999999996 + 0.0625 * seed)]]}}}};
      int arg_2 = 0;
      array[1, 1, 1, 1] matrix[1, 1] value = log_inv_logit_diff(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_inv_logit_diff(array[,,]int,int)=>array[,,]real
    {
      array[1, 1, 1] int arg_1 = {{{1}}};
      int arg_2 = 0;
      array[1, 1, 1] real value = log_inv_logit_diff(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_inv_logit_diff(array[]matrix,int)=>array[]matrix
    {
      array[1] matrix[1, 1] arg_1 = {[[(0.94999999999999996 + 0.0625 * seed)]]};
      int arg_2 = 0;
      array[1] matrix[1, 1] value = log_inv_logit_diff(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_inv_logit_diff(real,array[,,,,,,]row_vector)=>array[,,,,,,]row_vector
    {
      real arg_1 = (0.94999999999999996 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] arg_2 = {{{{{{{[(-0.55000000000000004 + 0.0625 * seed)]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] value = log_inv_logit_diff(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_inv_logit_diff(real,array[,,,,,]matrix)=>array[,,,,,]matrix
    {
      real arg_1 = (0.94999999999999996 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{{{[[(-0.55000000000000004 + 0.0625 * seed)]]}}}}}};
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] value = log_inv_logit_diff(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_inv_logit_diff(real,array[,,,,,]row_vector)=>array[,,,,,]row_vector
    {
      real arg_1 = (0.94999999999999996 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1] row_vector[1] arg_2 = {{{{{{[(-0.55000000000000004 + 0.0625 * seed)]}}}}}};
      array[1, 1, 1, 1, 1, 1] row_vector[1] value = log_inv_logit_diff(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_inv_logit_diff(real,array[,,,,]matrix)=>array[,,,,]matrix
    {
      real arg_1 = (0.94999999999999996 + 0.0625 * seed);
      array[1, 1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{{[[(-0.55000000000000004 + 0.0625 * seed)]]}}}}};
      array[1, 1, 1, 1, 1] matrix[1, 1] value = log_inv_logit_diff(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_modified_bessel_first_kind(array[,,,,,,]matrix,array[,,,,,,]matrix)=>array[,,,,,,]matrix
    {
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{{{{[[(1.2 + 0.0625 * seed)]]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] value = log_modified_bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_modified_bessel_first_kind(array[,,,,,,]real,int)=>array[,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{{(0.45000000000000001 + 0.0625 * seed)}}}}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1, 1, 1, 1] real value = log_modified_bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_modified_bessel_first_kind(real,array[,,,]row_vector)=>array[,,,]row_vector
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1, 1, 1] row_vector[1] arg_2 = {{{{[(1.2 + 0.0625 * seed)]}}}};
      array[1, 1, 1, 1] row_vector[1] value = log_modified_bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_modified_bessel_first_kind(real,array[,,,]vector)=>array[,,,]vector
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1, 1, 1] vector[1] arg_2 = {{{{[(1.2 + 0.0625 * seed)]'}}}};
      array[1, 1, 1, 1] vector[1] value = log_modified_bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_modified_bessel_first_kind(real,array[,,]matrix)=>array[,,]matrix
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1, 1] matrix[1, 1] arg_2 = {{{[[(1.2 + 0.0625 * seed)]]}}};
      array[1, 1, 1] matrix[1, 1] value = log_modified_bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_modified_bessel_first_kind(real,matrix)=>matrix
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      matrix[1, 1] arg_2 = [[(1.2 + 0.0625 * seed)]];
      matrix[1, 1] value = log_modified_bessel_first_kind(arg_1, arg_2);
      total += 1.140625 * sum(value);
    }
    // log_modified_bessel_first_kind(row_vector,real)=>row_vector
    {
      row_vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)];
      real arg_2 = (1.2 + 0.0625 * seed);
      row_vector[1] value = log_modified_bessel_first_kind(arg_1, arg_2);
      total += 1.15625 * sum(value);
    }
    // log_rising_factorial(array[,,]real,array[,,]real)=>array[,,]real
    {
      array[1, 1, 1] real arg_1 = {{{(1.45 + 0.0625 * seed)}}};
      array[1, 1, 1] real arg_2 = {{{(1.1499999999999999 + 0.0625 * seed)}}};
      array[1, 1, 1] real value = log_rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_rising_factorial(array[,,]real,int)=>array[,,]real
    {
      array[1, 1, 1] real arg_1 = {{{(1.45 + 0.0625 * seed)}}};
      int arg_2 = 1;
      array[1, 1, 1] real value = log_rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_rising_factorial(array[]vector,array[]vector)=>array[]vector
    {
      array[1] vector[1] arg_1 = {[(1.45 + 0.0625 * seed)]'};
      array[1] vector[1] arg_2 = {[(1.1499999999999999 + 0.0625 * seed)]'};
      array[1] vector[1] value = log_rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_rising_factorial(int,array[,,,]real)=>array[,,,]real
    {
      int arg_1 = 1;
      array[1, 1, 1, 1] real arg_2 = {{{{(1.1499999999999999 + 0.0625 * seed)}}}};
      array[1, 1, 1, 1] real value = log_rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_rising_factorial(int,array[,,]int)=>array[,,]real
    {
      int arg_1 = 1;
      array[1, 1, 1] int arg_2 = {{{1}}};
      array[1, 1, 1] real value = log_rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_rising_factorial(real,array[,,]real)=>array[,,]real
    {
      real arg_1 = (1.45 + 0.0625 * seed);
      array[1, 1, 1] real arg_2 = {{{(1.1499999999999999 + 0.0625 * seed)}}};
      array[1, 1, 1] real value = log_rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_rising_factorial(row_vector,int)=>row_vector
    {
      row_vector[1] arg_1 = [(1.45 + 0.0625 * seed)];
      int arg_2 = 1;
      row_vector[1] value = log_rising_factorial(arg_1, arg_2);
      total += 1.046875 * sum(value);
    }
    // log_sum_exp(array[,,]int,real)=>array[,,]real
    {
      array[1, 1, 1] int arg_1 = {{{0}}};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1, 1, 1] real value = log_sum_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_sum_exp(array[,,]matrix,array[,,]matrix)=>array[,,]matrix
    {
      array[1, 1, 1] matrix[1, 1] arg_1 = {{{[[(0.45000000000000001 + 0.0625 * seed)]]}}};
      array[1, 1, 1] matrix[1, 1] arg_2 = {{{[[(1.2 + 0.0625 * seed)]]}}};
      array[1, 1, 1] matrix[1, 1] value = log_sum_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_sum_exp(int,array[,,,,,]vector)=>array[,,,,,]vector
    {
      int arg_1 = 0;
      array[1, 1, 1, 1, 1, 1] vector[1] arg_2 = {{{{{{[(1.2 + 0.0625 * seed)]'}}}}}};
      array[1, 1, 1, 1, 1, 1] vector[1] value = log_sum_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // minus(array[,,,]real)=>array[,,,]real
    {
      array[1, 1, 1, 1] real arg_1 = {{{{(0.45000000000000001 + 0.0625 * seed)}}}};
      array[1, 1, 1, 1] real value = minus(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // minus(array[,,]real)=>array[,,]real
    {
      array[1, 1, 1] real arg_1 = {{{(0.45000000000000001 + 0.0625 * seed)}}};
      array[1, 1, 1] real value = minus(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // minus(array[,]vector)=>array[,]vector
    {
      array[1, 1] vector[1] arg_1 = {{[(0.45000000000000001 + 0.0625 * seed)]'}};
      array[1, 1] vector[1] value = minus(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // minus(row_vector)=>row_vector
    {
      row_vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)];
      row_vector[1] value = minus(arg_1);
      total += 1.046875 * sum(value);
    }
    // modified_bessel_first_kind(array[,,,,,]int,real)=>array[,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{2}}}}}};
      real arg_2 = (1.3499999999999999 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1] real value = modified_bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // modified_bessel_first_kind(array[,,,,]int,array[,,,]row_vector)=>array[,,,]row_vector
    {
      array[1, 1, 1, 1, 1] int arg_1 = {{{{{2}}}}};
      array[1, 1, 1, 1] row_vector[1] arg_2 = {{{{[(1.3499999999999999 + 0.0625 * seed)]}}}};
      array[1, 1, 1, 1] row_vector[1] value = modified_bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // modified_bessel_first_kind(array[,]int,matrix)=>matrix
    {
      array[1, 1] int arg_1 = {{2}};
      matrix[1, 1] arg_2 = [[(1.3499999999999999 + 0.0625 * seed)]];
      matrix[1, 1] value = modified_bessel_first_kind(arg_1, arg_2);
      total += 1.15625 * sum(value);
    }
    // modified_bessel_first_kind(int,array[,,,]real)=>array[,,,]real
    {
      int arg_1 = 2;
      array[1, 1, 1, 1] real arg_2 = {{{{(1.3499999999999999 + 0.0625 * seed)}}}};
      array[1, 1, 1, 1] real value = modified_bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // modified_bessel_second_kind(array[,,,,,]int,array[,,,,,]real)=>array[,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{2}}}}}};
      array[1, 1, 1, 1, 1, 1] real arg_2 = {{{{{{(1.3499999999999999 + 0.0625 * seed)}}}}}};
      array[1, 1, 1, 1, 1, 1] real value = modified_bessel_second_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // modified_bessel_second_kind(array[,,,]int,real)=>array[,,,]real
    {
      array[1, 1, 1, 1] int arg_1 = {{{{2}}}};
      real arg_2 = (1.3499999999999999 + 0.0625 * seed);
      array[1, 1, 1, 1] real value = modified_bessel_second_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // modified_bessel_second_kind(array[,,]int,array[,,]real)=>array[,,]real
    {
      array[1, 1, 1] int arg_1 = {{{2}}};
      array[1, 1, 1] real arg_2 = {{{(1.3499999999999999 + 0.0625 * seed)}}};
      array[1, 1, 1] real value = modified_bessel_second_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // modified_bessel_second_kind(array[,]int,array[]row_vector)=>array[]row_vector
    {
      array[1, 1] int arg_1 = {{2}};
      array[1] row_vector[1] arg_2 = {[(1.3499999999999999 + 0.0625 * seed)]};
      array[1] row_vector[1] value = modified_bessel_second_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // modified_bessel_second_kind(int,array[,,,,]row_vector)=>array[,,,,]row_vector
    {
      int arg_1 = 2;
      array[1, 1, 1, 1, 1] row_vector[1] arg_2 = {{{{{[(1.3499999999999999 + 0.0625 * seed)]}}}}};
      array[1, 1, 1, 1, 1] row_vector[1] value = modified_bessel_second_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // modified_bessel_second_kind(int,matrix)=>matrix
    {
      int arg_1 = 2;
      matrix[1, 1] arg_2 = [[(1.3499999999999999 + 0.0625 * seed)]];
      matrix[1, 1] value = modified_bessel_second_kind(arg_1, arg_2);
      total += 1.171875 * sum(value);
    }
    // num_elements(array[,,,]vector)=>int
    {
      array[1, 1, 1, 1] vector[1] arg_1 = {{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}};
      int value = num_elements(arg_1);
      total += 1 * value;
    }
    // num_elements(array[]int)=>int
    {
      array[1] int arg_1 = {2};
      int value = num_elements(arg_1);
      total += 1.140625 * value;
    }
    // owens_t(real,array[,]real)=>array[,]real
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1] real arg_2 = {{(1.2 + 0.0625 * seed)}};
      array[1, 1] real value = owens_t(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // owens_t(real,array[,]row_vector)=>array[,]row_vector
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1] row_vector[1] arg_2 = {{[(1.2 + 0.0625 * seed)]}};
      array[1, 1] row_vector[1] value = owens_t(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // pow(array[,]int,int)=>array[,]real
    {
      array[1, 1] int arg_1 = {{0}};
      int arg_2 = 1;
      array[1, 1] real value = pow(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // pow(array[,]matrix,real)=>array[,]matrix
    {
      array[1, 1] matrix[1, 1] arg_1 = {{[[(0.45000000000000001 + 0.0625 * seed)]]}};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1, 1] matrix[1, 1] value = pow(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // pow(int,array[]vector)=>array[]vector
    {
      int arg_1 = 0;
      array[1] vector[1] arg_2 = {[(1.2 + 0.0625 * seed)]'};
      array[1] vector[1] value = pow(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // pow(matrix,int)=>matrix
    {
      matrix[1, 1] arg_1 = [[(0.45000000000000001 + 0.0625 * seed)]];
      int arg_2 = 1;
      matrix[1, 1] value = pow(arg_1, arg_2);
      total += 1.015625 * sum(value);
    }
    // pow(real,array[,,,,]real)=>array[,,,,]real
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1, 1, 1, 1] real arg_2 = {{{{{(1.2 + 0.0625 * seed)}}}}};
      array[1, 1, 1, 1, 1] real value = pow(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // pow(real,array[,]row_vector)=>array[,]row_vector
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1] row_vector[1] arg_2 = {{[(1.2 + 0.0625 * seed)]}};
      array[1, 1] row_vector[1] value = pow(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // reverse(array[,]matrix)=>array[,]matrix
    {
      array[1, 1] matrix[1, 1] arg_1 = {{[[(0.45000000000000001 + 0.0625 * seed)]]}};
      array[1, 1] matrix[1, 1] value = reverse(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // rising_factorial(array[,,]vector,int)=>array[,,]vector
    {
      array[1, 1, 1] vector[1] arg_1 = {{{[(1.45 + 0.0625 * seed)]'}}};
      int arg_2 = 2;
      array[1, 1, 1] vector[1] value = rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // round(array[]int)=>array[]real
    {
      array[1] int arg_1 = {1};
      array[1] real value = round(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // round(real)=>real
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      real value = round(arg_1);
      total += 1.109375 * value;
    }
    // sin(array[,,,,,,]vector)=>array[,,,,,,]vector
    {
      array[1, 1, 1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] vector[1] value = sin(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // size(array[,]real)=>int
    {
      array[1, 1] real arg_1 = {{(0.45000000000000001 + 0.0625 * seed)}};
      int value = size(arg_1);
      total += 1.125 * value;
    }
    // sqrt(array[,,,]matrix)=>array[,,,]matrix
    {
      array[1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{[[(1.3499999999999999 + 0.0625 * seed)]]}}}};
      array[1, 1, 1, 1] matrix[1, 1] value = sqrt(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // sqrt(array[,,]row_vector)=>array[,,]row_vector
    {
      array[1, 1, 1] row_vector[1] arg_1 = {{{[(1.3499999999999999 + 0.0625 * seed)]}}};
      array[1, 1, 1] row_vector[1] value = sqrt(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // sqrt(array[,]row_vector)=>array[,]row_vector
    {
      array[1, 1] row_vector[1] arg_1 = {{[(1.3499999999999999 + 0.0625 * seed)]}};
      array[1, 1] row_vector[1] value = sqrt(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // std_normal_log_qf(array[,,,,]row_vector)=>array[,,,,]row_vector
    {
      array[1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{[(-0.55000000000000004 + 0.0625 * seed)]}}}}};
      array[1, 1, 1, 1, 1] row_vector[1] value = std_normal_log_qf(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // std_normal_qf(array[,,,,]real)=>array[,,,,]real
    {
      array[1, 1, 1, 1, 1] real arg_1 = {{{{{(0.45000000000000001 + 0.0625 * seed)}}}}};
      array[1, 1, 1, 1, 1] real value = std_normal_qf(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // std_normal_qf(array[,,,]real)=>array[,,,]real
    {
      array[1, 1, 1, 1] real arg_1 = {{{{(0.45000000000000001 + 0.0625 * seed)}}}};
      array[1, 1, 1, 1] real value = std_normal_qf(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // tan(array[,,,,]vector)=>array[,,,,]vector
    {
      array[1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}}};
      array[1, 1, 1, 1, 1] vector[1] value = tan(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // tan(array[,,,]matrix)=>array[,,,]matrix
    {
      array[1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}};
      array[1, 1, 1, 1] matrix[1, 1] value = tan(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // tan(array[,,,]row_vector)=>array[,,,]row_vector
    {
      array[1, 1, 1, 1] row_vector[1] arg_1 = {{{{[(0.45000000000000001 + 0.0625 * seed)]}}}};
      array[1, 1, 1, 1] row_vector[1] value = tan(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // tanh(matrix)=>matrix
    {
      matrix[1, 1] arg_1 = [[(0.45000000000000001 + 0.0625 * seed)]];
      matrix[1, 1] value = tanh(arg_1);
      total += 1.1875 * sum(value);
    }
    // tgamma(array[,,,,,,]vector)=>array[,,,,,,]vector
    {
      array[1, 1, 1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] vector[1] value = tgamma(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // to_array_1d(array[,,,,,,,,]real)=>array[]real
    {
      array[1, 1, 1, 1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{{{{(0.45000000000000001 + 0.0625 * seed)}}}}}}}}};
      array[1] real value = to_array_1d(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // to_array_1d(array[,,,,,]int)=>array[]int
    {
      array[1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{1}}}}}};
      array[1] int value = to_array_1d(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // to_array_1d(row_vector)=>array[]real
    {
      row_vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)];
      array[1] real value = to_array_1d(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // to_matrix(row_vector)=>matrix
    {
      row_vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)];
      matrix[1, 1] value = to_matrix(arg_1);
      total += 1 * sum(value);
    }
    // to_matrix(row_vector,int,int)=>matrix
    {
      row_vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)];
      matrix[1, 1] value = to_matrix(arg_1, 1, 1);
      total += 1.109375 * sum(value);
    }
    // to_matrix(vector)=>matrix
    {
      vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)]';
      matrix[1, 1] value = to_matrix(arg_1);
      total += 1.0625 * sum(value);
    }
    // to_row_vector(matrix)=>row_vector
    {
      matrix[1, 1] arg_1 = [[(0.45000000000000001 + 0.0625 * seed)]];
      row_vector[1] value = to_row_vector(arg_1);
      total += 1.078125 * sum(value);
    }
    // trigamma(array[,,,,,]row_vector)=>array[,,,,,]row_vector
    {
      array[1, 1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{{[(1.3499999999999999 + 0.0625 * seed)]}}}}}};
      array[1, 1, 1, 1, 1, 1] row_vector[1] value = trigamma(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // trigamma(array[,]row_vector)=>array[,]row_vector
    {
      array[1, 1] row_vector[1] arg_1 = {{[(1.3499999999999999 + 0.0625 * seed)]}};
      array[1, 1] row_vector[1] value = trigamma(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // trigamma(real)=>real
    {
      real arg_1 = (1.3499999999999999 + 0.0625 * seed);
      real value = trigamma(arg_1);
      total += 1.015625 * value;
    }
    // trunc(vector)=>vector
    {
      vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)]';
      vector[1] value = trunc(arg_1);
      total += 1.09375 * sum(value);
    }
    return total;
  }
}
data {
  real context_seed;
}
transformed data {
  real transformed_data_result = builtin_signatures_04(context_seed);
}
parameters {
  real probe;
}
model {
  probe ~ std_normal();
  target += builtin_signatures_04(probe);
  if (probe > -1e100)
    target += builtin_signatures_04(probe);
}
generated quantities {
  real generated_quantities_result = builtin_signatures_04(probe);
}
