// STANLI-LIT: PASS
// STANLI-LIT-EXPECT: OK
// STANLI-LIT-DATA: {"context_seed": 0.0}
// STANLI-LIT-TIMEOUT: 180
// Generated by tools/generate_builtin_signature_models.py from the unified FunctionSpec registry
// and `stanc --dump-stan-math-signatures`. Do not edit by hand.
// Partition 8 of 30; 236 overloads.
functions {
  real builtin_signatures_08(real seed) {
    real total = 0;
    // Phi(array[]matrix)=>array[]matrix
    {
      array[1] matrix[1, 1] arg_1 = {[[(0.45000000000000001 + 0.0625 * seed)]]};
      array[1] matrix[1, 1] value = Phi(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // acos(array[,,,,,,]row_vector)=>array[,,,,,,]row_vector
    {
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{{{[(0.29999999999999999 + 0.0625 * seed)]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] value = acos(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // acos(array[,]int)=>array[,]real
    {
      array[1, 1] int arg_1 = {{0}};
      array[1, 1] real value = acos(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // acos(array[]vector)=>array[]vector
    {
      array[1] vector[1] arg_1 = {[(0.29999999999999999 + 0.0625 * seed)]'};
      array[1] vector[1] value = acos(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // acosh(array[,,,,,,]matrix)=>array[,,,,,,]matrix
    {
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{{{[[(1.3499999999999999 + 0.0625 * seed)]]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] value = acosh(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // acosh(array[,,,,,,]row_vector)=>array[,,,,,,]row_vector
    {
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{{{[(1.3499999999999999 + 0.0625 * seed)]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] value = acosh(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // acosh(array[,,,,,]int)=>array[,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{1}}}}}};
      array[1, 1, 1, 1, 1, 1] real value = acosh(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // append_array(array[,]real,array[,]real)=>array[,]real
    {
      array[1, 1] real arg_1 = {{(0.45000000000000001 + 0.0625 * seed)}};
      array[1, 1] real arg_2 = {{(1.2 + 0.0625 * seed)}};
      array[2, 1] real value = append_array(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // append_col(vector,matrix)=>matrix
    {
      vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)]';
      matrix[1, 1] arg_2 = [[(1.2 + 0.0625 * seed)]];
      matrix[1, 2] value = append_col(arg_1, arg_2);
      total += 1 * sum(value);
    }
    // append_row(matrix,row_vector)=>matrix
    {
      matrix[1, 1] arg_1 = [[(0.45000000000000001 + 0.0625 * seed)]];
      row_vector[1] arg_2 = [(1.2 + 0.0625 * seed)];
      matrix[2, 1] value = append_row(arg_1, arg_2);
      total += 1.0625 * sum(value);
    }
    // append_row(row_vector,row_vector)=>matrix
    {
      row_vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)];
      row_vector[1] arg_2 = [(1.2 + 0.0625 * seed)];
      matrix[2, 1] value = append_row(arg_1, arg_2);
      total += 1.125 * sum(value);
    }
    // asin(array[,]real)=>array[,]real
    {
      array[1, 1] real arg_1 = {{(0.29999999999999999 + 0.0625 * seed)}};
      array[1, 1] real value = asin(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // asinh(array[]vector)=>array[]vector
    {
      array[1] vector[1] arg_1 = {[(0.45000000000000001 + 0.0625 * seed)]'};
      array[1] vector[1] value = asinh(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // atan(array[,,,,]row_vector)=>array[,,,,]row_vector
    {
      array[1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{[(0.45000000000000001 + 0.0625 * seed)]}}}}};
      array[1, 1, 1, 1, 1] row_vector[1] value = atan(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // atan2(array[,,,,,,]vector,array[,,,,,,]vector)=>array[,,,,,,]vector
    {
      array[1, 1, 1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] vector[1] arg_2 = {{{{{{{[(1.2 + 0.0625 * seed)]'}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] vector[1] value = atan2(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // atan2(array[,,,,]matrix,array[,,,,]matrix)=>array[,,,,]matrix
    {
      array[1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}}};
      array[1, 1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{{[[(1.2 + 0.0625 * seed)]]}}}}};
      array[1, 1, 1, 1, 1] matrix[1, 1] value = atan2(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // atan2(array[,,,,]vector,int)=>array[,,,,]vector
    {
      array[1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1, 1] vector[1] value = atan2(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // atan2(array[,,]matrix,int)=>array[,,]matrix
    {
      array[1, 1, 1] matrix[1, 1] arg_1 = {{{[[(0.45000000000000001 + 0.0625 * seed)]]}}};
      int arg_2 = 1;
      array[1, 1, 1] matrix[1, 1] value = atan2(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // atan2(int,array[,,,,,,,]real)=>array[,,,,,,,]real
    {
      int arg_1 = 0;
      array[1, 1, 1, 1, 1, 1, 1, 1] real arg_2 = {{{{{{{{(1.2 + 0.0625 * seed)}}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1, 1] real value = atan2(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // atan2(int,array[]matrix)=>array[]matrix
    {
      int arg_1 = 0;
      array[1] matrix[1, 1] arg_2 = {[[(1.2 + 0.0625 * seed)]]};
      array[1] matrix[1, 1] value = atan2(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // atan2(real,array[,]row_vector)=>array[,]row_vector
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1] row_vector[1] arg_2 = {{[(1.2 + 0.0625 * seed)]}};
      array[1, 1] row_vector[1] value = atan2(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // atan2(real,vector)=>vector
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      vector[1] arg_2 = [(1.2 + 0.0625 * seed)]';
      vector[1] value = atan2(arg_1, arg_2);
      total += 1.0625 * sum(value);
    }
    // bessel_first_kind(int,array[,,,,,]vector)=>array[,,,,,]vector
    {
      int arg_1 = 2;
      array[1, 1, 1, 1, 1, 1] vector[1] arg_2 = {{{{{{[(1.3499999999999999 + 0.0625 * seed)]'}}}}}};
      array[1, 1, 1, 1, 1, 1] vector[1] value = bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // bessel_first_kind(int,array[,,,]vector)=>array[,,,]vector
    {
      int arg_1 = 2;
      array[1, 1, 1, 1] vector[1] arg_2 = {{{{[(1.3499999999999999 + 0.0625 * seed)]'}}}};
      array[1, 1, 1, 1] vector[1] value = bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // bessel_second_kind(array[,,,,,,,]int,array[,,,,,,]row_vector)=>array[,,,,,,]row_vector
    {
      array[1, 1, 1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{{{2}}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] arg_2 = {{{{{{{[(1.3499999999999999 + 0.0625 * seed)]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] value = bessel_second_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // bessel_second_kind(array[,,,,,]int,array[,,,]matrix)=>array[,,,]matrix
    {
      array[1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{2}}}}}};
      array[1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{[[(1.3499999999999999 + 0.0625 * seed)]]}}}};
      array[1, 1, 1, 1] matrix[1, 1] value = bessel_second_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // beta(array[,,,,,]vector,array[,,,,,]vector)=>array[,,,,,]vector
    {
      array[1, 1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{{[(1.95 + 0.0625 * seed)]'}}}}}};
      array[1, 1, 1, 1, 1, 1] vector[1] arg_2 = {{{{{{[(2.9500000000000002 + 0.0625 * seed)]'}}}}}};
      array[1, 1, 1, 1, 1, 1] vector[1] value = beta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // beta(array[,,,,]real,int)=>array[,,,,]real
    {
      array[1, 1, 1, 1, 1] real arg_1 = {{{{{(1.95 + 0.0625 * seed)}}}}};
      int arg_2 = 3;
      array[1, 1, 1, 1, 1] real value = beta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // beta(array[,,,]row_vector,real)=>array[,,,]row_vector
    {
      array[1, 1, 1, 1] row_vector[1] arg_1 = {{{{[(1.95 + 0.0625 * seed)]}}}};
      real arg_2 = (2.9500000000000002 + 0.0625 * seed);
      array[1, 1, 1, 1] row_vector[1] value = beta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // beta(array[,,,]vector,array[,,,]vector)=>array[,,,]vector
    {
      array[1, 1, 1, 1] vector[1] arg_1 = {{{{[(1.95 + 0.0625 * seed)]'}}}};
      array[1, 1, 1, 1] vector[1] arg_2 = {{{{[(2.9500000000000002 + 0.0625 * seed)]'}}}};
      array[1, 1, 1, 1] vector[1] value = beta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // beta(array[,,]real,real)=>array[,,]real
    {
      array[1, 1, 1] real arg_1 = {{{(1.95 + 0.0625 * seed)}}};
      real arg_2 = (2.9500000000000002 + 0.0625 * seed);
      array[1, 1, 1] real value = beta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // beta(array[]int,real)=>array[]real
    {
      array[1] int arg_1 = {2};
      real arg_2 = (2.9500000000000002 + 0.0625 * seed);
      array[1] real value = beta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // binary_log_loss(array[,,,,,,,]int,array[,,,,,,]row_vector)=>array[,,,,,,]row_vector
    {
      array[1, 1, 1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{{{1}}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] arg_2 = {{{{{{{[(0.35000000000000003 + 0.0625 * seed)]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] value = binary_log_loss(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // binary_log_loss(array[,]int,array[]row_vector)=>array[]row_vector
    {
      array[1, 1] int arg_1 = {{1}};
      array[1] row_vector[1] arg_2 = {[(0.35000000000000003 + 0.0625 * seed)]};
      array[1] row_vector[1] value = binary_log_loss(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // cos(array[,,]vector)=>array[,,]vector
    {
      array[1, 1, 1] vector[1] arg_1 = {{{[(0.45000000000000001 + 0.0625 * seed)]'}}};
      array[1, 1, 1] vector[1] value = cos(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // digamma(array[,,,]matrix)=>array[,,,]matrix
    {
      array[1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{[[(1.3499999999999999 + 0.0625 * seed)]]}}}};
      array[1, 1, 1, 1] matrix[1, 1] value = digamma(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // digamma(array[,,]int)=>array[,,]real
    {
      array[1, 1, 1] int arg_1 = {{{1}}};
      array[1, 1, 1] real value = digamma(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // digamma(array[,]vector)=>array[,]vector
    {
      array[1, 1] vector[1] arg_1 = {{[(1.3499999999999999 + 0.0625 * seed)]'}};
      array[1, 1] vector[1] value = digamma(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // digamma(array[]int)=>array[]real
    {
      array[1] int arg_1 = {1};
      array[1] real value = digamma(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // dims(array[,,,,,]vector)=>array[]int
    {
      array[1, 1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}}}};
      array[8] int value = dims(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // dims(array[,,]int)=>array[]int
    {
      array[1, 1, 1] int arg_1 = {{{2}}};
      array[3] int value = dims(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // dims(array[]real)=>array[]int
    {
      array[1] real arg_1 = {(0.45000000000000001 + 0.0625 * seed)};
      array[1] int value = dims(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // elt_multiply(real,matrix)=>matrix
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      matrix[1, 1] arg_2 = [[(1.2 + 0.0625 * seed)]];
      matrix[1, 1] value = elt_multiply(arg_1, arg_2);
      total += 1.171875 * sum(value);
    }
    // erf(array[,,,,,]matrix)=>array[,,,,,]matrix
    {
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}}}};
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] value = erf(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // erf(int)=>real
    {
      int arg_1 = 1;
      real value = erf(arg_1);
      total += 1.09375 * value;
    }
    // erfc(array[,,,,,,]real)=>array[,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{{(0.45000000000000001 + 0.0625 * seed)}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] real value = erfc(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // erfc(array[]int)=>array[]real
    {
      array[1] int arg_1 = {1};
      array[1] real value = erfc(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // expm1(array[,,,,,]int)=>array[,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{1}}}}}};
      array[1, 1, 1, 1, 1, 1] real value = expm1(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // expm1(array[,,,,,]matrix)=>array[,,,,,]matrix
    {
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}}}};
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] value = expm1(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // expm1(array[,]vector)=>array[,]vector
    {
      array[1, 1] vector[1] arg_1 = {{[(0.45000000000000001 + 0.0625 * seed)]'}};
      array[1, 1] vector[1] value = expm1(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // falling_factorial(array[,]matrix,array[,,,]int)=>array[,]matrix
    {
      array[1, 1] matrix[1, 1] arg_1 = {{[[(3.4500000000000002 + 0.0625 * seed)]]}};
      array[1, 1, 1, 1] int arg_2 = {{{{2}}}};
      array[1, 1] matrix[1, 1] value = falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // falling_factorial(row_vector,int)=>row_vector
    {
      row_vector[1] arg_1 = [(3.4500000000000002 + 0.0625 * seed)];
      int arg_2 = 2;
      row_vector[1] value = falling_factorial(arg_1, arg_2);
      total += 1.1875 * sum(value);
    }
    // fdim(array[,,,,,,,]int,int)=>array[,,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{{{1}}}}}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1, 1, 1, 1, 1] real value = fdim(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fdim(array[,,,,,,,]real,array[,,,,,,,]real)=>array[,,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{{{(0.94999999999999996 + 0.0625 * seed)}}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1, 1] real arg_2 = {{{{{{{{(0.94999999999999996 + 0.0625 * seed)}}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1, 1] real value = fdim(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fdim(array[,,,,,]vector,int)=>array[,,,,,]vector
    {
      array[1, 1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{{[(0.94999999999999996 + 0.0625 * seed)]'}}}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1, 1, 1] vector[1] value = fdim(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fdim(int,real)=>real
    {
      int arg_1 = 1;
      real arg_2 = (0.94999999999999996 + 0.0625 * seed);
      real value = fdim(arg_1, arg_2);
      total += 1.1875 * value;
    }
    // fdim(matrix,int)=>matrix
    {
      matrix[1, 1] arg_1 = [[(0.94999999999999996 + 0.0625 * seed)]];
      int arg_2 = 1;
      matrix[1, 1] value = fdim(arg_1, arg_2);
      total += 1.25 * sum(value);
    }
    // fdim(real,array[,,,]row_vector)=>array[,,,]row_vector
    {
      real arg_1 = (0.94999999999999996 + 0.0625 * seed);
      array[1, 1, 1, 1] row_vector[1] arg_2 = {{{{[(0.94999999999999996 + 0.0625 * seed)]}}}};
      array[1, 1, 1, 1] row_vector[1] value = fdim(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // floor(array[]int)=>array[]real
    {
      array[1] int arg_1 = {1};
      array[1] real value = floor(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // fmax(array[,,,,,,]int,int)=>array[,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{{1}}}}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1, 1, 1, 1] real value = fmax(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmax(array[,]matrix,array[,]matrix)=>array[,]matrix
    {
      array[1, 1] matrix[1, 1] arg_1 = {{[[(0.94999999999999996 + 0.0625 * seed)]]}};
      array[1, 1] matrix[1, 1] arg_2 = {{[[(0.94999999999999996 + 0.0625 * seed)]]}};
      array[1, 1] matrix[1, 1] value = fmax(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmax(int,array[,,,]matrix)=>array[,,,]matrix
    {
      int arg_1 = 1;
      array[1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{[[(0.94999999999999996 + 0.0625 * seed)]]}}}};
      array[1, 1, 1, 1] matrix[1, 1] value = fmax(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmax(int,array[,,,]real)=>array[,,,]real
    {
      int arg_1 = 1;
      array[1, 1, 1, 1] real arg_2 = {{{{(0.94999999999999996 + 0.0625 * seed)}}}};
      array[1, 1, 1, 1] real value = fmax(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmax(real,array[,,,]vector)=>array[,,,]vector
    {
      real arg_1 = (0.94999999999999996 + 0.0625 * seed);
      array[1, 1, 1, 1] vector[1] arg_2 = {{{{[(0.94999999999999996 + 0.0625 * seed)]'}}}};
      array[1, 1, 1, 1] vector[1] value = fmax(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmin(array[,,,,,]int,real)=>array[,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{1}}}}}};
      real arg_2 = (0.94999999999999996 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1] real value = fmin(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmin(array[,,]int,array[,,]int)=>array[,,]real
    {
      array[1, 1, 1] int arg_1 = {{{1}}};
      array[1, 1, 1] int arg_2 = {{{1}}};
      array[1, 1, 1] real value = fmin(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmin(array[,,]vector,int)=>array[,,]vector
    {
      array[1, 1, 1] vector[1] arg_1 = {{{[(0.94999999999999996 + 0.0625 * seed)]'}}};
      int arg_2 = 1;
      array[1, 1, 1] vector[1] value = fmin(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmin(array[,,]vector,real)=>array[,,]vector
    {
      array[1, 1, 1] vector[1] arg_1 = {{{[(0.94999999999999996 + 0.0625 * seed)]'}}};
      real arg_2 = (0.94999999999999996 + 0.0625 * seed);
      array[1, 1, 1] vector[1] value = fmin(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmin(array[,]matrix,int)=>array[,]matrix
    {
      array[1, 1] matrix[1, 1] arg_1 = {{[[(0.94999999999999996 + 0.0625 * seed)]]}};
      int arg_2 = 1;
      array[1, 1] matrix[1, 1] value = fmin(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmin(int,array[,,,,,,]row_vector)=>array[,,,,,,]row_vector
    {
      int arg_1 = 1;
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] arg_2 = {{{{{{{[(0.94999999999999996 + 0.0625 * seed)]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] value = fmin(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmin(int,array[,,]matrix)=>array[,,]matrix
    {
      int arg_1 = 1;
      array[1, 1, 1] matrix[1, 1] arg_2 = {{{[[(0.94999999999999996 + 0.0625 * seed)]]}}};
      array[1, 1, 1] matrix[1, 1] value = fmin(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmin(int,array[,]real)=>array[,]real
    {
      int arg_1 = 1;
      array[1, 1] real arg_2 = {{(0.94999999999999996 + 0.0625 * seed)}};
      array[1, 1] real value = fmin(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmin(int,array[]matrix)=>array[]matrix
    {
      int arg_1 = 1;
      array[1] matrix[1, 1] arg_2 = {[[(0.94999999999999996 + 0.0625 * seed)]]};
      array[1] matrix[1, 1] value = fmin(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmin(real,array[,,,]real)=>array[,,,]real
    {
      real arg_1 = (0.94999999999999996 + 0.0625 * seed);
      array[1, 1, 1, 1] real arg_2 = {{{{(0.94999999999999996 + 0.0625 * seed)}}}};
      array[1, 1, 1, 1] real value = fmin(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmod(array[,,,,,]real,array[,,,,,]real)=>array[,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{(2.4500000000000002 + 0.0625 * seed)}}}}}};
      array[1, 1, 1, 1, 1, 1] real arg_2 = {{{{{{(0.94999999999999996 + 0.0625 * seed)}}}}}};
      array[1, 1, 1, 1, 1, 1] real value = fmod(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmod(array[,,,]real,array[,,,]real)=>array[,,,]real
    {
      array[1, 1, 1, 1] real arg_1 = {{{{(2.4500000000000002 + 0.0625 * seed)}}}};
      array[1, 1, 1, 1] real arg_2 = {{{{(0.94999999999999996 + 0.0625 * seed)}}}};
      array[1, 1, 1, 1] real value = fmod(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmod(array[,,,]row_vector,int)=>array[,,,]row_vector
    {
      array[1, 1, 1, 1] row_vector[1] arg_1 = {{{{[(2.4500000000000002 + 0.0625 * seed)]}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1] row_vector[1] value = fmod(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmod(int,array[,,,,,,,]real)=>array[,,,,,,,]real
    {
      int arg_1 = 2;
      array[1, 1, 1, 1, 1, 1, 1, 1] real arg_2 = {{{{{{{{(0.94999999999999996 + 0.0625 * seed)}}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1, 1] real value = fmod(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmod(int,array[,,,]vector)=>array[,,,]vector
    {
      int arg_1 = 2;
      array[1, 1, 1, 1] vector[1] arg_2 = {{{{[(0.94999999999999996 + 0.0625 * seed)]'}}}};
      array[1, 1, 1, 1] vector[1] value = fmod(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmod(real,array[,,]real)=>array[,,]real
    {
      real arg_1 = (2.4500000000000002 + 0.0625 * seed);
      array[1, 1, 1] real arg_2 = {{{(0.94999999999999996 + 0.0625 * seed)}}};
      array[1, 1, 1] real value = fmod(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmod(real,array[,,]row_vector)=>array[,,]row_vector
    {
      real arg_1 = (2.4500000000000002 + 0.0625 * seed);
      array[1, 1, 1] row_vector[1] arg_2 = {{{[(0.94999999999999996 + 0.0625 * seed)]}}};
      array[1, 1, 1] row_vector[1] value = fmod(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmod(real,int)=>real
    {
      real arg_1 = (2.4500000000000002 + 0.0625 * seed);
      int arg_2 = 1;
      real value = fmod(arg_1, arg_2);
      total += 1.234375 * value;
    }
    // gamma_q(real,array[,]matrix)=>array[,]matrix
    {
      real arg_1 = (1.95 + 0.0625 * seed);
      array[1, 1] matrix[1, 1] arg_2 = {{[[(1.25 + 0.0625 * seed)]]}};
      array[1, 1] matrix[1, 1] value = gamma_q(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // gamma_q(real,vector)=>vector
    {
      real arg_1 = (1.95 + 0.0625 * seed);
      vector[1] arg_2 = [(1.25 + 0.0625 * seed)]';
      vector[1] value = gamma_q(arg_1, arg_2);
      total += 1.0625 * sum(value);
    }
    // hypot(array[,,,,,,]row_vector,real)=>array[,,,,,,]row_vector
    {
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{{{[(0.45000000000000001 + 0.0625 * seed)]}}}}}}};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] value = hypot(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // hypot(array[,,,,,,]vector,int)=>array[,,,,,,]vector
    {
      array[1, 1, 1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1, 1, 1, 1] vector[1] value = hypot(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // hypot(array[,,,,,]vector,real)=>array[,,,,,]vector
    {
      array[1, 1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}}}};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1] vector[1] value = hypot(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // hypot(array[,,,,]row_vector,real)=>array[,,,,]row_vector
    {
      array[1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{[(0.45000000000000001 + 0.0625 * seed)]}}}}};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1, 1, 1, 1, 1] row_vector[1] value = hypot(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // hypot(int,array[,,,,,,,]real)=>array[,,,,,,,]real
    {
      int arg_1 = 0;
      array[1, 1, 1, 1, 1, 1, 1, 1] real arg_2 = {{{{{{{{(1.2 + 0.0625 * seed)}}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1, 1] real value = hypot(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // inv(row_vector)=>row_vector
    {
      row_vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)];
      row_vector[1] value = inv(arg_1);
      total += 1.09375 * sum(value);
    }
    // inv_Phi(array[,,,,,,]int)=>array[,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{{0}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] real value = inv_Phi(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // inv_Phi(array[,,,,]row_vector)=>array[,,,,]row_vector
    {
      array[1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{[(0.45000000000000001 + 0.0625 * seed)]}}}}};
      array[1, 1, 1, 1, 1] row_vector[1] value = inv_Phi(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // inv_Phi(array[,,]matrix)=>array[,,]matrix
    {
      array[1, 1, 1] matrix[1, 1] arg_1 = {{{[[(0.45000000000000001 + 0.0625 * seed)]]}}};
      array[1, 1, 1] matrix[1, 1] value = inv_Phi(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // inv_cloglog(array[,,]vector)=>array[,,]vector
    {
      array[1, 1, 1] vector[1] arg_1 = {{{[(0.45000000000000001 + 0.0625 * seed)]'}}};
      array[1, 1, 1] vector[1] value = inv_cloglog(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // inv_cloglog(array[,]real)=>array[,]real
    {
      array[1, 1] real arg_1 = {{(0.45000000000000001 + 0.0625 * seed)}};
      array[1, 1] real value = inv_cloglog(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // inv_erfc(array[,,,,,]real)=>array[,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{(0.45000000000000001 + 0.0625 * seed)}}}}}};
      array[1, 1, 1, 1, 1, 1] real value = inv_erfc(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // inv_logit(array[,,,,,]row_vector)=>array[,,,,,]row_vector
    {
      array[1, 1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{{[(0.45000000000000001 + 0.0625 * seed)]}}}}}};
      array[1, 1, 1, 1, 1, 1] row_vector[1] value = inv_logit(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // inv_logit(array[,,,]int)=>array[,,,]real
    {
      array[1, 1, 1, 1] int arg_1 = {{{{1}}}};
      array[1, 1, 1, 1] real value = inv_logit(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // inv_sqrt(array[,,,,,,]vector)=>array[,,,,,,]vector
    {
      array[1, 1, 1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{{{[(1.3499999999999999 + 0.0625 * seed)]'}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] vector[1] value = inv_sqrt(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // inv_sqrt(array[,,,,]real)=>array[,,,,]real
    {
      array[1, 1, 1, 1, 1] real arg_1 = {{{{{(1.3499999999999999 + 0.0625 * seed)}}}}};
      array[1, 1, 1, 1, 1] real value = inv_sqrt(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // inv_square(array[,,]real)=>array[,,]real
    {
      array[1, 1, 1] real arg_1 = {{{(0.45000000000000001 + 0.0625 * seed)}}};
      array[1, 1, 1] real value = inv_square(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // inv_square(array[]real)=>array[]real
    {
      array[1] real arg_1 = {(0.45000000000000001 + 0.0625 * seed)};
      array[1] real value = inv_square(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // lambert_w0(array[,,,,]real)=>array[,,,,]real
    {
      array[1, 1, 1, 1, 1] real arg_1 = {{{{{(0.45000000000000001 + 0.0625 * seed)}}}}};
      array[1, 1, 1, 1, 1] real value = lambert_w0(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // lambert_w0(array[,,,]row_vector)=>array[,,,]row_vector
    {
      array[1, 1, 1, 1] row_vector[1] arg_1 = {{{{[(0.45000000000000001 + 0.0625 * seed)]}}}};
      array[1, 1, 1, 1] row_vector[1] value = lambert_w0(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // lambert_w0(array[,,]int)=>array[,,]real
    {
      array[1, 1, 1] int arg_1 = {{{1}}};
      array[1, 1, 1] real value = lambert_w0(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // lambert_w0(array[]matrix)=>array[]matrix
    {
      array[1] matrix[1, 1] arg_1 = {[[(0.45000000000000001 + 0.0625 * seed)]]};
      array[1] matrix[1, 1] value = lambert_w0(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // lambert_wm1(array[,]vector)=>array[,]vector
    {
      array[1, 1] vector[1] arg_1 = {{[(-0.25 + 0.0625 * seed)]'}};
      array[1, 1] vector[1] value = lambert_wm1(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // lbeta(array[,,,,,,]vector,real)=>array[,,,,,,]vector
    {
      array[1, 1, 1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{{{[(1.95 + 0.0625 * seed)]'}}}}}}};
      real arg_2 = (2.9500000000000002 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1, 1] vector[1] value = lbeta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lbeta(array[,,,]real,array[,,,]real)=>array[,,,]real
    {
      array[1, 1, 1, 1] real arg_1 = {{{{(1.95 + 0.0625 * seed)}}}};
      array[1, 1, 1, 1] real arg_2 = {{{{(2.9500000000000002 + 0.0625 * seed)}}}};
      array[1, 1, 1, 1] real value = lbeta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lbeta(int,array[,,,,,,,]real)=>array[,,,,,,,]real
    {
      int arg_1 = 2;
      array[1, 1, 1, 1, 1, 1, 1, 1] real arg_2 = {{{{{{{{(2.9500000000000002 + 0.0625 * seed)}}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1, 1] real value = lbeta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lbeta(real,array[,,,]real)=>array[,,,]real
    {
      real arg_1 = (1.95 + 0.0625 * seed);
      array[1, 1, 1, 1] real arg_2 = {{{{(2.9500000000000002 + 0.0625 * seed)}}}};
      array[1, 1, 1, 1] real value = lbeta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lbeta(real,array[,,]matrix)=>array[,,]matrix
    {
      real arg_1 = (1.95 + 0.0625 * seed);
      array[1, 1, 1] matrix[1, 1] arg_2 = {{{[[(2.9500000000000002 + 0.0625 * seed)]]}}};
      array[1, 1, 1] matrix[1, 1] value = lbeta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lbeta(real,array[,,]row_vector)=>array[,,]row_vector
    {
      real arg_1 = (1.95 + 0.0625 * seed);
      array[1, 1, 1] row_vector[1] arg_2 = {{{[(2.9500000000000002 + 0.0625 * seed)]}}};
      array[1, 1, 1] row_vector[1] value = lbeta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lchoose(array[,,,,,,]real,real)=>array[,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{{(3.9500000000000002 + 0.0625 * seed)}}}}}}};
      real arg_2 = (1.95 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1, 1] real value = lchoose(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lchoose(array[,,,,]matrix,array[,,,,]matrix)=>array[,,,,]matrix
    {
      array[1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{[[(3.9500000000000002 + 0.0625 * seed)]]}}}}};
      array[1, 1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{{[[(1.95 + 0.0625 * seed)]]}}}}};
      array[1, 1, 1, 1, 1] matrix[1, 1] value = lchoose(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lchoose(array[,,,,]vector,int)=>array[,,,,]vector
    {
      array[1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{[(3.9500000000000002 + 0.0625 * seed)]'}}}}};
      int arg_2 = 2;
      array[1, 1, 1, 1, 1] vector[1] value = lchoose(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lchoose(array[]int,real)=>array[]real
    {
      array[1] int arg_1 = {4};
      real arg_2 = (1.95 + 0.0625 * seed);
      array[1] real value = lchoose(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lchoose(int,array[]int)=>array[]real
    {
      int arg_1 = 4;
      array[1] int arg_2 = {2};
      array[1] real value = lchoose(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lchoose(real,array[,,,]int)=>array[,,,]real
    {
      real arg_1 = (3.9500000000000002 + 0.0625 * seed);
      array[1, 1, 1, 1] int arg_2 = {{{{2}}}};
      array[1, 1, 1, 1] real value = lchoose(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lchoose(real,array[,,]matrix)=>array[,,]matrix
    {
      real arg_1 = (3.9500000000000002 + 0.0625 * seed);
      array[1, 1, 1] matrix[1, 1] arg_2 = {{{[[(1.95 + 0.0625 * seed)]]}}};
      array[1, 1, 1] matrix[1, 1] value = lchoose(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lchoose(real,array[]int)=>array[]real
    {
      real arg_1 = (3.9500000000000002 + 0.0625 * seed);
      array[1] int arg_2 = {2};
      array[1] real value = lchoose(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // ldexp(array[,,,,,,]matrix,int)=>array[,,,,,,]matrix
    {
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}}}}};
      int arg_2 = 2;
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] value = ldexp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // ldexp(array[,,,,]vector,array[,,,,,]int)=>array[,,,,]vector
    {
      array[1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}}};
      array[1, 1, 1, 1, 1, 1] int arg_2 = {{{{{{2}}}}}};
      array[1, 1, 1, 1, 1] vector[1] value = ldexp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lgamma(array[,,,,,,]int)=>array[,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{{1}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] real value = lgamma(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // lgamma(array[,,,,,,]real)=>array[,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{{(1.3499999999999999 + 0.0625 * seed)}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] real value = lgamma(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // lmgamma(array[,]int,array[]vector)=>array[]vector
    {
      array[1, 1] int arg_1 = {{2}};
      array[1] vector[1] arg_2 = {[(1.95 + 0.0625 * seed)]'};
      array[1] vector[1] value = lmgamma(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lmgamma(array[,]int,matrix)=>matrix
    {
      array[1, 1] int arg_1 = {{2}};
      matrix[1, 1] arg_2 = [[(1.95 + 0.0625 * seed)]];
      matrix[1, 1] value = lmgamma(arg_1, arg_2);
      total += 1.25 * sum(value);
    }
    // lmgamma(array[]int,vector)=>vector
    {
      array[1] int arg_1 = {2};
      vector[1] arg_2 = [(1.95 + 0.0625 * seed)]';
      vector[1] value = lmgamma(arg_1, arg_2);
      total += 1 * sum(value);
    }
    // lmgamma(int,array[,]matrix)=>array[,]matrix
    {
      int arg_1 = 2;
      array[1, 1] matrix[1, 1] arg_2 = {{[[(1.95 + 0.0625 * seed)]]}};
      array[1, 1] matrix[1, 1] value = lmgamma(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lmultiply(array[,,,,,,]row_vector,real)=>array[,,,,,,]row_vector
    {
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{{{[(0.45000000000000001 + 0.0625 * seed)]}}}}}}};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] value = lmultiply(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lmultiply(array[]matrix,int)=>array[]matrix
    {
      array[1] matrix[1, 1] arg_1 = {[[(0.45000000000000001 + 0.0625 * seed)]]};
      int arg_2 = 1;
      array[1] matrix[1, 1] value = lmultiply(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lmultiply(int,array[,,,,,,,]real)=>array[,,,,,,,]real
    {
      int arg_1 = 0;
      array[1, 1, 1, 1, 1, 1, 1, 1] real arg_2 = {{{{{{{{(1.2 + 0.0625 * seed)}}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1, 1] real value = lmultiply(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lmultiply(int,array[,,,,,,]matrix)=>array[,,,,,,]matrix
    {
      int arg_1 = 0;
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{{{{[[(1.2 + 0.0625 * seed)]]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] value = lmultiply(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lmultiply(int,array[]vector)=>array[]vector
    {
      int arg_1 = 0;
      array[1] vector[1] arg_2 = {[(1.2 + 0.0625 * seed)]'};
      array[1] vector[1] value = lmultiply(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lmultiply(matrix,int)=>matrix
    {
      matrix[1, 1] arg_1 = [[(0.45000000000000001 + 0.0625 * seed)]];
      int arg_2 = 1;
      matrix[1, 1] value = lmultiply(arg_1, arg_2);
      total += 1 * sum(value);
    }
    // log(array[,,,,]matrix)=>array[,,,,]matrix
    {
      array[1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{[[(1.3499999999999999 + 0.0625 * seed)]]}}}}};
      array[1, 1, 1, 1, 1] matrix[1, 1] value = log(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log10(array[,,,,]matrix)=>array[,,,,]matrix
    {
      array[1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{[[(1.3499999999999999 + 0.0625 * seed)]]}}}}};
      array[1, 1, 1, 1, 1] matrix[1, 1] value = log10(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log10(array[,,,]matrix)=>array[,,,]matrix
    {
      array[1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{[[(1.3499999999999999 + 0.0625 * seed)]]}}}};
      array[1, 1, 1, 1] matrix[1, 1] value = log10(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log1m(array[,,,,]int)=>array[,,,,]real
    {
      array[1, 1, 1, 1, 1] int arg_1 = {{{{{0}}}}};
      array[1, 1, 1, 1, 1] real value = log1m(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log1m(array[,,]real)=>array[,,]real
    {
      array[1, 1, 1] real arg_1 = {{{(0.29999999999999999 + 0.0625 * seed)}}};
      array[1, 1, 1] real value = log1m(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log1m_exp(array[,,,,]matrix)=>array[,,,,]matrix
    {
      array[1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{[[(-0.55000000000000004 + 0.0625 * seed)]]}}}}};
      array[1, 1, 1, 1, 1] matrix[1, 1] value = log1m_exp(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log1m_exp(array[,]vector)=>array[,]vector
    {
      array[1, 1] vector[1] arg_1 = {{[(-0.55000000000000004 + 0.0625 * seed)]'}};
      array[1, 1] vector[1] value = log1m_exp(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log1m_exp(row_vector)=>row_vector
    {
      row_vector[1] arg_1 = [(-0.55000000000000004 + 0.0625 * seed)];
      row_vector[1] value = log1m_exp(arg_1);
      total += 1.015625 * sum(value);
    }
    // log1p(array[,,,,]vector)=>array[,,,,]vector
    {
      array[1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}}};
      array[1, 1, 1, 1, 1] vector[1] value = log1p(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log1p(array[,,]vector)=>array[,,]vector
    {
      array[1, 1, 1] vector[1] arg_1 = {{{[(0.45000000000000001 + 0.0625 * seed)]'}}};
      array[1, 1, 1] vector[1] value = log1p(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log_diff_exp(array[,,,]row_vector,array[,,,]row_vector)=>array[,,,]row_vector
    {
      array[1, 1, 1, 1] row_vector[1] arg_1 = {{{{[(1.45 + 0.0625 * seed)]}}}};
      array[1, 1, 1, 1] row_vector[1] arg_2 = {{{{[(0.45000000000000001 + 0.0625 * seed)]}}}};
      array[1, 1, 1, 1] row_vector[1] value = log_diff_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_diff_exp(array[,]row_vector,array[,]row_vector)=>array[,]row_vector
    {
      array[1, 1] row_vector[1] arg_1 = {{[(1.45 + 0.0625 * seed)]}};
      array[1, 1] row_vector[1] arg_2 = {{[(0.45000000000000001 + 0.0625 * seed)]}};
      array[1, 1] row_vector[1] value = log_diff_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_diff_exp(array[,]vector,real)=>array[,]vector
    {
      array[1, 1] vector[1] arg_1 = {{[(1.45 + 0.0625 * seed)]'}};
      real arg_2 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1] vector[1] value = log_diff_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_diff_exp(array[]matrix,real)=>array[]matrix
    {
      array[1] matrix[1, 1] arg_1 = {[[(1.45 + 0.0625 * seed)]]};
      real arg_2 = (0.45000000000000001 + 0.0625 * seed);
      array[1] matrix[1, 1] value = log_diff_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_diff_exp(array[]real,int)=>array[]real
    {
      array[1] real arg_1 = {(1.45 + 0.0625 * seed)};
      int arg_2 = 0;
      array[1] real value = log_diff_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_diff_exp(array[]vector,array[]vector)=>array[]vector
    {
      array[1] vector[1] arg_1 = {[(1.45 + 0.0625 * seed)]'};
      array[1] vector[1] arg_2 = {[(0.45000000000000001 + 0.0625 * seed)]'};
      array[1] vector[1] value = log_diff_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_diff_exp(int,array[,,,,,,]int)=>array[,,,,,,]real
    {
      int arg_1 = 1;
      array[1, 1, 1, 1, 1, 1, 1] int arg_2 = {{{{{{{0}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] real value = log_diff_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_diff_exp(int,array[,,,,,,]row_vector)=>array[,,,,,,]row_vector
    {
      int arg_1 = 1;
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] arg_2 = {{{{{{{[(0.45000000000000001 + 0.0625 * seed)]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] value = log_diff_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_diff_exp(int,array[,,,,,]int)=>array[,,,,,]real
    {
      int arg_1 = 1;
      array[1, 1, 1, 1, 1, 1] int arg_2 = {{{{{{0}}}}}};
      array[1, 1, 1, 1, 1, 1] real value = log_diff_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_diff_exp(real,array[,,]int)=>array[,,]real
    {
      real arg_1 = (1.45 + 0.0625 * seed);
      array[1, 1, 1] int arg_2 = {{{0}}};
      array[1, 1, 1] real value = log_diff_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_diff_exp(vector,real)=>vector
    {
      vector[1] arg_1 = [(1.45 + 0.0625 * seed)]';
      real arg_2 = (0.45000000000000001 + 0.0625 * seed);
      vector[1] value = log_diff_exp(arg_1, arg_2);
      total += 1.09375 * sum(value);
    }
    // log_falling_factorial(array[,,,,,,]real,int)=>array[,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{{(3.4500000000000002 + 0.0625 * seed)}}}}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1, 1, 1, 1] real value = log_falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_falling_factorial(array[,,,,,]row_vector,array[,,,,,]row_vector)=>array[,,,,,]row_vector
    {
      array[1, 1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{{[(3.4500000000000002 + 0.0625 * seed)]}}}}}};
      array[1, 1, 1, 1, 1, 1] row_vector[1] arg_2 = {{{{{{[(1.1499999999999999 + 0.0625 * seed)]}}}}}};
      array[1, 1, 1, 1, 1, 1] row_vector[1] value = log_falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_falling_factorial(array[,,,]row_vector,real)=>array[,,,]row_vector
    {
      array[1, 1, 1, 1] row_vector[1] arg_1 = {{{{[(3.4500000000000002 + 0.0625 * seed)]}}}};
      real arg_2 = (1.1499999999999999 + 0.0625 * seed);
      array[1, 1, 1, 1] row_vector[1] value = log_falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_falling_factorial(array[,,]matrix,int)=>array[,,]matrix
    {
      array[1, 1, 1] matrix[1, 1] arg_1 = {{{[[(3.4500000000000002 + 0.0625 * seed)]]}}};
      int arg_2 = 1;
      array[1, 1, 1] matrix[1, 1] value = log_falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_falling_factorial(array[,,]real,int)=>array[,,]real
    {
      array[1, 1, 1] real arg_1 = {{{(3.4500000000000002 + 0.0625 * seed)}}};
      int arg_2 = 1;
      array[1, 1, 1] real value = log_falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_falling_factorial(array[]int,array[]int)=>array[]real
    {
      array[1] int arg_1 = {3};
      array[1] int arg_2 = {1};
      array[1] real value = log_falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_falling_factorial(int,array[,,,,,,,]real)=>array[,,,,,,,]real
    {
      int arg_1 = 3;
      array[1, 1, 1, 1, 1, 1, 1, 1] real arg_2 = {{{{{{{{(1.1499999999999999 + 0.0625 * seed)}}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1, 1] real value = log_falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_falling_factorial(int,array[,,,]matrix)=>array[,,,]matrix
    {
      int arg_1 = 3;
      array[1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{[[(1.1499999999999999 + 0.0625 * seed)]]}}}};
      array[1, 1, 1, 1] matrix[1, 1] value = log_falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_falling_factorial(int,array[,,,]vector)=>array[,,,]vector
    {
      int arg_1 = 3;
      array[1, 1, 1, 1] vector[1] arg_2 = {{{{[(1.1499999999999999 + 0.0625 * seed)]'}}}};
      array[1, 1, 1, 1] vector[1] value = log_falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_falling_factorial(real,array[,,,,,]vector)=>array[,,,,,]vector
    {
      real arg_1 = (3.4500000000000002 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1] vector[1] arg_2 = {{{{{{[(1.1499999999999999 + 0.0625 * seed)]'}}}}}};
      array[1, 1, 1, 1, 1, 1] vector[1] value = log_falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_falling_factorial(real,array[,,,,]real)=>array[,,,,]real
    {
      real arg_1 = (3.4500000000000002 + 0.0625 * seed);
      array[1, 1, 1, 1, 1] real arg_2 = {{{{{(1.1499999999999999 + 0.0625 * seed)}}}}};
      array[1, 1, 1, 1, 1] real value = log_falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_falling_factorial(real,array[,,,]matrix)=>array[,,,]matrix
    {
      real arg_1 = (3.4500000000000002 + 0.0625 * seed);
      array[1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{[[(1.1499999999999999 + 0.0625 * seed)]]}}}};
      array[1, 1, 1, 1] matrix[1, 1] value = log_falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_inv_logit(array[,,,]matrix)=>array[,,,]matrix
    {
      array[1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}};
      array[1, 1, 1, 1] matrix[1, 1] value = log_inv_logit(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log_inv_logit_diff(array[,,,,,,]row_vector,int)=>array[,,,,,,]row_vector
    {
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{{{[(0.94999999999999996 + 0.0625 * seed)]}}}}}}};
      int arg_2 = 0;
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] value = log_inv_logit_diff(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_inv_logit_diff(array[,,,]int,real)=>array[,,,]real
    {
      array[1, 1, 1, 1] int arg_1 = {{{{1}}}};
      real arg_2 = (-0.55000000000000004 + 0.0625 * seed);
      array[1, 1, 1, 1] real value = log_inv_logit_diff(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_inv_logit_diff(real,array[,,,]int)=>array[,,,]real
    {
      real arg_1 = (0.94999999999999996 + 0.0625 * seed);
      array[1, 1, 1, 1] int arg_2 = {{{{0}}}};
      array[1, 1, 1, 1] real value = log_inv_logit_diff(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_inv_logit_diff(real,array[,,,]vector)=>array[,,,]vector
    {
      real arg_1 = (0.94999999999999996 + 0.0625 * seed);
      array[1, 1, 1, 1] vector[1] arg_2 = {{{{[(-0.55000000000000004 + 0.0625 * seed)]'}}}};
      array[1, 1, 1, 1] vector[1] value = log_inv_logit_diff(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_inv_logit_diff(real,real)=>real
    {
      real arg_1 = (0.94999999999999996 + 0.0625 * seed);
      real arg_2 = (-0.55000000000000004 + 0.0625 * seed);
      real value = log_inv_logit_diff(arg_1, arg_2);
      total += 1.25 * value;
    }
    // log_modified_bessel_first_kind(array[,,,,,,,]int,real)=>array[,,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{{{0}}}}}}}};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1, 1, 1] real value = log_modified_bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_modified_bessel_first_kind(array[,,,,]real,array[,,,,]real)=>array[,,,,]real
    {
      array[1, 1, 1, 1, 1] real arg_1 = {{{{{(0.45000000000000001 + 0.0625 * seed)}}}}};
      array[1, 1, 1, 1, 1] real arg_2 = {{{{{(1.2 + 0.0625 * seed)}}}}};
      array[1, 1, 1, 1, 1] real value = log_modified_bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_modified_bessel_first_kind(array[,,,]row_vector,array[,,,]row_vector)=>array[,,,]row_vector
    {
      array[1, 1, 1, 1] row_vector[1] arg_1 = {{{{[(0.45000000000000001 + 0.0625 * seed)]}}}};
      array[1, 1, 1, 1] row_vector[1] arg_2 = {{{{[(1.2 + 0.0625 * seed)]}}}};
      array[1, 1, 1, 1] row_vector[1] value = log_modified_bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_modified_bessel_first_kind(array[,]int,array[,]int)=>array[,]real
    {
      array[1, 1] int arg_1 = {{0}};
      array[1, 1] int arg_2 = {{1}};
      array[1, 1] real value = log_modified_bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_modified_bessel_first_kind(int,array[,,,]row_vector)=>array[,,,]row_vector
    {
      int arg_1 = 0;
      array[1, 1, 1, 1] row_vector[1] arg_2 = {{{{[(1.2 + 0.0625 * seed)]}}}};
      array[1, 1, 1, 1] row_vector[1] value = log_modified_bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_modified_bessel_first_kind(int,real)=>real
    {
      int arg_1 = 0;
      real arg_2 = (1.2 + 0.0625 * seed);
      real value = log_modified_bessel_first_kind(arg_1, arg_2);
      total += 1.109375 * value;
    }
    // log_modified_bessel_first_kind(real,array[,,,,,]vector)=>array[,,,,,]vector
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1] vector[1] arg_2 = {{{{{{[(1.2 + 0.0625 * seed)]'}}}}}};
      array[1, 1, 1, 1, 1, 1] vector[1] value = log_modified_bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_rising_factorial(array[,,,,,]int,real)=>array[,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{1}}}}}};
      real arg_2 = (1.1499999999999999 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1] real value = log_rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_rising_factorial(array[,,]int,array[,,]int)=>array[,,]real
    {
      array[1, 1, 1] int arg_1 = {{{1}}};
      array[1, 1, 1] int arg_2 = {{{1}}};
      array[1, 1, 1] real value = log_rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_rising_factorial(array[]row_vector,int)=>array[]row_vector
    {
      array[1] row_vector[1] arg_1 = {[(1.45 + 0.0625 * seed)]};
      int arg_2 = 1;
      array[1] row_vector[1] value = log_rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_rising_factorial(int,array[,,,]int)=>array[,,,]real
    {
      int arg_1 = 1;
      array[1, 1, 1, 1] int arg_2 = {{{{1}}}};
      array[1, 1, 1, 1] real value = log_rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_rising_factorial(int,array[,,]real)=>array[,,]real
    {
      int arg_1 = 1;
      array[1, 1, 1] real arg_2 = {{{(1.1499999999999999 + 0.0625 * seed)}}};
      array[1, 1, 1] real value = log_rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_rising_factorial(int,array[,,]row_vector)=>array[,,]row_vector
    {
      int arg_1 = 1;
      array[1, 1, 1] row_vector[1] arg_2 = {{{[(1.1499999999999999 + 0.0625 * seed)]}}};
      array[1, 1, 1] row_vector[1] value = log_rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_rising_factorial(real,array[,,]int)=>array[,,]real
    {
      real arg_1 = (1.45 + 0.0625 * seed);
      array[1, 1, 1] int arg_2 = {{{1}}};
      array[1, 1, 1] real value = log_rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_sum_exp(array[,,,,,,]int,int)=>array[,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{{0}}}}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1, 1, 1, 1] real value = log_sum_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_sum_exp(array[,,,,]real,array[,,,,]real)=>array[,,,,]real
    {
      array[1, 1, 1, 1, 1] real arg_1 = {{{{{(0.45000000000000001 + 0.0625 * seed)}}}}};
      array[1, 1, 1, 1, 1] real arg_2 = {{{{{(1.2 + 0.0625 * seed)}}}}};
      array[1, 1, 1, 1, 1] real value = log_sum_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_sum_exp(array[,]vector,array[,]vector)=>array[,]vector
    {
      array[1, 1] vector[1] arg_1 = {{[(0.45000000000000001 + 0.0625 * seed)]'}};
      array[1, 1] vector[1] arg_2 = {{[(1.2 + 0.0625 * seed)]'}};
      array[1, 1] vector[1] value = log_sum_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_sum_exp(vector)=>real
    {
      vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)]';
      real value = log_sum_exp(arg_1);
      total += 1.078125 * value;
    }
    // logit(array[,,,,,]int)=>array[,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{0}}}}}};
      array[1, 1, 1, 1, 1, 1] real value = logit(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // logit(row_vector)=>row_vector
    {
      row_vector[1] arg_1 = [(0.29999999999999999 + 0.0625 * seed)];
      row_vector[1] value = logit(arg_1);
      total += 1.1875 * sum(value);
    }
    // modified_bessel_first_kind(array[,,]int,real)=>array[,,]real
    {
      array[1, 1, 1] int arg_1 = {{{2}}};
      real arg_2 = (1.3499999999999999 + 0.0625 * seed);
      array[1, 1, 1] real value = modified_bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // modified_bessel_second_kind(array[,,,,,,]int,real)=>array[,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{{2}}}}}}};
      real arg_2 = (1.3499999999999999 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1, 1] real value = modified_bessel_second_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // modified_bessel_second_kind(int,array[,,]vector)=>array[,,]vector
    {
      int arg_1 = 2;
      array[1, 1, 1] vector[1] arg_2 = {{{[(1.3499999999999999 + 0.0625 * seed)]'}}};
      array[1, 1, 1] vector[1] value = modified_bessel_second_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // num_elements(array[,,,,,,,]row_vector)=>int
    {
      array[1, 1, 1, 1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{{{{[(0.45000000000000001 + 0.0625 * seed)]}}}}}}}};
      int value = num_elements(arg_1);
      total += 1.015625 * value;
    }
    // num_elements(array[,,,,,,,]vector)=>int
    {
      array[1, 1, 1, 1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}}}}}};
      int value = num_elements(arg_1);
      total += 1.125 * value;
    }
    // num_elements(array[,,]vector)=>int
    {
      array[1, 1, 1] vector[1] arg_1 = {{{[(0.45000000000000001 + 0.0625 * seed)]'}}};
      int value = num_elements(arg_1);
      total += 1.203125 * value;
    }
    // num_elements(row_vector)=>int
    {
      row_vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)];
      int value = num_elements(arg_1);
      total += 1.1875 * value;
    }
    // num_elements(vector)=>int
    {
      vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)]';
      int value = num_elements(arg_1);
      total += 1.03125 * value;
    }
    // one_hot_array(int,int)=>array[]real
    {
      array[1] real value = one_hot_array(1, 1);
      if (seed > 1e100)
        print(value);
    }
    // ones_row_vector(int)=>row_vector
    {
      row_vector[1] value = ones_row_vector(1);
      total += 1 * sum(value);
    }
    // owens_t(array[,,,,,,]matrix,real)=>array[,,,,,,]matrix
    {
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}}}}};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] value = owens_t(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // owens_t(real,array[,,,,,]vector)=>array[,,,,,]vector
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1] vector[1] arg_2 = {{{{{{[(1.2 + 0.0625 * seed)]'}}}}}};
      array[1, 1, 1, 1, 1, 1] vector[1] value = owens_t(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // owens_t(real,array[,,,,]row_vector)=>array[,,,,]row_vector
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1, 1, 1, 1] row_vector[1] arg_2 = {{{{{[(1.2 + 0.0625 * seed)]}}}}};
      array[1, 1, 1, 1, 1] row_vector[1] value = owens_t(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // owens_t(real,array[,,]vector)=>array[,,]vector
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1, 1] vector[1] arg_2 = {{{[(1.2 + 0.0625 * seed)]'}}};
      array[1, 1, 1] vector[1] value = owens_t(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // pow(array[,,,,,,,]int,int)=>array[,,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{{{0}}}}}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1, 1, 1, 1, 1] real value = pow(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // pow(array[,,,,,,]int,array[,,,,,,]int)=>array[,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{{0}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] int arg_2 = {{{{{{{1}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] real value = pow(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // pow(array[,,,,,,]vector,int)=>array[,,,,,,]vector
    {
      array[1, 1, 1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1, 1, 1, 1] vector[1] value = pow(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // pow(array[,,,,]int,real)=>array[,,,,]real
    {
      array[1, 1, 1, 1, 1] int arg_1 = {{{{{0}}}}};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1, 1, 1, 1, 1] real value = pow(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // pow(array[,,,,]vector,array[,,,,]vector)=>array[,,,,]vector
    {
      array[1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}}};
      array[1, 1, 1, 1, 1] vector[1] arg_2 = {{{{{[(1.2 + 0.0625 * seed)]'}}}}};
      array[1, 1, 1, 1, 1] vector[1] value = pow(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // pow(real,array[,,,,,]real)=>array[,,,,,]real
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1] real arg_2 = {{{{{{(1.2 + 0.0625 * seed)}}}}}};
      array[1, 1, 1, 1, 1, 1] real value = pow(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // pow(real,array[,]int)=>array[,]real
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1] int arg_2 = {{1}};
      array[1, 1] real value = pow(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // pow(real,array[]row_vector)=>array[]row_vector
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1] row_vector[1] arg_2 = {[(1.2 + 0.0625 * seed)]};
      array[1] row_vector[1] value = pow(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // quad_form_sym(matrix,vector)=>real
    {
      matrix[1, 1] arg_1 = [[(0.45000000000000001 + 0.0625 * seed)]];
      vector[1] arg_2 = [(1.2 + 0.0625 * seed)]';
      real value = quad_form_sym(arg_1, arg_2);
      total += 1 * value;
    }
    // rising_factorial(array[,,,,,,]row_vector,array[,,,,,,,]int)=>array[,,,,,,]row_vector
    {
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{{{[(1.45 + 0.0625 * seed)]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1, 1] int arg_2 = {{{{{{{{2}}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] value = rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // rising_factorial(array[,,,]vector,int)=>array[,,,]vector
    {
      array[1, 1, 1, 1] vector[1] arg_1 = {{{{[(1.45 + 0.0625 * seed)]'}}}};
      int arg_2 = 2;
      array[1, 1, 1, 1] vector[1] value = rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // sin(array[,,,,,,]matrix)=>array[,,,,,,]matrix
    {
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] value = sin(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // sinh(array[,,,,,]real)=>array[,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{(0.45000000000000001 + 0.0625 * seed)}}}}}};
      array[1, 1, 1, 1, 1, 1] real value = sinh(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // size(array[,,,,,,]real)=>int
    {
      array[1, 1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{{(0.45000000000000001 + 0.0625 * seed)}}}}}}};
      int value = size(arg_1);
      total += 1.234375 * value;
    }
    // size(array[,,,,]int)=>int
    {
      array[1, 1, 1, 1, 1] int arg_1 = {{{{{2}}}}};
      int value = size(arg_1);
      total += 1.046875 * value;
    }
    // size(array[,,]real)=>int
    {
      array[1, 1, 1] real arg_1 = {{{(0.45000000000000001 + 0.0625 * seed)}}};
      int value = size(arg_1);
      total += 1.03125 * value;
    }
    // square(array[,,,,,]vector)=>array[,,,,,]vector
    {
      array[1, 1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}}}};
      array[1, 1, 1, 1, 1, 1] vector[1] value = square(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // std_normal_qf(array[]vector)=>array[]vector
    {
      array[1] vector[1] arg_1 = {[(0.45000000000000001 + 0.0625 * seed)]'};
      array[1] vector[1] value = std_normal_qf(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // step(real)=>real
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      real value = step(arg_1);
      total += 1.03125 * value;
    }
    // tail(array[]matrix,int)=>array[]matrix
    {
      array[1] matrix[1, 1] arg_1 = {[[(0.45000000000000001 + 0.0625 * seed)]]};
      array[1] matrix[1, 1] value = tail(arg_1, 1);
      if (seed > 1e100)
        print(value);
    }
    // tail(row_vector,int)=>row_vector
    {
      row_vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)];
      row_vector[1] value = tail(arg_1, 1);
      total += 1.078125 * sum(value);
    }
    // tanh(array[,,,,,]matrix)=>array[,,,,,]matrix
    {
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}}}};
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] value = tanh(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // tanh(array[,,,]int)=>array[,,,]real
    {
      array[1, 1, 1, 1] int arg_1 = {{{{1}}}};
      array[1, 1, 1, 1] real value = tanh(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // tanh(array[,,,]vector)=>array[,,,]vector
    {
      array[1, 1, 1, 1] vector[1] arg_1 = {{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}};
      array[1, 1, 1, 1] vector[1] value = tanh(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // tgamma(array[,,,,,]matrix)=>array[,,,,,]matrix
    {
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}}}};
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] value = tgamma(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // to_matrix(row_vector)=>matrix
    {
      row_vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)];
      matrix[1, 1] value = to_matrix(arg_1);
      total += 1.1875 * sum(value);
    }
    // trigamma(array[,]matrix)=>array[,]matrix
    {
      array[1, 1] matrix[1, 1] arg_1 = {{[[(1.3499999999999999 + 0.0625 * seed)]]}};
      array[1, 1] matrix[1, 1] value = trigamma(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // trigamma(array[,]row_vector)=>array[,]row_vector
    {
      array[1, 1] row_vector[1] arg_1 = {{[(1.3499999999999999 + 0.0625 * seed)]}};
      array[1, 1] row_vector[1] value = trigamma(arg_1);
      if (seed > 1e100)
        print(value);
    }
    return total;
  }
}
data {
  real context_seed;
}
transformed data {
  real transformed_data_result = builtin_signatures_08(context_seed);
}
parameters {
  real probe;
}
model {
  probe ~ std_normal();
  target += builtin_signatures_08(probe);
  if (probe > -1e100)
    target += builtin_signatures_08(probe);
}
generated quantities {
  real generated_quantities_result = builtin_signatures_08(probe);
}
