// STANLI-LIT: PASS
// STANLI-LIT-EXPECT: OK
// STANLI-LIT-DATA: {"context_seed": 0.0}
// STANLI-LIT-TIMEOUT: 180
// Generated by tools/generate_builtin_signature_models.py from the unified FunctionSpec registry
// and `stanc --dump-stan-math-signatures`. Do not edit by hand.
// Partition 24 of 30; 238 overloads.
functions {
  real builtin_signatures_24(real seed) {
    real total = 0;
    // Phi(array[,,,,]matrix)=>array[,,,,]matrix
    {
      array[1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}}};
      array[1, 1, 1, 1, 1] matrix[1, 1] value = Phi(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // Phi(array[,,]real)=>array[,,]real
    {
      array[1, 1, 1] real arg_1 = {{{(0.45000000000000001 + 0.0625 * seed)}}};
      array[1, 1, 1] real value = Phi(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // Phi_approx(real)=>real
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      real value = Phi_approx(arg_1);
      total += 1.03125 * value;
    }
    // abs(array[,,,]int)=>array[,,,]int
    {
      array[1, 1, 1, 1] int arg_1 = {{{{2}}}};
      array[1, 1, 1, 1] int value = abs(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // abs(array[,]vector)=>array[,]vector
    {
      array[1, 1] vector[1] arg_1 = {{[(0.45000000000000001 + 0.0625 * seed)]'}};
      array[1, 1] vector[1] value = abs(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // abs(vector)=>vector
    {
      vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)]';
      vector[1] value = abs(arg_1);
      total += 1.109375 * sum(value);
    }
    // acos(array[,,,]row_vector)=>array[,,,]row_vector
    {
      array[1, 1, 1, 1] row_vector[1] arg_1 = {{{{[(0.29999999999999999 + 0.0625 * seed)]}}}};
      array[1, 1, 1, 1] row_vector[1] value = acos(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // acosh(array[,,]real)=>array[,,]real
    {
      array[1, 1, 1] real arg_1 = {{{(1.3499999999999999 + 0.0625 * seed)}}};
      array[1, 1, 1] real value = acosh(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // add(real,real)=>real
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      real arg_2 = (1.2 + 0.0625 * seed);
      real value = add(arg_1, arg_2);
      total += 1.109375 * value;
    }
    // asinh(array[,,,,]real)=>array[,,,,]real
    {
      array[1, 1, 1, 1, 1] real arg_1 = {{{{{(0.45000000000000001 + 0.0625 * seed)}}}}};
      array[1, 1, 1, 1, 1] real value = asinh(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // atan2(array[,,,,,,]matrix,real)=>array[,,,,,,]matrix
    {
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}}}}};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] value = atan2(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // atan2(array[,,,,]matrix,real)=>array[,,,,]matrix
    {
      array[1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}}};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1, 1, 1, 1, 1] matrix[1, 1] value = atan2(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // atan2(array[,,,]int,int)=>array[,,,]real
    {
      array[1, 1, 1, 1] int arg_1 = {{{{0}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1] real value = atan2(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // atan2(int,array[,,,,,,]matrix)=>array[,,,,,,]matrix
    {
      int arg_1 = 0;
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{{{{[[(1.2 + 0.0625 * seed)]]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] value = atan2(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // atan2(int,array[,]row_vector)=>array[,]row_vector
    {
      int arg_1 = 0;
      array[1, 1] row_vector[1] arg_2 = {{[(1.2 + 0.0625 * seed)]}};
      array[1, 1] row_vector[1] value = atan2(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // atanh(array[]row_vector)=>array[]row_vector
    {
      array[1] row_vector[1] arg_1 = {[(0.29999999999999999 + 0.0625 * seed)]};
      array[1] row_vector[1] value = atanh(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // bessel_first_kind(int,array[,,,,]real)=>array[,,,,]real
    {
      int arg_1 = 2;
      array[1, 1, 1, 1, 1] real arg_2 = {{{{{(1.3499999999999999 + 0.0625 * seed)}}}}};
      array[1, 1, 1, 1, 1] real value = bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // bessel_first_kind(int,array[]row_vector)=>array[]row_vector
    {
      int arg_1 = 2;
      array[1] row_vector[1] arg_2 = {[(1.3499999999999999 + 0.0625 * seed)]};
      array[1] row_vector[1] value = bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // bessel_second_kind(array[,,,,,,,]int,array[,,,,,]matrix)=>array[,,,,,]matrix
    {
      array[1, 1, 1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{{{2}}}}}}}};
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{{{[[(1.3499999999999999 + 0.0625 * seed)]]}}}}}};
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] value = bessel_second_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // bessel_second_kind(int,array[,,,,,,,]real)=>array[,,,,,,,]real
    {
      int arg_1 = 2;
      array[1, 1, 1, 1, 1, 1, 1, 1] real arg_2 = {{{{{{{{(1.3499999999999999 + 0.0625 * seed)}}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1, 1] real value = bessel_second_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // beta(array[,,,,,,]int,array[,,,,,,]int)=>array[,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{{2}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] int arg_2 = {{{{{{{3}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] real value = beta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // beta(array[,,,,]int,real)=>array[,,,,]real
    {
      array[1, 1, 1, 1, 1] int arg_1 = {{{{{2}}}}};
      real arg_2 = (2.9500000000000002 + 0.0625 * seed);
      array[1, 1, 1, 1, 1] real value = beta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // beta(array[,,,,]vector,array[,,,,]vector)=>array[,,,,]vector
    {
      array[1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{[(1.95 + 0.0625 * seed)]'}}}}};
      array[1, 1, 1, 1, 1] vector[1] arg_2 = {{{{{[(2.9500000000000002 + 0.0625 * seed)]'}}}}};
      array[1, 1, 1, 1, 1] vector[1] value = beta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // beta(array[,,]int,int)=>array[,,]real
    {
      array[1, 1, 1] int arg_1 = {{{2}}};
      int arg_2 = 3;
      array[1, 1, 1] real value = beta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // beta(int,array[,,,,]real)=>array[,,,,]real
    {
      int arg_1 = 2;
      array[1, 1, 1, 1, 1] real arg_2 = {{{{{(2.9500000000000002 + 0.0625 * seed)}}}}};
      array[1, 1, 1, 1, 1] real value = beta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // binary_log_loss(array[,,,,]int,array[,,,,]real)=>array[,,,,]real
    {
      array[1, 1, 1, 1, 1] int arg_1 = {{{{{1}}}}};
      array[1, 1, 1, 1, 1] real arg_2 = {{{{{(0.35000000000000003 + 0.0625 * seed)}}}}};
      array[1, 1, 1, 1, 1] real value = binary_log_loss(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // binary_log_loss(array[,,,,]int,real)=>array[,,,,]real
    {
      array[1, 1, 1, 1, 1] int arg_1 = {{{{{1}}}}};
      real arg_2 = (0.35000000000000003 + 0.0625 * seed);
      array[1, 1, 1, 1, 1] real value = binary_log_loss(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // binary_log_loss(int,array[,,,]matrix)=>array[,,,]matrix
    {
      int arg_1 = 1;
      array[1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{[[(0.35000000000000003 + 0.0625 * seed)]]}}}};
      array[1, 1, 1, 1] matrix[1, 1] value = binary_log_loss(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // binary_log_loss(int,matrix)=>matrix
    {
      int arg_1 = 1;
      matrix[1, 1] arg_2 = [[(0.35000000000000003 + 0.0625 * seed)]];
      matrix[1, 1] value = binary_log_loss(arg_1, arg_2);
      total += 1.234375 * sum(value);
    }
    // ceil(array[]row_vector)=>array[]row_vector
    {
      array[1] row_vector[1] arg_1 = {[(0.45000000000000001 + 0.0625 * seed)]};
      array[1] row_vector[1] value = ceil(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // choose(int,array[,,,,,,]int)=>array[,,,,,,]int
    {
      int arg_1 = 5;
      array[1, 1, 1, 1, 1, 1, 1] int arg_2 = {{{{{{{2}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] int value = choose(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // cos(array[,,,,,,]row_vector)=>array[,,,,,,]row_vector
    {
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{{{[(0.45000000000000001 + 0.0625 * seed)]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] value = cos(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // cos(array[,,,]vector)=>array[,,,]vector
    {
      array[1, 1, 1, 1] vector[1] arg_1 = {{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}};
      array[1, 1, 1, 1] vector[1] value = cos(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // cos(array[,,]matrix)=>array[,,]matrix
    {
      array[1, 1, 1] matrix[1, 1] arg_1 = {{{[[(0.45000000000000001 + 0.0625 * seed)]]}}};
      array[1, 1, 1] matrix[1, 1] value = cos(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // cos(array[,,]vector)=>array[,,]vector
    {
      array[1, 1, 1] vector[1] arg_1 = {{{[(0.45000000000000001 + 0.0625 * seed)]'}}};
      array[1, 1, 1] vector[1] value = cos(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // cosh(array[,,,,,]matrix)=>array[,,,,,]matrix
    {
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}}}};
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] value = cosh(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // cosh(array[,,,,,]real)=>array[,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{(0.45000000000000001 + 0.0625 * seed)}}}}}};
      array[1, 1, 1, 1, 1, 1] real value = cosh(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // cosh(real)=>real
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      real value = cosh(arg_1);
      total += 1.046875 * value;
    }
    // dims(array[,,,,,,]int)=>array[]int
    {
      array[1, 1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{{2}}}}}}};
      array[7] int value = dims(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // dims(array[,,,,,]int)=>array[]int
    {
      array[1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{2}}}}}};
      array[6] int value = dims(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // divide(vector,real)=>vector
    {
      vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)]';
      real arg_2 = (1.2 + 0.0625 * seed);
      vector[1] value = divide(arg_1, arg_2);
      total += 1.203125 * sum(value);
    }
    // dot_product(row_vector,row_vector)=>real
    {
      row_vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)];
      row_vector[1] arg_2 = [(1.2 + 0.0625 * seed)];
      real value = dot_product(arg_1, arg_2);
      total += 1.15625 * value;
    }
    // elt_divide(matrix,real)=>matrix
    {
      matrix[1, 1] arg_1 = [[(0.45000000000000001 + 0.0625 * seed)]];
      real arg_2 = (1.2 + 0.0625 * seed);
      matrix[1, 1] value = elt_divide(arg_1, arg_2);
      total += 1.1875 * sum(value);
    }
    // erf(array[,,,,,,]real)=>array[,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{{(0.45000000000000001 + 0.0625 * seed)}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] real value = erf(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // erf(array[,,,,]row_vector)=>array[,,,,]row_vector
    {
      array[1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{[(0.45000000000000001 + 0.0625 * seed)]}}}}};
      array[1, 1, 1, 1, 1] row_vector[1] value = erf(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // erf(array[,]row_vector)=>array[,]row_vector
    {
      array[1, 1] row_vector[1] arg_1 = {{[(0.45000000000000001 + 0.0625 * seed)]}};
      array[1, 1] row_vector[1] value = erf(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // erfc(array[,,,]real)=>array[,,,]real
    {
      array[1, 1, 1, 1] real arg_1 = {{{{(0.45000000000000001 + 0.0625 * seed)}}}};
      array[1, 1, 1, 1] real value = erfc(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // exp(array[,,,,]real)=>array[,,,,]real
    {
      array[1, 1, 1, 1, 1] real arg_1 = {{{{{(0.45000000000000001 + 0.0625 * seed)}}}}};
      array[1, 1, 1, 1, 1] real value = exp(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // exp(array[]matrix)=>array[]matrix
    {
      array[1] matrix[1, 1] arg_1 = {[[(0.45000000000000001 + 0.0625 * seed)]]};
      array[1] matrix[1, 1] value = exp(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // exp2(array[,,,,]matrix)=>array[,,,,]matrix
    {
      array[1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}}};
      array[1, 1, 1, 1, 1] matrix[1, 1] value = exp2(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // exp2(row_vector)=>row_vector
    {
      row_vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)];
      row_vector[1] value = exp2(arg_1);
      total += 1 * sum(value);
    }
    // expm1(array[,,,]vector)=>array[,,,]vector
    {
      array[1, 1, 1, 1] vector[1] arg_1 = {{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}};
      array[1, 1, 1, 1] vector[1] value = expm1(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // expm1(array[,,]int)=>array[,,]real
    {
      array[1, 1, 1] int arg_1 = {{{1}}};
      array[1, 1, 1] real value = expm1(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // falling_factorial(array[,,,,]vector,array[,,,,,]int)=>array[,,,,]vector
    {
      array[1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{[(3.4500000000000002 + 0.0625 * seed)]'}}}}};
      array[1, 1, 1, 1, 1, 1] int arg_2 = {{{{{{2}}}}}};
      array[1, 1, 1, 1, 1] vector[1] value = falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fdim(array[,,,,,]real,array[,,,,,]real)=>array[,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{(0.94999999999999996 + 0.0625 * seed)}}}}}};
      array[1, 1, 1, 1, 1, 1] real arg_2 = {{{{{{(0.94999999999999996 + 0.0625 * seed)}}}}}};
      array[1, 1, 1, 1, 1, 1] real value = fdim(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fdim(array[,,,,]row_vector,array[,,,,]row_vector)=>array[,,,,]row_vector
    {
      array[1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{[(0.94999999999999996 + 0.0625 * seed)]}}}}};
      array[1, 1, 1, 1, 1] row_vector[1] arg_2 = {{{{{[(0.94999999999999996 + 0.0625 * seed)]}}}}};
      array[1, 1, 1, 1, 1] row_vector[1] value = fdim(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fdim(int,array[,,,,,]row_vector)=>array[,,,,,]row_vector
    {
      int arg_1 = 1;
      array[1, 1, 1, 1, 1, 1] row_vector[1] arg_2 = {{{{{{[(0.94999999999999996 + 0.0625 * seed)]}}}}}};
      array[1, 1, 1, 1, 1, 1] row_vector[1] value = fdim(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fdim(int,array[,]matrix)=>array[,]matrix
    {
      int arg_1 = 1;
      array[1, 1] matrix[1, 1] arg_2 = {{[[(0.94999999999999996 + 0.0625 * seed)]]}};
      array[1, 1] matrix[1, 1] value = fdim(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fdim(int,array[]int)=>array[]real
    {
      int arg_1 = 1;
      array[1] int arg_2 = {1};
      array[1] real value = fdim(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fdim(real,array[]row_vector)=>array[]row_vector
    {
      real arg_1 = (0.94999999999999996 + 0.0625 * seed);
      array[1] row_vector[1] arg_2 = {[(0.94999999999999996 + 0.0625 * seed)]};
      array[1] row_vector[1] value = fdim(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fdim(row_vector,row_vector)=>row_vector
    {
      row_vector[1] arg_1 = [(0.94999999999999996 + 0.0625 * seed)];
      row_vector[1] arg_2 = [(0.94999999999999996 + 0.0625 * seed)];
      row_vector[1] value = fdim(arg_1, arg_2);
      total += 1.078125 * sum(value);
    }
    // floor(array[,]int)=>array[,]real
    {
      array[1, 1] int arg_1 = {{1}};
      array[1, 1] real value = floor(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // fmax(array[,,,,,,]real,int)=>array[,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{{(0.94999999999999996 + 0.0625 * seed)}}}}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1, 1, 1, 1] real value = fmax(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmax(array[,,,,,]real,real)=>array[,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{(0.94999999999999996 + 0.0625 * seed)}}}}}};
      real arg_2 = (0.94999999999999996 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1] real value = fmax(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmax(array[,,,,]real,array[,,,,]real)=>array[,,,,]real
    {
      array[1, 1, 1, 1, 1] real arg_1 = {{{{{(0.94999999999999996 + 0.0625 * seed)}}}}};
      array[1, 1, 1, 1, 1] real arg_2 = {{{{{(0.94999999999999996 + 0.0625 * seed)}}}}};
      array[1, 1, 1, 1, 1] real value = fmax(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmax(array[,,,]vector,int)=>array[,,,]vector
    {
      array[1, 1, 1, 1] vector[1] arg_1 = {{{{[(0.94999999999999996 + 0.0625 * seed)]'}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1] vector[1] value = fmax(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmax(array[,]int,array[,]int)=>array[,]real
    {
      array[1, 1] int arg_1 = {{1}};
      array[1, 1] int arg_2 = {{1}};
      array[1, 1] real value = fmax(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmax(array[,]matrix,real)=>array[,]matrix
    {
      array[1, 1] matrix[1, 1] arg_1 = {{[[(0.94999999999999996 + 0.0625 * seed)]]}};
      real arg_2 = (0.94999999999999996 + 0.0625 * seed);
      array[1, 1] matrix[1, 1] value = fmax(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmax(int,array[,,,]row_vector)=>array[,,,]row_vector
    {
      int arg_1 = 1;
      array[1, 1, 1, 1] row_vector[1] arg_2 = {{{{[(0.94999999999999996 + 0.0625 * seed)]}}}};
      array[1, 1, 1, 1] row_vector[1] value = fmax(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmax(real,array[,,,,]matrix)=>array[,,,,]matrix
    {
      real arg_1 = (0.94999999999999996 + 0.0625 * seed);
      array[1, 1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{{[[(0.94999999999999996 + 0.0625 * seed)]]}}}}};
      array[1, 1, 1, 1, 1] matrix[1, 1] value = fmax(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmax(real,array[,,,]matrix)=>array[,,,]matrix
    {
      real arg_1 = (0.94999999999999996 + 0.0625 * seed);
      array[1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{[[(0.94999999999999996 + 0.0625 * seed)]]}}}};
      array[1, 1, 1, 1] matrix[1, 1] value = fmax(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmin(array[,,,,,,]row_vector,array[,,,,,,]row_vector)=>array[,,,,,,]row_vector
    {
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{{{[(0.94999999999999996 + 0.0625 * seed)]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] arg_2 = {{{{{{{[(0.94999999999999996 + 0.0625 * seed)]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] value = fmin(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmin(array[,,]int,int)=>array[,,]real
    {
      array[1, 1, 1] int arg_1 = {{{1}}};
      int arg_2 = 1;
      array[1, 1, 1] real value = fmin(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmin(array[,]row_vector,real)=>array[,]row_vector
    {
      array[1, 1] row_vector[1] arg_1 = {{[(0.94999999999999996 + 0.0625 * seed)]}};
      real arg_2 = (0.94999999999999996 + 0.0625 * seed);
      array[1, 1] row_vector[1] value = fmin(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmin(array[]vector,real)=>array[]vector
    {
      array[1] vector[1] arg_1 = {[(0.94999999999999996 + 0.0625 * seed)]'};
      real arg_2 = (0.94999999999999996 + 0.0625 * seed);
      array[1] vector[1] value = fmin(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmin(int,array[,,,]real)=>array[,,,]real
    {
      int arg_1 = 1;
      array[1, 1, 1, 1] real arg_2 = {{{{(0.94999999999999996 + 0.0625 * seed)}}}};
      array[1, 1, 1, 1] real value = fmin(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmin(int,array[,,]real)=>array[,,]real
    {
      int arg_1 = 1;
      array[1, 1, 1] real arg_2 = {{{(0.94999999999999996 + 0.0625 * seed)}}};
      array[1, 1, 1] real value = fmin(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmin(real,array[,,,,]int)=>array[,,,,]real
    {
      real arg_1 = (0.94999999999999996 + 0.0625 * seed);
      array[1, 1, 1, 1, 1] int arg_2 = {{{{{1}}}}};
      array[1, 1, 1, 1, 1] real value = fmin(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmod(array[,,,,,]int,real)=>array[,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{2}}}}}};
      real arg_2 = (0.94999999999999996 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1] real value = fmod(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmod(array[,,,,]vector,real)=>array[,,,,]vector
    {
      array[1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{[(2.4500000000000002 + 0.0625 * seed)]'}}}}};
      real arg_2 = (0.94999999999999996 + 0.0625 * seed);
      array[1, 1, 1, 1, 1] vector[1] value = fmod(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmod(array[,,,]int,array[,,,]int)=>array[,,,]real
    {
      array[1, 1, 1, 1] int arg_1 = {{{{2}}}};
      array[1, 1, 1, 1] int arg_2 = {{{{1}}}};
      array[1, 1, 1, 1] real value = fmod(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmod(array[,,]matrix,array[,,]matrix)=>array[,,]matrix
    {
      array[1, 1, 1] matrix[1, 1] arg_1 = {{{[[(2.4500000000000002 + 0.0625 * seed)]]}}};
      array[1, 1, 1] matrix[1, 1] arg_2 = {{{[[(0.94999999999999996 + 0.0625 * seed)]]}}};
      array[1, 1, 1] matrix[1, 1] value = fmod(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmod(array[,,]vector,real)=>array[,,]vector
    {
      array[1, 1, 1] vector[1] arg_1 = {{{[(2.4500000000000002 + 0.0625 * seed)]'}}};
      real arg_2 = (0.94999999999999996 + 0.0625 * seed);
      array[1, 1, 1] vector[1] value = fmod(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmod(int,array[,,,,,]row_vector)=>array[,,,,,]row_vector
    {
      int arg_1 = 2;
      array[1, 1, 1, 1, 1, 1] row_vector[1] arg_2 = {{{{{{[(0.94999999999999996 + 0.0625 * seed)]}}}}}};
      array[1, 1, 1, 1, 1, 1] row_vector[1] value = fmod(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmod(real,array[,,,,]row_vector)=>array[,,,,]row_vector
    {
      real arg_1 = (2.4500000000000002 + 0.0625 * seed);
      array[1, 1, 1, 1, 1] row_vector[1] arg_2 = {{{{{[(0.94999999999999996 + 0.0625 * seed)]}}}}};
      array[1, 1, 1, 1, 1] row_vector[1] value = fmod(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmod(real,array[,,]matrix)=>array[,,]matrix
    {
      real arg_1 = (2.4500000000000002 + 0.0625 * seed);
      array[1, 1, 1] matrix[1, 1] arg_2 = {{{[[(0.94999999999999996 + 0.0625 * seed)]]}}};
      array[1, 1, 1] matrix[1, 1] value = fmod(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // gamma_p(array[,,,,,,]matrix,array[,,,,,,]matrix)=>array[,,,,,,]matrix
    {
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{{{[[(1.95 + 0.0625 * seed)]]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{{{{[[(1.25 + 0.0625 * seed)]]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] value = gamma_p(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // gamma_q(array[,,,,,,]matrix,real)=>array[,,,,,,]matrix
    {
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{{{[[(1.95 + 0.0625 * seed)]]}}}}}}};
      real arg_2 = (1.25 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] value = gamma_q(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // gamma_q(array[,,,,,,]row_vector,array[,,,,,,]row_vector)=>array[,,,,,,]row_vector
    {
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{{{[(1.95 + 0.0625 * seed)]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] arg_2 = {{{{{{{[(1.25 + 0.0625 * seed)]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] value = gamma_q(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // gamma_q(array[,,,,,]real,array[,,,,,]real)=>array[,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{(1.95 + 0.0625 * seed)}}}}}};
      array[1, 1, 1, 1, 1, 1] real arg_2 = {{{{{{(1.25 + 0.0625 * seed)}}}}}};
      array[1, 1, 1, 1, 1, 1] real value = gamma_q(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // gamma_q(array[,]real,array[,]real)=>array[,]real
    {
      array[1, 1] real arg_1 = {{(1.95 + 0.0625 * seed)}};
      array[1, 1] real arg_2 = {{(1.25 + 0.0625 * seed)}};
      array[1, 1] real value = gamma_q(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // gamma_q(array[]vector,array[]vector)=>array[]vector
    {
      array[1] vector[1] arg_1 = {[(1.95 + 0.0625 * seed)]'};
      array[1] vector[1] arg_2 = {[(1.25 + 0.0625 * seed)]'};
      array[1] vector[1] value = gamma_q(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // gamma_q(row_vector,row_vector)=>row_vector
    {
      row_vector[1] arg_1 = [(1.95 + 0.0625 * seed)];
      row_vector[1] arg_2 = [(1.25 + 0.0625 * seed)];
      row_vector[1] value = gamma_q(arg_1, arg_2);
      total += 1.015625 * sum(value);
    }
    // hypot(array[,,,,,,]real,array[,,,,,,]real)=>array[,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{{(0.45000000000000001 + 0.0625 * seed)}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] real arg_2 = {{{{{{{(1.2 + 0.0625 * seed)}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] real value = hypot(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // hypot(array[,,,,,,]real,real)=>array[,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{{(0.45000000000000001 + 0.0625 * seed)}}}}}}};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1, 1] real value = hypot(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // hypot(array[,,,,]real,real)=>array[,,,,]real
    {
      array[1, 1, 1, 1, 1] real arg_1 = {{{{{(0.45000000000000001 + 0.0625 * seed)}}}}};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1, 1, 1, 1, 1] real value = hypot(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // hypot(array[,,,]int,int)=>array[,,,]real
    {
      array[1, 1, 1, 1] int arg_1 = {{{{0}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1] real value = hypot(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // hypot(array[,,,]row_vector,array[,,,]row_vector)=>array[,,,]row_vector
    {
      array[1, 1, 1, 1] row_vector[1] arg_1 = {{{{[(0.45000000000000001 + 0.0625 * seed)]}}}};
      array[1, 1, 1, 1] row_vector[1] arg_2 = {{{{[(1.2 + 0.0625 * seed)]}}}};
      array[1, 1, 1, 1] row_vector[1] value = hypot(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // hypot(int,array[,,,,,,,]int)=>array[,,,,,,,]real
    {
      int arg_1 = 0;
      array[1, 1, 1, 1, 1, 1, 1, 1] int arg_2 = {{{{{{{{1}}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1, 1] real value = hypot(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // hypot(int,array[,,,,,]real)=>array[,,,,,]real
    {
      int arg_1 = 0;
      array[1, 1, 1, 1, 1, 1] real arg_2 = {{{{{{(1.2 + 0.0625 * seed)}}}}}};
      array[1, 1, 1, 1, 1, 1] real value = hypot(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // hypot(int,array[,]int)=>array[,]real
    {
      int arg_1 = 0;
      array[1, 1] int arg_2 = {{1}};
      array[1, 1] real value = hypot(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // hypot(real,vector)=>vector
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      vector[1] arg_2 = [(1.2 + 0.0625 * seed)]';
      vector[1] value = hypot(arg_1, arg_2);
      total += 1.109375 * sum(value);
    }
    // inv_cloglog(array[,,,,,,]matrix)=>array[,,,,,,]matrix
    {
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] value = inv_cloglog(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // inv_cloglog(array[,,,]row_vector)=>array[,,,]row_vector
    {
      array[1, 1, 1, 1] row_vector[1] arg_1 = {{{{[(0.45000000000000001 + 0.0625 * seed)]}}}};
      array[1, 1, 1, 1] row_vector[1] value = inv_cloglog(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // inv_sqrt(array[,,,,]real)=>array[,,,,]real
    {
      array[1, 1, 1, 1, 1] real arg_1 = {{{{{(1.3499999999999999 + 0.0625 * seed)}}}}};
      array[1, 1, 1, 1, 1] real value = inv_sqrt(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // inv_sqrt(array[]vector)=>array[]vector
    {
      array[1] vector[1] arg_1 = {[(1.3499999999999999 + 0.0625 * seed)]'};
      array[1] vector[1] value = inv_sqrt(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // inv_square(array[,,,,]vector)=>array[,,,,]vector
    {
      array[1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}}};
      array[1, 1, 1, 1, 1] vector[1] value = inv_square(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // inv_square(array[]row_vector)=>array[]row_vector
    {
      array[1] row_vector[1] arg_1 = {[(0.45000000000000001 + 0.0625 * seed)]};
      array[1] row_vector[1] value = inv_square(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // inverse(matrix)=>matrix
    {
      matrix[1, 1] arg_1 = [[(0.45000000000000001 + 0.0625 * seed)]];
      matrix[1, 1] value = inverse(arg_1);
      total += 1 * sum(value);
    }
    // lambert_w0(array[,,,]real)=>array[,,,]real
    {
      array[1, 1, 1, 1] real arg_1 = {{{{(0.45000000000000001 + 0.0625 * seed)}}}};
      array[1, 1, 1, 1] real value = lambert_w0(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // lambert_w0(array[,,]real)=>array[,,]real
    {
      array[1, 1, 1] real arg_1 = {{{(0.45000000000000001 + 0.0625 * seed)}}};
      array[1, 1, 1] real value = lambert_w0(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // lambert_w0(array[,]vector)=>array[,]vector
    {
      array[1, 1] vector[1] arg_1 = {{[(0.45000000000000001 + 0.0625 * seed)]'}};
      array[1, 1] vector[1] value = lambert_w0(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // lambert_w0(array[]matrix)=>array[]matrix
    {
      array[1] matrix[1, 1] arg_1 = {[[(0.45000000000000001 + 0.0625 * seed)]]};
      array[1] matrix[1, 1] value = lambert_w0(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // lambert_w0(row_vector)=>row_vector
    {
      row_vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)];
      row_vector[1] value = lambert_w0(arg_1);
      total += 1.078125 * sum(value);
    }
    // lambert_wm1(array[,,,,,]matrix)=>array[,,,,,]matrix
    {
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{{[[(-0.25 + 0.0625 * seed)]]}}}}}};
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] value = lambert_wm1(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // lambert_wm1(array[,,,,]vector)=>array[,,,,]vector
    {
      array[1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{[(-0.25 + 0.0625 * seed)]'}}}}};
      array[1, 1, 1, 1, 1] vector[1] value = lambert_wm1(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // lambert_wm1(array[,,,]matrix)=>array[,,,]matrix
    {
      array[1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{[[(-0.25 + 0.0625 * seed)]]}}}};
      array[1, 1, 1, 1] matrix[1, 1] value = lambert_wm1(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // lambert_wm1(array[,]matrix)=>array[,]matrix
    {
      array[1, 1] matrix[1, 1] arg_1 = {{[[(-0.25 + 0.0625 * seed)]]}};
      array[1, 1] matrix[1, 1] value = lambert_wm1(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // lbeta(array[,,,,,,]int,array[,,,,,,]int)=>array[,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{{2}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] int arg_2 = {{{{{{{3}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] real value = lbeta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lbeta(array[,,]vector,int)=>array[,,]vector
    {
      array[1, 1, 1] vector[1] arg_1 = {{{[(1.95 + 0.0625 * seed)]'}}};
      int arg_2 = 3;
      array[1, 1, 1] vector[1] value = lbeta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lbeta(array[,]matrix,real)=>array[,]matrix
    {
      array[1, 1] matrix[1, 1] arg_1 = {{[[(1.95 + 0.0625 * seed)]]}};
      real arg_2 = (2.9500000000000002 + 0.0625 * seed);
      array[1, 1] matrix[1, 1] value = lbeta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lbeta(array[]real,int)=>array[]real
    {
      array[1] real arg_1 = {(1.95 + 0.0625 * seed)};
      int arg_2 = 3;
      array[1] real value = lbeta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lbeta(array[]row_vector,int)=>array[]row_vector
    {
      array[1] row_vector[1] arg_1 = {[(1.95 + 0.0625 * seed)]};
      int arg_2 = 3;
      array[1] row_vector[1] value = lbeta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lchoose(array[,]int,int)=>array[,]real
    {
      array[1, 1] int arg_1 = {{4}};
      int arg_2 = 2;
      array[1, 1] real value = lchoose(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lchoose(int,array[,,,,,]matrix)=>array[,,,,,]matrix
    {
      int arg_1 = 4;
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{{{[[(1.95 + 0.0625 * seed)]]}}}}}};
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] value = lchoose(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // ldexp(array[,,,,,,]matrix,array[,,,,,,,,]int)=>array[,,,,,,]matrix
    {
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1, 1, 1] int arg_2 = {{{{{{{{{2}}}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] value = ldexp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // ldexp(array[,,,]real,int)=>array[,,,]real
    {
      array[1, 1, 1, 1] real arg_1 = {{{{(0.45000000000000001 + 0.0625 * seed)}}}};
      int arg_2 = 2;
      array[1, 1, 1, 1] real value = ldexp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // ldexp(array[,,]real,array[,,]int)=>array[,,]real
    {
      array[1, 1, 1] real arg_1 = {{{(0.45000000000000001 + 0.0625 * seed)}}};
      array[1, 1, 1] int arg_2 = {{{2}}};
      array[1, 1, 1] real value = ldexp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lgamma(array[,,]int)=>array[,,]real
    {
      array[1, 1, 1] int arg_1 = {{{1}}};
      array[1, 1, 1] real value = lgamma(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // lmgamma(array[,,,]int,array[,]matrix)=>array[,]matrix
    {
      array[1, 1, 1, 1] int arg_1 = {{{{2}}}};
      array[1, 1] matrix[1, 1] arg_2 = {{[[(1.95 + 0.0625 * seed)]]}};
      array[1, 1] matrix[1, 1] value = lmgamma(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lmgamma(array[]int,real)=>array[]real
    {
      array[1] int arg_1 = {2};
      real arg_2 = (1.95 + 0.0625 * seed);
      array[1] real value = lmgamma(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lmgamma(int,array[,]vector)=>array[,]vector
    {
      int arg_1 = 2;
      array[1, 1] vector[1] arg_2 = {{[(1.95 + 0.0625 * seed)]'}};
      array[1, 1] vector[1] value = lmgamma(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lmultiply(array[,]row_vector,real)=>array[,]row_vector
    {
      array[1, 1] row_vector[1] arg_1 = {{[(0.45000000000000001 + 0.0625 * seed)]}};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1, 1] row_vector[1] value = lmultiply(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lmultiply(array[]row_vector,array[]row_vector)=>array[]row_vector
    {
      array[1] row_vector[1] arg_1 = {[(0.45000000000000001 + 0.0625 * seed)]};
      array[1] row_vector[1] arg_2 = {[(1.2 + 0.0625 * seed)]};
      array[1] row_vector[1] value = lmultiply(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log(array[,,,]row_vector)=>array[,,,]row_vector
    {
      array[1, 1, 1, 1] row_vector[1] arg_1 = {{{{[(1.3499999999999999 + 0.0625 * seed)]}}}};
      array[1, 1, 1, 1] row_vector[1] value = log(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log1m(array[,,]matrix)=>array[,,]matrix
    {
      array[1, 1, 1] matrix[1, 1] arg_1 = {{{[[(0.29999999999999999 + 0.0625 * seed)]]}}};
      array[1, 1, 1] matrix[1, 1] value = log1m(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log1m(row_vector)=>row_vector
    {
      row_vector[1] arg_1 = [(0.29999999999999999 + 0.0625 * seed)];
      row_vector[1] value = log1m(arg_1);
      total += 1.15625 * sum(value);
    }
    // log1p(array[,,,,]int)=>array[,,,,]real
    {
      array[1, 1, 1, 1, 1] int arg_1 = {{{{{1}}}}};
      array[1, 1, 1, 1, 1] real value = log1p(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log2(array[,,,]matrix)=>array[,,,]matrix
    {
      array[1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{[[(1.3499999999999999 + 0.0625 * seed)]]}}}};
      array[1, 1, 1, 1] matrix[1, 1] value = log2(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log2(real)=>real
    {
      real arg_1 = (1.3499999999999999 + 0.0625 * seed);
      real value = log2(arg_1);
      total += 1.140625 * value;
    }
    // log_diff_exp(array[,,,,,]row_vector,real)=>array[,,,,,]row_vector
    {
      array[1, 1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{{[(1.45 + 0.0625 * seed)]}}}}}};
      real arg_2 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1] row_vector[1] value = log_diff_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_diff_exp(array[,,]row_vector,int)=>array[,,]row_vector
    {
      array[1, 1, 1] row_vector[1] arg_1 = {{{[(1.45 + 0.0625 * seed)]}}};
      int arg_2 = 0;
      array[1, 1, 1] row_vector[1] value = log_diff_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_diff_exp(array[,,]vector,array[,,]vector)=>array[,,]vector
    {
      array[1, 1, 1] vector[1] arg_1 = {{{[(1.45 + 0.0625 * seed)]'}}};
      array[1, 1, 1] vector[1] arg_2 = {{{[(0.45000000000000001 + 0.0625 * seed)]'}}};
      array[1, 1, 1] vector[1] value = log_diff_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_diff_exp(array[,,]vector,int)=>array[,,]vector
    {
      array[1, 1, 1] vector[1] arg_1 = {{{[(1.45 + 0.0625 * seed)]'}}};
      int arg_2 = 0;
      array[1, 1, 1] vector[1] value = log_diff_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_diff_exp(array[]real,array[]real)=>array[]real
    {
      array[1] real arg_1 = {(1.45 + 0.0625 * seed)};
      array[1] real arg_2 = {(0.45000000000000001 + 0.0625 * seed)};
      array[1] real value = log_diff_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_diff_exp(int,array[,,,,]real)=>array[,,,,]real
    {
      int arg_1 = 1;
      array[1, 1, 1, 1, 1] real arg_2 = {{{{{(0.45000000000000001 + 0.0625 * seed)}}}}};
      array[1, 1, 1, 1, 1] real value = log_diff_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_diff_exp(int,array[,,,]int)=>array[,,,]real
    {
      int arg_1 = 1;
      array[1, 1, 1, 1] int arg_2 = {{{{0}}}};
      array[1, 1, 1, 1] real value = log_diff_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_diff_exp(int,array[]row_vector)=>array[]row_vector
    {
      int arg_1 = 1;
      array[1] row_vector[1] arg_2 = {[(0.45000000000000001 + 0.0625 * seed)]};
      array[1] row_vector[1] value = log_diff_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_diff_exp(int,int)=>real
    {
      int arg_1 = 1;
      int arg_2 = 0;
      real value = log_diff_exp(arg_1, arg_2);
      total += 1.03125 * value;
    }
    // log_diff_exp(int,real)=>real
    {
      int arg_1 = 1;
      real arg_2 = (0.45000000000000001 + 0.0625 * seed);
      real value = log_diff_exp(arg_1, arg_2);
      total += 1.25 * value;
    }
    // log_falling_factorial(array[,,,,]int,real)=>array[,,,,]real
    {
      array[1, 1, 1, 1, 1] int arg_1 = {{{{{3}}}}};
      real arg_2 = (1.1499999999999999 + 0.0625 * seed);
      array[1, 1, 1, 1, 1] real value = log_falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_falling_factorial(array[,]matrix,real)=>array[,]matrix
    {
      array[1, 1] matrix[1, 1] arg_1 = {{[[(3.4500000000000002 + 0.0625 * seed)]]}};
      real arg_2 = (1.1499999999999999 + 0.0625 * seed);
      array[1, 1] matrix[1, 1] value = log_falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_falling_factorial(int,array[]real)=>array[]real
    {
      int arg_1 = 3;
      array[1] real arg_2 = {(1.1499999999999999 + 0.0625 * seed)};
      array[1] real value = log_falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_falling_factorial(real,int)=>real
    {
      real arg_1 = (3.4500000000000002 + 0.0625 * seed);
      int arg_2 = 1;
      real value = log_falling_factorial(arg_1, arg_2);
      total += 1.171875 * value;
    }
    // log_inv_logit(array[,,,,,,]matrix)=>array[,,,,,,]matrix
    {
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] value = log_inv_logit(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log_inv_logit(array[,,,]real)=>array[,,,]real
    {
      array[1, 1, 1, 1] real arg_1 = {{{{(0.45000000000000001 + 0.0625 * seed)}}}};
      array[1, 1, 1, 1] real value = log_inv_logit(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log_inv_logit(matrix)=>matrix
    {
      matrix[1, 1] arg_1 = [[(0.45000000000000001 + 0.0625 * seed)]];
      matrix[1, 1] value = log_inv_logit(arg_1);
      total += 1 * sum(value);
    }
    // log_inv_logit_diff(real,array[,,]row_vector)=>array[,,]row_vector
    {
      real arg_1 = (0.94999999999999996 + 0.0625 * seed);
      array[1, 1, 1] row_vector[1] arg_2 = {{{[(-0.55000000000000004 + 0.0625 * seed)]}}};
      array[1, 1, 1] row_vector[1] value = log_inv_logit_diff(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_inv_logit_diff(real,array[]real)=>array[]real
    {
      real arg_1 = (0.94999999999999996 + 0.0625 * seed);
      array[1] real arg_2 = {(-0.55000000000000004 + 0.0625 * seed)};
      array[1] real value = log_inv_logit_diff(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_modified_bessel_first_kind(array[,,,,,]real,real)=>array[,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{(0.45000000000000001 + 0.0625 * seed)}}}}}};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1] real value = log_modified_bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_modified_bessel_first_kind(array[,,,]matrix,real)=>array[,,,]matrix
    {
      array[1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1, 1, 1, 1] matrix[1, 1] value = log_modified_bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_modified_bessel_first_kind(array[,,]vector,real)=>array[,,]vector
    {
      array[1, 1, 1] vector[1] arg_1 = {{{[(0.45000000000000001 + 0.0625 * seed)]'}}};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1, 1, 1] vector[1] value = log_modified_bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_modified_bessel_first_kind(array[,]int,real)=>array[,]real
    {
      array[1, 1] int arg_1 = {{0}};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1, 1] real value = log_modified_bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_modified_bessel_first_kind(array[,]matrix,array[,]matrix)=>array[,]matrix
    {
      array[1, 1] matrix[1, 1] arg_1 = {{[[(0.45000000000000001 + 0.0625 * seed)]]}};
      array[1, 1] matrix[1, 1] arg_2 = {{[[(1.2 + 0.0625 * seed)]]}};
      array[1, 1] matrix[1, 1] value = log_modified_bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_modified_bessel_first_kind(int,array[,,,,]matrix)=>array[,,,,]matrix
    {
      int arg_1 = 0;
      array[1, 1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{{[[(1.2 + 0.0625 * seed)]]}}}}};
      array[1, 1, 1, 1, 1] matrix[1, 1] value = log_modified_bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_modified_bessel_first_kind(int,array[]matrix)=>array[]matrix
    {
      int arg_1 = 0;
      array[1] matrix[1, 1] arg_2 = {[[(1.2 + 0.0625 * seed)]]};
      array[1] matrix[1, 1] value = log_modified_bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_modified_bessel_first_kind(int,real)=>real
    {
      int arg_1 = 0;
      real arg_2 = (1.2 + 0.0625 * seed);
      real value = log_modified_bessel_first_kind(arg_1, arg_2);
      total += 1.109375 * value;
    }
    // log_modified_bessel_first_kind(real,array[,,,,,,,]real)=>array[,,,,,,,]real
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1, 1, 1] real arg_2 = {{{{{{{{(1.2 + 0.0625 * seed)}}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1, 1] real value = log_modified_bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_modified_bessel_first_kind(real,array[,]int)=>array[,]real
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1] int arg_2 = {{1}};
      array[1, 1] real value = log_modified_bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_rising_factorial(array[,,]row_vector,int)=>array[,,]row_vector
    {
      array[1, 1, 1] row_vector[1] arg_1 = {{{[(1.45 + 0.0625 * seed)]}}};
      int arg_2 = 1;
      array[1, 1, 1] row_vector[1] value = log_rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_rising_factorial(array[,,]vector,int)=>array[,,]vector
    {
      array[1, 1, 1] vector[1] arg_1 = {{{[(1.45 + 0.0625 * seed)]'}}};
      int arg_2 = 1;
      array[1, 1, 1] vector[1] value = log_rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_rising_factorial(array[,,]vector,real)=>array[,,]vector
    {
      array[1, 1, 1] vector[1] arg_1 = {{{[(1.45 + 0.0625 * seed)]'}}};
      real arg_2 = (1.1499999999999999 + 0.0625 * seed);
      array[1, 1, 1] vector[1] value = log_rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_rising_factorial(array[,]vector,array[,]vector)=>array[,]vector
    {
      array[1, 1] vector[1] arg_1 = {{[(1.45 + 0.0625 * seed)]'}};
      array[1, 1] vector[1] arg_2 = {{[(1.1499999999999999 + 0.0625 * seed)]'}};
      array[1, 1] vector[1] value = log_rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_rising_factorial(array[]row_vector,int)=>array[]row_vector
    {
      array[1] row_vector[1] arg_1 = {[(1.45 + 0.0625 * seed)]};
      int arg_2 = 1;
      array[1] row_vector[1] value = log_rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_rising_factorial(array[]row_vector,real)=>array[]row_vector
    {
      array[1] row_vector[1] arg_1 = {[(1.45 + 0.0625 * seed)]};
      real arg_2 = (1.1499999999999999 + 0.0625 * seed);
      array[1] row_vector[1] value = log_rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_rising_factorial(int,array[,,,,,]row_vector)=>array[,,,,,]row_vector
    {
      int arg_1 = 1;
      array[1, 1, 1, 1, 1, 1] row_vector[1] arg_2 = {{{{{{[(1.1499999999999999 + 0.0625 * seed)]}}}}}};
      array[1, 1, 1, 1, 1, 1] row_vector[1] value = log_rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_rising_factorial(int,array[,,,]matrix)=>array[,,,]matrix
    {
      int arg_1 = 1;
      array[1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{[[(1.1499999999999999 + 0.0625 * seed)]]}}}};
      array[1, 1, 1, 1] matrix[1, 1] value = log_rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_rising_factorial(real,array[,,,,]real)=>array[,,,,]real
    {
      real arg_1 = (1.45 + 0.0625 * seed);
      array[1, 1, 1, 1, 1] real arg_2 = {{{{{(1.1499999999999999 + 0.0625 * seed)}}}}};
      array[1, 1, 1, 1, 1] real value = log_rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_rising_factorial(real,int)=>real
    {
      real arg_1 = (1.45 + 0.0625 * seed);
      int arg_2 = 1;
      real value = log_rising_factorial(arg_1, arg_2);
      total += 1.03125 * value;
    }
    // log_rising_factorial(real,row_vector)=>row_vector
    {
      real arg_1 = (1.45 + 0.0625 * seed);
      row_vector[1] arg_2 = [(1.1499999999999999 + 0.0625 * seed)];
      row_vector[1] value = log_rising_factorial(arg_1, arg_2);
      total += 1.09375 * sum(value);
    }
    // log_sum_exp(array[,,,]row_vector,int)=>array[,,,]row_vector
    {
      array[1, 1, 1, 1] row_vector[1] arg_1 = {{{{[(0.45000000000000001 + 0.0625 * seed)]}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1] row_vector[1] value = log_sum_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_sum_exp(array[,,]int,array[,,]int)=>array[,,]real
    {
      array[1, 1, 1] int arg_1 = {{{0}}};
      array[1, 1, 1] int arg_2 = {{{1}}};
      array[1, 1, 1] real value = log_sum_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_sum_exp(array[,]matrix,array[,]matrix)=>array[,]matrix
    {
      array[1, 1] matrix[1, 1] arg_1 = {{[[(0.45000000000000001 + 0.0625 * seed)]]}};
      array[1, 1] matrix[1, 1] arg_2 = {{[[(1.2 + 0.0625 * seed)]]}};
      array[1, 1] matrix[1, 1] value = log_sum_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_sum_exp(array[]int,int)=>array[]real
    {
      array[1] int arg_1 = {0};
      int arg_2 = 1;
      array[1] real value = log_sum_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_sum_exp(array[]row_vector,real)=>array[]row_vector
    {
      array[1] row_vector[1] arg_1 = {[(0.45000000000000001 + 0.0625 * seed)]};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1] row_vector[1] value = log_sum_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_sum_exp(int,array[,,]int)=>array[,,]real
    {
      int arg_1 = 0;
      array[1, 1, 1] int arg_2 = {{{1}}};
      array[1, 1, 1] real value = log_sum_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_sum_exp(real,array[,,,,,,,]real)=>array[,,,,,,,]real
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1, 1, 1] real arg_2 = {{{{{{{{(1.2 + 0.0625 * seed)}}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1, 1] real value = log_sum_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_sum_exp(real,array[,,]row_vector)=>array[,,]row_vector
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1, 1] row_vector[1] arg_2 = {{{[(1.2 + 0.0625 * seed)]}}};
      array[1, 1, 1] row_vector[1] value = log_sum_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // logical_neq(real,int)=>int
    {
      int value = logical_neq(0.45000000000000001, 1);
      total += 1.21875 * value;
    }
    // logical_or(int,int)=>int
    {
      int value = logical_or(0, 1);
      total += 1.171875 * value;
    }
    // minus(array[,,,,]matrix)=>array[,,,,]matrix
    {
      array[1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}}};
      array[1, 1, 1, 1, 1] matrix[1, 1] value = minus(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // minus(array[,,,]vector)=>array[,,,]vector
    {
      array[1, 1, 1, 1] vector[1] arg_1 = {{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}};
      array[1, 1, 1, 1] vector[1] value = minus(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // modified_bessel_first_kind(int,array[,,]row_vector)=>array[,,]row_vector
    {
      int arg_1 = 2;
      array[1, 1, 1] row_vector[1] arg_2 = {{{[(1.3499999999999999 + 0.0625 * seed)]}}};
      array[1, 1, 1] row_vector[1] value = modified_bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // modified_bessel_second_kind(array[,,,,,,,,]int,array[,,,,,,]matrix)=>array[,,,,,,]matrix
    {
      array[1, 1, 1, 1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{{{{2}}}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{{{{[[(1.3499999999999999 + 0.0625 * seed)]]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] value = modified_bessel_second_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // modified_bessel_second_kind(array[]int,row_vector)=>row_vector
    {
      array[1] int arg_1 = {2};
      row_vector[1] arg_2 = [(1.3499999999999999 + 0.0625 * seed)];
      row_vector[1] value = modified_bessel_second_kind(arg_1, arg_2);
      total += 1.234375 * sum(value);
    }
    // modified_bessel_second_kind(int,array[,,,]vector)=>array[,,,]vector
    {
      int arg_1 = 2;
      array[1, 1, 1, 1] vector[1] arg_2 = {{{{[(1.3499999999999999 + 0.0625 * seed)]'}}}};
      array[1, 1, 1, 1] vector[1] value = modified_bessel_second_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // ones_array(int)=>array[]real
    {
      array[1] real value = ones_array(1);
      if (seed > 1e100)
        print(value);
    }
    // owens_t(array[,,,,,,,]real,array[,,,,,,,]real)=>array[,,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{{{(0.45000000000000001 + 0.0625 * seed)}}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1, 1] real arg_2 = {{{{{{{{(1.2 + 0.0625 * seed)}}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1, 1] real value = owens_t(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // owens_t(array[,,,,,]matrix,real)=>array[,,,,,]matrix
    {
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}}}};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] value = owens_t(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // owens_t(array[,,,]row_vector,real)=>array[,,,]row_vector
    {
      array[1, 1, 1, 1] row_vector[1] arg_1 = {{{{[(0.45000000000000001 + 0.0625 * seed)]}}}};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1, 1, 1, 1] row_vector[1] value = owens_t(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // owens_t(array[,,]matrix,real)=>array[,,]matrix
    {
      array[1, 1, 1] matrix[1, 1] arg_1 = {{{[[(0.45000000000000001 + 0.0625 * seed)]]}}};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1, 1, 1] matrix[1, 1] value = owens_t(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // owens_t(array[]real,real)=>array[]real
    {
      array[1] real arg_1 = {(0.45000000000000001 + 0.0625 * seed)};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1] real value = owens_t(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // owens_t(array[]vector,real)=>array[]vector
    {
      array[1] vector[1] arg_1 = {[(0.45000000000000001 + 0.0625 * seed)]'};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1] vector[1] value = owens_t(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // owens_t(real,array[,,,,,]real)=>array[,,,,,]real
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1] real arg_2 = {{{{{{(1.2 + 0.0625 * seed)}}}}}};
      array[1, 1, 1, 1, 1, 1] real value = owens_t(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // pow(array[,,,,,,,]real,array[,,,,,,,]real)=>array[,,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{{{(0.45000000000000001 + 0.0625 * seed)}}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1, 1] real arg_2 = {{{{{{{{(1.2 + 0.0625 * seed)}}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1, 1] real value = pow(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // pow(array[,,,,,,]int,int)=>array[,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{{0}}}}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1, 1, 1, 1] real value = pow(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // pow(array[,,,,,,]row_vector,array[,,,,,,]row_vector)=>array[,,,,,,]row_vector
    {
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{{{[(0.45000000000000001 + 0.0625 * seed)]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] arg_2 = {{{{{{{[(1.2 + 0.0625 * seed)]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] value = pow(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // pow(array[,,,,,]row_vector,int)=>array[,,,,,]row_vector
    {
      array[1, 1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{{[(0.45000000000000001 + 0.0625 * seed)]}}}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1, 1, 1] row_vector[1] value = pow(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // pow(array[,,,,]vector,int)=>array[,,,,]vector
    {
      array[1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1, 1] vector[1] value = pow(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // pow(array[,]vector,real)=>array[,]vector
    {
      array[1, 1] vector[1] arg_1 = {{[(0.45000000000000001 + 0.0625 * seed)]'}};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1, 1] vector[1] value = pow(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // pow(int,array[,,,,,,,]int)=>array[,,,,,,,]real
    {
      int arg_1 = 0;
      array[1, 1, 1, 1, 1, 1, 1, 1] int arg_2 = {{{{{{{{1}}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1, 1] real value = pow(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // pow(real,array[,,,,,,]vector)=>array[,,,,,,]vector
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1, 1] vector[1] arg_2 = {{{{{{{[(1.2 + 0.0625 * seed)]'}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] vector[1] value = pow(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // pow(real,array[,,,,]matrix)=>array[,,,,]matrix
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{{[[(1.2 + 0.0625 * seed)]]}}}}};
      array[1, 1, 1, 1, 1] matrix[1, 1] value = pow(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // rep_array(matrix,int,int,int)=>array[,,]matrix
    {
      matrix[1, 1] arg_1 = [[(0.45000000000000001 + 0.0625 * seed)]];
      array[1, 1, 1] matrix[1, 1] value = rep_array(arg_1, 1, 1, 1);
      if (seed > 1e100)
        print(value);
    }
    // reverse(array[,,,,,,]vector)=>array[,,,,,,]vector
    {
      array[1, 1, 1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] vector[1] value = reverse(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // reverse(array[]int)=>array[]int
    {
      array[1] int arg_1 = {1};
      array[1] int value = reverse(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // reverse(vector)=>vector
    {
      vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)]';
      vector[1] value = reverse(arg_1);
      total += 1.03125 * sum(value);
    }
    // rising_factorial(array[,]vector,int)=>array[,]vector
    {
      array[1, 1] vector[1] arg_1 = {{[(1.45 + 0.0625 * seed)]'}};
      int arg_2 = 2;
      array[1, 1] vector[1] value = rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // rising_factorial(array[]row_vector,int)=>array[]row_vector
    {
      array[1] row_vector[1] arg_1 = {[(1.45 + 0.0625 * seed)]};
      int arg_2 = 2;
      array[1] row_vector[1] value = rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // rising_factorial(vector,int)=>vector
    {
      vector[1] arg_1 = [(1.45 + 0.0625 * seed)]';
      int arg_2 = 2;
      vector[1] value = rising_factorial(arg_1, arg_2);
      total += 1.203125 * sum(value);
    }
    // sinh(array[,,,]real)=>array[,,,]real
    {
      array[1, 1, 1, 1] real arg_1 = {{{{(0.45000000000000001 + 0.0625 * seed)}}}};
      array[1, 1, 1, 1] real value = sinh(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // sinh(array[]real)=>array[]real
    {
      array[1] real arg_1 = {(0.45000000000000001 + 0.0625 * seed)};
      array[1] real value = sinh(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // softmax(array[]row_vector)=>array[]row_vector
    {
      array[1] row_vector[1] arg_1 = {[(0.45000000000000001 + 0.0625 * seed)]};
      array[1] row_vector[1] value = softmax(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // sqrt(array[,,,,,,]vector)=>array[,,,,,,]vector
    {
      array[1, 1, 1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{{{[(1.3499999999999999 + 0.0625 * seed)]'}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] vector[1] value = sqrt(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // square(array[,,,,,,]row_vector)=>array[,,,,,,]row_vector
    {
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{{{[(0.45000000000000001 + 0.0625 * seed)]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] value = square(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // std_normal_log_qf(array[,,,]vector)=>array[,,,]vector
    {
      array[1, 1, 1, 1] vector[1] arg_1 = {{{{[(-0.55000000000000004 + 0.0625 * seed)]'}}}};
      array[1, 1, 1, 1] vector[1] value = std_normal_log_qf(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // std_normal_qf(array[,,,,]matrix)=>array[,,,,]matrix
    {
      array[1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}}};
      array[1, 1, 1, 1, 1] matrix[1, 1] value = std_normal_qf(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // tan(array[,,]matrix)=>array[,,]matrix
    {
      array[1, 1, 1] matrix[1, 1] arg_1 = {{{[[(0.45000000000000001 + 0.0625 * seed)]]}}};
      array[1, 1, 1] matrix[1, 1] value = tan(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // tgamma(array[,,,,,,]real)=>array[,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{{(0.45000000000000001 + 0.0625 * seed)}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] real value = tgamma(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // to_array_1d(array[]real)=>array[]real
    {
      array[1] real arg_1 = {(0.45000000000000001 + 0.0625 * seed)};
      array[1] real value = to_array_1d(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // to_matrix(array[]int,int,int,int)=>matrix
    {
      array[1] int arg_1 = {0};
      matrix[1, 1] value = to_matrix(arg_1, 1, 1, 1);
      total += 1.1875 * sum(value);
    }
    // to_matrix(array[]real,int,int)=>matrix
    {
      array[1] real arg_1 = {(0.45000000000000001 + 0.0625 * seed)};
      matrix[1, 1] value = to_matrix(arg_1, 1, 1);
      total += 1.03125 * sum(value);
    }
    // to_matrix(matrix,int,int,int)=>matrix
    {
      matrix[1, 1] arg_1 = [[(0.45000000000000001 + 0.0625 * seed)]];
      matrix[1, 1] value = to_matrix(arg_1, 1, 1, 1);
      total += 1.15625 * sum(value);
    }
    // trunc(array[,,,,,]row_vector)=>array[,,,,,]row_vector
    {
      array[1, 1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{{[(0.45000000000000001 + 0.0625 * seed)]}}}}}};
      array[1, 1, 1, 1, 1, 1] row_vector[1] value = trunc(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // trunc(array[,,,]matrix)=>array[,,,]matrix
    {
      array[1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}};
      array[1, 1, 1, 1] matrix[1, 1] value = trunc(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // trunc(array[,]row_vector)=>array[,]row_vector
    {
      array[1, 1] row_vector[1] arg_1 = {{[(0.45000000000000001 + 0.0625 * seed)]}};
      array[1, 1] row_vector[1] value = trunc(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // trunc(int)=>real
    {
      int arg_1 = 1;
      real value = trunc(arg_1);
      total += 1.1875 * value;
    }
    // variance(row_vector)=>real
    {
      row_vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)];
      real value = variance(arg_1);
      total += 1 * value;
    }
    return total;
  }
}
data {
  real context_seed;
}
transformed data {
  real transformed_data_result = builtin_signatures_24(context_seed);
}
parameters {
  real probe;
}
model {
  probe ~ std_normal();
  target += builtin_signatures_24(probe);
  if (probe > -1e100)
    target += builtin_signatures_24(probe);
}
generated quantities {
  real generated_quantities_result = builtin_signatures_24(probe);
}
