// STANLI-LIT: PASS
// STANLI-LIT-EXPECT: OK
// STANLI-LIT-DATA: {"context_seed": 0.0}
// STANLI-LIT-TIMEOUT: 180
// Generated by tools/generate_builtin_signature_models.py from the unified FunctionSpec registry
// and `stanc --dump-stan-math-signatures`. Do not edit by hand.
// Partition 21 of 30; 237 overloads.
functions {
  real builtin_signatures_21(real seed) {
    real total = 0;
    // Phi(array[,,,]int)=>array[,,,]real
    {
      array[1, 1, 1, 1] int arg_1 = {{{{1}}}};
      array[1, 1, 1, 1] real value = Phi(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // Phi(array[,,,]matrix)=>array[,,,]matrix
    {
      array[1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}};
      array[1, 1, 1, 1] matrix[1, 1] value = Phi(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // abs(array[,,]int)=>array[,,]int
    {
      array[1, 1, 1] int arg_1 = {{{2}}};
      array[1, 1, 1] int value = abs(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // acos(array[,,,]vector)=>array[,,,]vector
    {
      array[1, 1, 1, 1] vector[1] arg_1 = {{{{[(0.29999999999999999 + 0.0625 * seed)]'}}}};
      array[1, 1, 1, 1] vector[1] value = acos(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // acosh(array[,,]row_vector)=>array[,,]row_vector
    {
      array[1, 1, 1] row_vector[1] arg_1 = {{{[(1.3499999999999999 + 0.0625 * seed)]}}};
      array[1, 1, 1] row_vector[1] value = acosh(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // append_array(array[,,,,,,]row_vector,array[,,,,,,]row_vector)=>array[,,,,,,]row_vector
    {
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{{{[(0.45000000000000001 + 0.0625 * seed)]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] arg_2 = {{{{{{{[(1.2 + 0.0625 * seed)]}}}}}}};
      array[2, 1, 1, 1, 1, 1, 1] row_vector[1] value = append_array(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // append_row(vector,real)=>vector
    {
      vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)]';
      real arg_2 = (1.2 + 0.0625 * seed);
      vector[2] value = append_row(arg_1, arg_2);
      total += 1.234375 * sum(value);
    }
    // asin(matrix)=>matrix
    {
      matrix[1, 1] arg_1 = [[(0.29999999999999999 + 0.0625 * seed)]];
      matrix[1, 1] value = asin(arg_1);
      total += 1.140625 * sum(value);
    }
    // asinh(array[,,]row_vector)=>array[,,]row_vector
    {
      array[1, 1, 1] row_vector[1] arg_1 = {{{[(0.45000000000000001 + 0.0625 * seed)]}}};
      array[1, 1, 1] row_vector[1] value = asinh(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // asinh(array[,]real)=>array[,]real
    {
      array[1, 1] real arg_1 = {{(0.45000000000000001 + 0.0625 * seed)}};
      array[1, 1] real value = asinh(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // asinh(array[,]row_vector)=>array[,]row_vector
    {
      array[1, 1] row_vector[1] arg_1 = {{[(0.45000000000000001 + 0.0625 * seed)]}};
      array[1, 1] row_vector[1] value = asinh(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // asinh(row_vector)=>row_vector
    {
      row_vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)];
      row_vector[1] value = asinh(arg_1);
      total += 1.21875 * sum(value);
    }
    // atan2(array[,,,,,]matrix,int)=>array[,,,,,]matrix
    {
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] value = atan2(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // atan2(array[,,,]row_vector,real)=>array[,,,]row_vector
    {
      array[1, 1, 1, 1] row_vector[1] arg_1 = {{{{[(0.45000000000000001 + 0.0625 * seed)]}}}};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1, 1, 1, 1] row_vector[1] value = atan2(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // atan2(array[,]matrix,int)=>array[,]matrix
    {
      array[1, 1] matrix[1, 1] arg_1 = {{[[(0.45000000000000001 + 0.0625 * seed)]]}};
      int arg_2 = 1;
      array[1, 1] matrix[1, 1] value = atan2(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // atan2(array[,]real,array[,]real)=>array[,]real
    {
      array[1, 1] real arg_1 = {{(0.45000000000000001 + 0.0625 * seed)}};
      array[1, 1] real arg_2 = {{(1.2 + 0.0625 * seed)}};
      array[1, 1] real value = atan2(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // atan2(array[]matrix,real)=>array[]matrix
    {
      array[1] matrix[1, 1] arg_1 = {[[(0.45000000000000001 + 0.0625 * seed)]]};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1] matrix[1, 1] value = atan2(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // atanh(array[,,,,,,]int)=>array[,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{{0}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] real value = atanh(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // bessel_first_kind(array[,,,,,,]int,array[,,,,,]row_vector)=>array[,,,,,]row_vector
    {
      array[1, 1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{{2}}}}}}};
      array[1, 1, 1, 1, 1, 1] row_vector[1] arg_2 = {{{{{{[(1.3499999999999999 + 0.0625 * seed)]}}}}}};
      array[1, 1, 1, 1, 1, 1] row_vector[1] value = bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // bessel_first_kind(array[,,]int,array[,]row_vector)=>array[,]row_vector
    {
      array[1, 1, 1] int arg_1 = {{{2}}};
      array[1, 1] row_vector[1] arg_2 = {{[(1.3499999999999999 + 0.0625 * seed)]}};
      array[1, 1] row_vector[1] value = bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // bessel_first_kind(int,array[,]real)=>array[,]real
    {
      int arg_1 = 2;
      array[1, 1] real arg_2 = {{(1.3499999999999999 + 0.0625 * seed)}};
      array[1, 1] real value = bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // bessel_second_kind(int,matrix)=>matrix
    {
      int arg_1 = 2;
      matrix[1, 1] arg_2 = [[(1.3499999999999999 + 0.0625 * seed)]];
      matrix[1, 1] value = bessel_second_kind(arg_1, arg_2);
      total += 1.0625 * sum(value);
    }
    // beta(array[,,,,,,]int,int)=>array[,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{{2}}}}}}};
      int arg_2 = 3;
      array[1, 1, 1, 1, 1, 1, 1] real value = beta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // beta(array[,,,,,,]matrix,real)=>array[,,,,,,]matrix
    {
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{{{[[(1.95 + 0.0625 * seed)]]}}}}}}};
      real arg_2 = (2.9500000000000002 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] value = beta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // beta(array[,,,,,,]vector,int)=>array[,,,,,,]vector
    {
      array[1, 1, 1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{{{[(1.95 + 0.0625 * seed)]'}}}}}}};
      int arg_2 = 3;
      array[1, 1, 1, 1, 1, 1, 1] vector[1] value = beta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // beta(array[]int,array[]int)=>array[]real
    {
      array[1] int arg_1 = {2};
      array[1] int arg_2 = {3};
      array[1] real value = beta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // beta(array[]int,int)=>array[]real
    {
      array[1] int arg_1 = {2};
      int arg_2 = 3;
      array[1] real value = beta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // beta(int,array[,,,,,,]vector)=>array[,,,,,,]vector
    {
      int arg_1 = 2;
      array[1, 1, 1, 1, 1, 1, 1] vector[1] arg_2 = {{{{{{{[(2.9500000000000002 + 0.0625 * seed)]'}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] vector[1] value = beta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // beta(int,array[,,,,]int)=>array[,,,,]real
    {
      int arg_1 = 2;
      array[1, 1, 1, 1, 1] int arg_2 = {{{{{3}}}}};
      array[1, 1, 1, 1, 1] real value = beta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // beta(real,array[,,,,]matrix)=>array[,,,,]matrix
    {
      real arg_1 = (1.95 + 0.0625 * seed);
      array[1, 1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{{[[(2.9500000000000002 + 0.0625 * seed)]]}}}}};
      array[1, 1, 1, 1, 1] matrix[1, 1] value = beta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // cbrt(array[,,,,,]row_vector)=>array[,,,,,]row_vector
    {
      array[1, 1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{{[(0.45000000000000001 + 0.0625 * seed)]}}}}}};
      array[1, 1, 1, 1, 1, 1] row_vector[1] value = cbrt(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // cos(array[,,,,]int)=>array[,,,,]real
    {
      array[1, 1, 1, 1, 1] int arg_1 = {{{{{1}}}}};
      array[1, 1, 1, 1, 1] real value = cos(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // cosh(array[,,,]real)=>array[,,,]real
    {
      array[1, 1, 1, 1] real arg_1 = {{{{(0.45000000000000001 + 0.0625 * seed)}}}};
      array[1, 1, 1, 1] real value = cosh(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // cosh(array[,,]matrix)=>array[,,]matrix
    {
      array[1, 1, 1] matrix[1, 1] arg_1 = {{{[[(0.45000000000000001 + 0.0625 * seed)]]}}};
      array[1, 1, 1] matrix[1, 1] value = cosh(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // cosh(array[,,]real)=>array[,,]real
    {
      array[1, 1, 1] real arg_1 = {{{(0.45000000000000001 + 0.0625 * seed)}}};
      array[1, 1, 1] real value = cosh(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // cosh(array[,]int)=>array[,]real
    {
      array[1, 1] int arg_1 = {{1}};
      array[1, 1] real value = cosh(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // digamma(array[]vector)=>array[]vector
    {
      array[1] vector[1] arg_1 = {[(1.3499999999999999 + 0.0625 * seed)]'};
      array[1] vector[1] value = digamma(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // digamma(real)=>real
    {
      real arg_1 = (1.3499999999999999 + 0.0625 * seed);
      real value = digamma(arg_1);
      total += 1.03125 * value;
    }
    // elt_multiply(int,int)=>int
    {
      int arg_1 = 2;
      int arg_2 = 3;
      int value = elt_multiply(arg_1, arg_2);
      total += 1.109375 * value;
    }
    // erf(array[,,]int)=>array[,,]real
    {
      array[1, 1, 1] int arg_1 = {{{1}}};
      array[1, 1, 1] real value = erf(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // erfc(array[,,,,,,]vector)=>array[,,,,,,]vector
    {
      array[1, 1, 1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] vector[1] value = erfc(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // exp2(array[,,]int)=>array[,,]real
    {
      array[1, 1, 1] int arg_1 = {{{1}}};
      array[1, 1, 1] real value = exp2(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // expm1(array[,,,,,,]int)=>array[,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{{1}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] real value = expm1(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // expm1(array[,,,,]real)=>array[,,,,]real
    {
      array[1, 1, 1, 1, 1] real arg_1 = {{{{{(0.45000000000000001 + 0.0625 * seed)}}}}};
      array[1, 1, 1, 1, 1] real value = expm1(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // falling_factorial(array[,,,,,,]matrix,array[,,,,,,,,]int)=>array[,,,,,,]matrix
    {
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{{{[[(3.4500000000000002 + 0.0625 * seed)]]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1, 1, 1] int arg_2 = {{{{{{{{{2}}}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] value = falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // falling_factorial(array[,,,,,,]matrix,int)=>array[,,,,,,]matrix
    {
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{{{[[(3.4500000000000002 + 0.0625 * seed)]]}}}}}}};
      int arg_2 = 2;
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] value = falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // falling_factorial(array[,,,,,,]real,array[,,,,,,]int)=>array[,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{{(3.4500000000000002 + 0.0625 * seed)}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] int arg_2 = {{{{{{{2}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] real value = falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // falling_factorial(array[,]vector,array[,,]int)=>array[,]vector
    {
      array[1, 1] vector[1] arg_1 = {{[(3.4500000000000002 + 0.0625 * seed)]'}};
      array[1, 1, 1] int arg_2 = {{{2}}};
      array[1, 1] vector[1] value = falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // falling_factorial(array[]row_vector,array[,]int)=>array[]row_vector
    {
      array[1] row_vector[1] arg_1 = {[(3.4500000000000002 + 0.0625 * seed)]};
      array[1, 1] int arg_2 = {{2}};
      array[1] row_vector[1] value = falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fdim(array[,,,,]matrix,real)=>array[,,,,]matrix
    {
      array[1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{[[(0.94999999999999996 + 0.0625 * seed)]]}}}}};
      real arg_2 = (0.94999999999999996 + 0.0625 * seed);
      array[1, 1, 1, 1, 1] matrix[1, 1] value = fdim(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fdim(array[,,,,]real,array[,,,,]real)=>array[,,,,]real
    {
      array[1, 1, 1, 1, 1] real arg_1 = {{{{{(0.94999999999999996 + 0.0625 * seed)}}}}};
      array[1, 1, 1, 1, 1] real arg_2 = {{{{{(0.94999999999999996 + 0.0625 * seed)}}}}};
      array[1, 1, 1, 1, 1] real value = fdim(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fdim(array[]matrix,array[]matrix)=>array[]matrix
    {
      array[1] matrix[1, 1] arg_1 = {[[(0.94999999999999996 + 0.0625 * seed)]]};
      array[1] matrix[1, 1] arg_2 = {[[(0.94999999999999996 + 0.0625 * seed)]]};
      array[1] matrix[1, 1] value = fdim(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fdim(array[]vector,int)=>array[]vector
    {
      array[1] vector[1] arg_1 = {[(0.94999999999999996 + 0.0625 * seed)]'};
      int arg_2 = 1;
      array[1] vector[1] value = fdim(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fdim(int,array[,,,,,,]real)=>array[,,,,,,]real
    {
      int arg_1 = 1;
      array[1, 1, 1, 1, 1, 1, 1] real arg_2 = {{{{{{{(0.94999999999999996 + 0.0625 * seed)}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] real value = fdim(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fdim(int,array[,,,,]matrix)=>array[,,,,]matrix
    {
      int arg_1 = 1;
      array[1, 1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{{[[(0.94999999999999996 + 0.0625 * seed)]]}}}}};
      array[1, 1, 1, 1, 1] matrix[1, 1] value = fdim(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fdim(int,array[,,,,]row_vector)=>array[,,,,]row_vector
    {
      int arg_1 = 1;
      array[1, 1, 1, 1, 1] row_vector[1] arg_2 = {{{{{[(0.94999999999999996 + 0.0625 * seed)]}}}}};
      array[1, 1, 1, 1, 1] row_vector[1] value = fdim(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fdim(real,array[,]row_vector)=>array[,]row_vector
    {
      real arg_1 = (0.94999999999999996 + 0.0625 * seed);
      array[1, 1] row_vector[1] arg_2 = {{[(0.94999999999999996 + 0.0625 * seed)]}};
      array[1, 1] row_vector[1] value = fdim(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // floor(array[,,,,,,]row_vector)=>array[,,,,,,]row_vector
    {
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{{{[(0.45000000000000001 + 0.0625 * seed)]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] value = floor(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // floor(array[,,,,]row_vector)=>array[,,,,]row_vector
    {
      array[1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{[(0.45000000000000001 + 0.0625 * seed)]}}}}};
      array[1, 1, 1, 1, 1] row_vector[1] value = floor(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // fmax(array[,,,,,,]row_vector,int)=>array[,,,,,,]row_vector
    {
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{{{[(0.94999999999999996 + 0.0625 * seed)]}}}}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] value = fmax(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmax(array[,,,,,]vector,array[,,,,,]vector)=>array[,,,,,]vector
    {
      array[1, 1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{{[(0.94999999999999996 + 0.0625 * seed)]'}}}}}};
      array[1, 1, 1, 1, 1, 1] vector[1] arg_2 = {{{{{{[(0.94999999999999996 + 0.0625 * seed)]'}}}}}};
      array[1, 1, 1, 1, 1, 1] vector[1] value = fmax(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmax(array[,,,,,]vector,real)=>array[,,,,,]vector
    {
      array[1, 1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{{[(0.94999999999999996 + 0.0625 * seed)]'}}}}}};
      real arg_2 = (0.94999999999999996 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1] vector[1] value = fmax(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmax(array[,,]real,int)=>array[,,]real
    {
      array[1, 1, 1] real arg_1 = {{{(0.94999999999999996 + 0.0625 * seed)}}};
      int arg_2 = 1;
      array[1, 1, 1] real value = fmax(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmax(array[]int,real)=>array[]real
    {
      array[1] int arg_1 = {1};
      real arg_2 = (0.94999999999999996 + 0.0625 * seed);
      array[1] real value = fmax(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmax(array[]real,real)=>array[]real
    {
      array[1] real arg_1 = {(0.94999999999999996 + 0.0625 * seed)};
      real arg_2 = (0.94999999999999996 + 0.0625 * seed);
      array[1] real value = fmax(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmax(int,array[,,,,,]matrix)=>array[,,,,,]matrix
    {
      int arg_1 = 1;
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{{{[[(0.94999999999999996 + 0.0625 * seed)]]}}}}}};
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] value = fmax(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmax(int,real)=>real
    {
      int arg_1 = 1;
      real arg_2 = (0.94999999999999996 + 0.0625 * seed);
      real value = fmax(arg_1, arg_2);
      total += 1.046875 * value;
    }
    // fmax(real,array[]vector)=>array[]vector
    {
      real arg_1 = (0.94999999999999996 + 0.0625 * seed);
      array[1] vector[1] arg_2 = {[(0.94999999999999996 + 0.0625 * seed)]'};
      array[1] vector[1] value = fmax(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmax(vector,vector)=>vector
    {
      vector[1] arg_1 = [(0.94999999999999996 + 0.0625 * seed)]';
      vector[1] arg_2 = [(0.94999999999999996 + 0.0625 * seed)]';
      vector[1] value = fmax(arg_1, arg_2);
      total += 1 * sum(value);
    }
    // fmin(array[,,,,,]matrix,real)=>array[,,,,,]matrix
    {
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{{[[(0.94999999999999996 + 0.0625 * seed)]]}}}}}};
      real arg_2 = (0.94999999999999996 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] value = fmin(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmin(array[,,,,]real,int)=>array[,,,,]real
    {
      array[1, 1, 1, 1, 1] real arg_1 = {{{{{(0.94999999999999996 + 0.0625 * seed)}}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1, 1] real value = fmin(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmin(int,array[,,,,,]row_vector)=>array[,,,,,]row_vector
    {
      int arg_1 = 1;
      array[1, 1, 1, 1, 1, 1] row_vector[1] arg_2 = {{{{{{[(0.94999999999999996 + 0.0625 * seed)]}}}}}};
      array[1, 1, 1, 1, 1, 1] row_vector[1] value = fmin(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmod(array[,,,,,,,]int,int)=>array[,,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{{{2}}}}}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1, 1, 1, 1, 1] real value = fmod(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmod(array[,,,,,,,]real,int)=>array[,,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{{{(2.4500000000000002 + 0.0625 * seed)}}}}}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1, 1, 1, 1, 1] real value = fmod(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmod(array[,,,,,,]real,int)=>array[,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{{(2.4500000000000002 + 0.0625 * seed)}}}}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1, 1, 1, 1] real value = fmod(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmod(array[,,,,]real,array[,,,,]real)=>array[,,,,]real
    {
      array[1, 1, 1, 1, 1] real arg_1 = {{{{{(2.4500000000000002 + 0.0625 * seed)}}}}};
      array[1, 1, 1, 1, 1] real arg_2 = {{{{{(0.94999999999999996 + 0.0625 * seed)}}}}};
      array[1, 1, 1, 1, 1] real value = fmod(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmod(array[,,,,]vector,array[,,,,]vector)=>array[,,,,]vector
    {
      array[1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{[(2.4500000000000002 + 0.0625 * seed)]'}}}}};
      array[1, 1, 1, 1, 1] vector[1] arg_2 = {{{{{[(0.94999999999999996 + 0.0625 * seed)]'}}}}};
      array[1, 1, 1, 1, 1] vector[1] value = fmod(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmod(array[,,,]row_vector,array[,,,]row_vector)=>array[,,,]row_vector
    {
      array[1, 1, 1, 1] row_vector[1] arg_1 = {{{{[(2.4500000000000002 + 0.0625 * seed)]}}}};
      array[1, 1, 1, 1] row_vector[1] arg_2 = {{{{[(0.94999999999999996 + 0.0625 * seed)]}}}};
      array[1, 1, 1, 1] row_vector[1] value = fmod(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmod(array[,,,]row_vector,real)=>array[,,,]row_vector
    {
      array[1, 1, 1, 1] row_vector[1] arg_1 = {{{{[(2.4500000000000002 + 0.0625 * seed)]}}}};
      real arg_2 = (0.94999999999999996 + 0.0625 * seed);
      array[1, 1, 1, 1] row_vector[1] value = fmod(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmod(array[,]vector,array[,]vector)=>array[,]vector
    {
      array[1, 1] vector[1] arg_1 = {{[(2.4500000000000002 + 0.0625 * seed)]'}};
      array[1, 1] vector[1] arg_2 = {{[(0.94999999999999996 + 0.0625 * seed)]'}};
      array[1, 1] vector[1] value = fmod(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmod(int,array[,]vector)=>array[,]vector
    {
      int arg_1 = 2;
      array[1, 1] vector[1] arg_2 = {{[(0.94999999999999996 + 0.0625 * seed)]'}};
      array[1, 1] vector[1] value = fmod(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // fmod(real,array[,,,,,]int)=>array[,,,,,]real
    {
      real arg_1 = (2.4500000000000002 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1] int arg_2 = {{{{{{1}}}}}};
      array[1, 1, 1, 1, 1, 1] real value = fmod(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // gamma_p(array[,,]vector,real)=>array[,,]vector
    {
      array[1, 1, 1] vector[1] arg_1 = {{{[(1.95 + 0.0625 * seed)]'}}};
      real arg_2 = (1.25 + 0.0625 * seed);
      array[1, 1, 1] vector[1] value = gamma_p(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // gamma_p(real,array[,,,,,,,]real)=>array[,,,,,,,]real
    {
      real arg_1 = (1.95 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1, 1, 1] real arg_2 = {{{{{{{{(1.25 + 0.0625 * seed)}}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1, 1] real value = gamma_p(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // gamma_p(real,array[,]row_vector)=>array[,]row_vector
    {
      real arg_1 = (1.95 + 0.0625 * seed);
      array[1, 1] row_vector[1] arg_2 = {{[(1.25 + 0.0625 * seed)]}};
      array[1, 1] row_vector[1] value = gamma_p(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // gamma_q(array[,,,,,]real,real)=>array[,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{(1.95 + 0.0625 * seed)}}}}}};
      real arg_2 = (1.25 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1] real value = gamma_q(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // gamma_q(real,array[,,,,,,]row_vector)=>array[,,,,,,]row_vector
    {
      real arg_1 = (1.95 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] arg_2 = {{{{{{{[(1.25 + 0.0625 * seed)]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] value = gamma_q(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // hypot(array[,,,,,,]int,real)=>array[,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{{0}}}}}}};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1, 1] real value = hypot(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // hypot(array[,,,]matrix,real)=>array[,,,]matrix
    {
      array[1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1, 1, 1, 1] matrix[1, 1] value = hypot(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // hypot(array[,,]int,int)=>array[,,]real
    {
      array[1, 1, 1] int arg_1 = {{{0}}};
      int arg_2 = 1;
      array[1, 1, 1] real value = hypot(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // hypot(array[,]row_vector,real)=>array[,]row_vector
    {
      array[1, 1] row_vector[1] arg_1 = {{[(0.45000000000000001 + 0.0625 * seed)]}};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1, 1] row_vector[1] value = hypot(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // hypot(array[]vector,real)=>array[]vector
    {
      array[1] vector[1] arg_1 = {[(0.45000000000000001 + 0.0625 * seed)]'};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1] vector[1] value = hypot(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // hypot(int,array[,,,,,]real)=>array[,,,,,]real
    {
      int arg_1 = 0;
      array[1, 1, 1, 1, 1, 1] real arg_2 = {{{{{{(1.2 + 0.0625 * seed)}}}}}};
      array[1, 1, 1, 1, 1, 1] real value = hypot(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // hypot(int,array[,,,]vector)=>array[,,,]vector
    {
      int arg_1 = 0;
      array[1, 1, 1, 1] vector[1] arg_2 = {{{{[(1.2 + 0.0625 * seed)]'}}}};
      array[1, 1, 1, 1] vector[1] value = hypot(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // hypot(int,matrix)=>matrix
    {
      int arg_1 = 0;
      matrix[1, 1] arg_2 = [[(1.2 + 0.0625 * seed)]];
      matrix[1, 1] value = hypot(arg_1, arg_2);
      total += 1.171875 * sum(value);
    }
    // inv(array[,,,,,,]row_vector)=>array[,,,,,,]row_vector
    {
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{{{[(0.45000000000000001 + 0.0625 * seed)]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] value = inv(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // inv_Phi(array[,,,,]matrix)=>array[,,,,]matrix
    {
      array[1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}}};
      array[1, 1, 1, 1, 1] matrix[1, 1] value = inv_Phi(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // inv_Phi(array[]real)=>array[]real
    {
      array[1] real arg_1 = {(0.45000000000000001 + 0.0625 * seed)};
      array[1] real value = inv_Phi(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // inv_erfc(array[]row_vector)=>array[]row_vector
    {
      array[1] row_vector[1] arg_1 = {[(0.45000000000000001 + 0.0625 * seed)]};
      array[1] row_vector[1] value = inv_erfc(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // inv_logit(array[,,,,,]real)=>array[,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{(0.45000000000000001 + 0.0625 * seed)}}}}}};
      array[1, 1, 1, 1, 1, 1] real value = inv_logit(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // inv_logit(array[,,,]vector)=>array[,,,]vector
    {
      array[1, 1, 1, 1] vector[1] arg_1 = {{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}};
      array[1, 1, 1, 1] vector[1] value = inv_logit(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // inv_sqrt(array[,,]vector)=>array[,,]vector
    {
      array[1, 1, 1] vector[1] arg_1 = {{{[(1.3499999999999999 + 0.0625 * seed)]'}}};
      array[1, 1, 1] vector[1] value = inv_sqrt(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // inv_sqrt(array[,]vector)=>array[,]vector
    {
      array[1, 1] vector[1] arg_1 = {{[(1.3499999999999999 + 0.0625 * seed)]'}};
      array[1, 1] vector[1] value = inv_sqrt(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // inv_square(array[,,,,,]real)=>array[,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{(0.45000000000000001 + 0.0625 * seed)}}}}}};
      array[1, 1, 1, 1, 1, 1] real value = inv_square(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // inv_square(array[,]matrix)=>array[,]matrix
    {
      array[1, 1] matrix[1, 1] arg_1 = {{[[(0.45000000000000001 + 0.0625 * seed)]]}};
      array[1, 1] matrix[1, 1] value = inv_square(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // lambert_w0(array[,,,,]matrix)=>array[,,,,]matrix
    {
      array[1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}}};
      array[1, 1, 1, 1, 1] matrix[1, 1] value = lambert_w0(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // lambert_w0(array[,,]matrix)=>array[,,]matrix
    {
      array[1, 1, 1] matrix[1, 1] arg_1 = {{{[[(0.45000000000000001 + 0.0625 * seed)]]}}};
      array[1, 1, 1] matrix[1, 1] value = lambert_w0(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // lambert_wm1(array[,,,]matrix)=>array[,,,]matrix
    {
      array[1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{[[(-0.25 + 0.0625 * seed)]]}}}};
      array[1, 1, 1, 1] matrix[1, 1] value = lambert_wm1(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // lambert_wm1(array[]vector)=>array[]vector
    {
      array[1] vector[1] arg_1 = {[(-0.25 + 0.0625 * seed)]'};
      array[1] vector[1] value = lambert_wm1(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // lbeta(array[,,,,,]int,real)=>array[,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{2}}}}}};
      real arg_2 = (2.9500000000000002 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1] real value = lbeta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lbeta(array[]int,int)=>array[]real
    {
      array[1] int arg_1 = {2};
      int arg_2 = 3;
      array[1] real value = lbeta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lbeta(array[]matrix,real)=>array[]matrix
    {
      array[1] matrix[1, 1] arg_1 = {[[(1.95 + 0.0625 * seed)]]};
      real arg_2 = (2.9500000000000002 + 0.0625 * seed);
      array[1] matrix[1, 1] value = lbeta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lbeta(int,array[,,,]real)=>array[,,,]real
    {
      int arg_1 = 2;
      array[1, 1, 1, 1] real arg_2 = {{{{(2.9500000000000002 + 0.0625 * seed)}}}};
      array[1, 1, 1, 1] real value = lbeta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lbeta(real,array[,,,]int)=>array[,,,]real
    {
      real arg_1 = (1.95 + 0.0625 * seed);
      array[1, 1, 1, 1] int arg_2 = {{{{3}}}};
      array[1, 1, 1, 1] real value = lbeta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lbeta(real,array[,,]vector)=>array[,,]vector
    {
      real arg_1 = (1.95 + 0.0625 * seed);
      array[1, 1, 1] vector[1] arg_2 = {{{[(2.9500000000000002 + 0.0625 * seed)]'}}};
      array[1, 1, 1] vector[1] value = lbeta(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lchoose(array[,,,]matrix,array[,,,]matrix)=>array[,,,]matrix
    {
      array[1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{[[(3.9500000000000002 + 0.0625 * seed)]]}}}};
      array[1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{[[(1.95 + 0.0625 * seed)]]}}}};
      array[1, 1, 1, 1] matrix[1, 1] value = lchoose(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lchoose(array[,,,]vector,array[,,,]vector)=>array[,,,]vector
    {
      array[1, 1, 1, 1] vector[1] arg_1 = {{{{[(3.9500000000000002 + 0.0625 * seed)]'}}}};
      array[1, 1, 1, 1] vector[1] arg_2 = {{{{[(1.95 + 0.0625 * seed)]'}}}};
      array[1, 1, 1, 1] vector[1] value = lchoose(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lchoose(array[,]real,int)=>array[,]real
    {
      array[1, 1] real arg_1 = {{(3.9500000000000002 + 0.0625 * seed)}};
      int arg_2 = 2;
      array[1, 1] real value = lchoose(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // ldexp(array[,,,,]row_vector,int)=>array[,,,,]row_vector
    {
      array[1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{[(0.45000000000000001 + 0.0625 * seed)]}}}}};
      int arg_2 = 2;
      array[1, 1, 1, 1, 1] row_vector[1] value = ldexp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // ldexp(row_vector,array[]int)=>row_vector
    {
      row_vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)];
      array[1] int arg_2 = {2};
      row_vector[1] value = ldexp(arg_1, arg_2);
      total += 1.15625 * sum(value);
    }
    // lgamma(array[]vector)=>array[]vector
    {
      array[1] vector[1] arg_1 = {[(1.3499999999999999 + 0.0625 * seed)]'};
      array[1] vector[1] value = lgamma(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // lmultiply(array[,,,,,,]matrix,real)=>array[,,,,,,]matrix
    {
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}}}}};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] value = lmultiply(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lmultiply(array[,,,,]row_vector,real)=>array[,,,,]row_vector
    {
      array[1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{[(0.45000000000000001 + 0.0625 * seed)]}}}}};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1, 1, 1, 1, 1] row_vector[1] value = lmultiply(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lmultiply(array[]real,array[]real)=>array[]real
    {
      array[1] real arg_1 = {(0.45000000000000001 + 0.0625 * seed)};
      array[1] real arg_2 = {(1.2 + 0.0625 * seed)};
      array[1] real value = lmultiply(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lmultiply(array[]real,int)=>array[]real
    {
      array[1] real arg_1 = {(0.45000000000000001 + 0.0625 * seed)};
      int arg_2 = 1;
      array[1] real value = lmultiply(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // lmultiply(int,array[]matrix)=>array[]matrix
    {
      int arg_1 = 0;
      array[1] matrix[1, 1] arg_2 = {[[(1.2 + 0.0625 * seed)]]};
      array[1] matrix[1, 1] value = lmultiply(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log(vector)=>vector
    {
      vector[1] arg_1 = [(1.3499999999999999 + 0.0625 * seed)]';
      vector[1] value = log(arg_1);
      total += 1.015625 * sum(value);
    }
    // log1m(array[,,,,,]row_vector)=>array[,,,,,]row_vector
    {
      array[1, 1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{{[(0.29999999999999999 + 0.0625 * seed)]}}}}}};
      array[1, 1, 1, 1, 1, 1] row_vector[1] value = log1m(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log1m_inv_logit(array[,,]row_vector)=>array[,,]row_vector
    {
      array[1, 1, 1] row_vector[1] arg_1 = {{{[(0.45000000000000001 + 0.0625 * seed)]}}};
      array[1, 1, 1] row_vector[1] value = log1m_inv_logit(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log2(array[,,,,,]matrix)=>array[,,,,,]matrix
    {
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{{[[(1.3499999999999999 + 0.0625 * seed)]]}}}}}};
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] value = log2(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log2(array[]row_vector)=>array[]row_vector
    {
      array[1] row_vector[1] arg_1 = {[(1.3499999999999999 + 0.0625 * seed)]};
      array[1] row_vector[1] value = log2(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log2(row_vector)=>row_vector
    {
      row_vector[1] arg_1 = [(1.3499999999999999 + 0.0625 * seed)];
      row_vector[1] value = log2(arg_1);
      total += 1.25 * sum(value);
    }
    // log_diff_exp(array[,]real,array[,]real)=>array[,]real
    {
      array[1, 1] real arg_1 = {{(1.45 + 0.0625 * seed)}};
      array[1, 1] real arg_2 = {{(0.45000000000000001 + 0.0625 * seed)}};
      array[1, 1] real value = log_diff_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_diff_exp(array[]vector,real)=>array[]vector
    {
      array[1] vector[1] arg_1 = {[(1.45 + 0.0625 * seed)]'};
      real arg_2 = (0.45000000000000001 + 0.0625 * seed);
      array[1] vector[1] value = log_diff_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_diff_exp(int,array[,,]vector)=>array[,,]vector
    {
      int arg_1 = 1;
      array[1, 1, 1] vector[1] arg_2 = {{{[(0.45000000000000001 + 0.0625 * seed)]'}}};
      array[1, 1, 1] vector[1] value = log_diff_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_diff_exp(int,matrix)=>matrix
    {
      int arg_1 = 1;
      matrix[1, 1] arg_2 = [[(0.45000000000000001 + 0.0625 * seed)]];
      matrix[1, 1] value = log_diff_exp(arg_1, arg_2);
      total += 1.140625 * sum(value);
    }
    // log_diff_exp(real,array[,,,,,]matrix)=>array[,,,,,]matrix
    {
      real arg_1 = (1.45 + 0.0625 * seed);
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}}}};
      array[1, 1, 1, 1, 1, 1] matrix[1, 1] value = log_diff_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_falling_factorial(array[,,,,,]row_vector,int)=>array[,,,,,]row_vector
    {
      array[1, 1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{{[(3.4500000000000002 + 0.0625 * seed)]}}}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1, 1, 1] row_vector[1] value = log_falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_falling_factorial(array[,,,,,]vector,array[,,,,,]vector)=>array[,,,,,]vector
    {
      array[1, 1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{{[(3.4500000000000002 + 0.0625 * seed)]'}}}}}};
      array[1, 1, 1, 1, 1, 1] vector[1] arg_2 = {{{{{{[(1.1499999999999999 + 0.0625 * seed)]'}}}}}};
      array[1, 1, 1, 1, 1, 1] vector[1] value = log_falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_falling_factorial(array[,,,]int,array[,,,]int)=>array[,,,]real
    {
      array[1, 1, 1, 1] int arg_1 = {{{{3}}}};
      array[1, 1, 1, 1] int arg_2 = {{{{1}}}};
      array[1, 1, 1, 1] real value = log_falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_falling_factorial(array[,]matrix,int)=>array[,]matrix
    {
      array[1, 1] matrix[1, 1] arg_1 = {{[[(3.4500000000000002 + 0.0625 * seed)]]}};
      int arg_2 = 1;
      array[1, 1] matrix[1, 1] value = log_falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_falling_factorial(array[]real,real)=>array[]real
    {
      array[1] real arg_1 = {(3.4500000000000002 + 0.0625 * seed)};
      real arg_2 = (1.1499999999999999 + 0.0625 * seed);
      array[1] real value = log_falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_falling_factorial(int,array[,,,,,]int)=>array[,,,,,]real
    {
      int arg_1 = 3;
      array[1, 1, 1, 1, 1, 1] int arg_2 = {{{{{{1}}}}}};
      array[1, 1, 1, 1, 1, 1] real value = log_falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_falling_factorial(int,array[,,,,,]vector)=>array[,,,,,]vector
    {
      int arg_1 = 3;
      array[1, 1, 1, 1, 1, 1] vector[1] arg_2 = {{{{{{[(1.1499999999999999 + 0.0625 * seed)]'}}}}}};
      array[1, 1, 1, 1, 1, 1] vector[1] value = log_falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_falling_factorial(int,array[,,,]row_vector)=>array[,,,]row_vector
    {
      int arg_1 = 3;
      array[1, 1, 1, 1] row_vector[1] arg_2 = {{{{[(1.1499999999999999 + 0.0625 * seed)]}}}};
      array[1, 1, 1, 1] row_vector[1] value = log_falling_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_falling_factorial(int,real)=>real
    {
      int arg_1 = 3;
      real arg_2 = (1.1499999999999999 + 0.0625 * seed);
      real value = log_falling_factorial(arg_1, arg_2);
      total += 1.25 * value;
    }
    // log_inv_logit(array[]vector)=>array[]vector
    {
      array[1] vector[1] arg_1 = {[(0.45000000000000001 + 0.0625 * seed)]'};
      array[1] vector[1] value = log_inv_logit(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // log_inv_logit_diff(array[,,,,,,,]int,int)=>array[,,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{{{1}}}}}}}};
      int arg_2 = 0;
      array[1, 1, 1, 1, 1, 1, 1, 1] real value = log_inv_logit_diff(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_inv_logit_diff(array[,,,,]int,real)=>array[,,,,]real
    {
      array[1, 1, 1, 1, 1] int arg_1 = {{{{{1}}}}};
      real arg_2 = (-0.55000000000000004 + 0.0625 * seed);
      array[1, 1, 1, 1, 1] real value = log_inv_logit_diff(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_inv_logit_diff(array[,,]matrix,real)=>array[,,]matrix
    {
      array[1, 1, 1] matrix[1, 1] arg_1 = {{{[[(0.94999999999999996 + 0.0625 * seed)]]}}};
      real arg_2 = (-0.55000000000000004 + 0.0625 * seed);
      array[1, 1, 1] matrix[1, 1] value = log_inv_logit_diff(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_inv_logit_diff(array[,]row_vector,array[,]row_vector)=>array[,]row_vector
    {
      array[1, 1] row_vector[1] arg_1 = {{[(0.94999999999999996 + 0.0625 * seed)]}};
      array[1, 1] row_vector[1] arg_2 = {{[(-0.55000000000000004 + 0.0625 * seed)]}};
      array[1, 1] row_vector[1] value = log_inv_logit_diff(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_inv_logit_diff(int,array[,,,]int)=>array[,,,]real
    {
      int arg_1 = 1;
      array[1, 1, 1, 1] int arg_2 = {{{{0}}}};
      array[1, 1, 1, 1] real value = log_inv_logit_diff(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_inv_logit_diff(real,array[,,,,]row_vector)=>array[,,,,]row_vector
    {
      real arg_1 = (0.94999999999999996 + 0.0625 * seed);
      array[1, 1, 1, 1, 1] row_vector[1] arg_2 = {{{{{[(-0.55000000000000004 + 0.0625 * seed)]}}}}};
      array[1, 1, 1, 1, 1] row_vector[1] value = log_inv_logit_diff(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_modified_bessel_first_kind(array[,,,,,,,]int,array[,,,,,,,]int)=>array[,,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{{{0}}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1, 1] int arg_2 = {{{{{{{{1}}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1, 1] real value = log_modified_bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_modified_bessel_first_kind(array[,,,,,]row_vector,int)=>array[,,,,,]row_vector
    {
      array[1, 1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{{[(0.45000000000000001 + 0.0625 * seed)]}}}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1, 1, 1] row_vector[1] value = log_modified_bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_modified_bessel_first_kind(int,array[,,,,]real)=>array[,,,,]real
    {
      int arg_1 = 0;
      array[1, 1, 1, 1, 1] real arg_2 = {{{{{(1.2 + 0.0625 * seed)}}}}};
      array[1, 1, 1, 1, 1] real value = log_modified_bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_modified_bessel_first_kind(real,array[,,,,]int)=>array[,,,,]real
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1, 1, 1, 1] int arg_2 = {{{{{1}}}}};
      array[1, 1, 1, 1, 1] real value = log_modified_bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_modified_bessel_first_kind(real,array[,,]real)=>array[,,]real
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1, 1] real arg_2 = {{{(1.2 + 0.0625 * seed)}}};
      array[1, 1, 1] real value = log_modified_bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_modified_bessel_first_kind(real,array[]vector)=>array[]vector
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1] vector[1] arg_2 = {[(1.2 + 0.0625 * seed)]'};
      array[1] vector[1] value = log_modified_bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_rising_factorial(array[,,,,,,,]real,array[,,,,,,,]real)=>array[,,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{{{(1.45 + 0.0625 * seed)}}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1, 1] real arg_2 = {{{{{{{{(1.1499999999999999 + 0.0625 * seed)}}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1, 1] real value = log_rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_rising_factorial(array[,,,,,,]row_vector,int)=>array[,,,,,,]row_vector
    {
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{{{[(1.45 + 0.0625 * seed)]}}}}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] value = log_rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_rising_factorial(array[,,,]matrix,array[,,,]matrix)=>array[,,,]matrix
    {
      array[1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{[[(1.45 + 0.0625 * seed)]]}}}};
      array[1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{[[(1.1499999999999999 + 0.0625 * seed)]]}}}};
      array[1, 1, 1, 1] matrix[1, 1] value = log_rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_rising_factorial(array[,]int,int)=>array[,]real
    {
      array[1, 1] int arg_1 = {{1}};
      int arg_2 = 1;
      array[1, 1] real value = log_rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_rising_factorial(array[]real,array[]real)=>array[]real
    {
      array[1] real arg_1 = {(1.45 + 0.0625 * seed)};
      array[1] real arg_2 = {(1.1499999999999999 + 0.0625 * seed)};
      array[1] real value = log_rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_rising_factorial(array[]real,real)=>array[]real
    {
      array[1] real arg_1 = {(1.45 + 0.0625 * seed)};
      real arg_2 = (1.1499999999999999 + 0.0625 * seed);
      array[1] real value = log_rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_rising_factorial(int,array[,,]vector)=>array[,,]vector
    {
      int arg_1 = 1;
      array[1, 1, 1] vector[1] arg_2 = {{{[(1.1499999999999999 + 0.0625 * seed)]'}}};
      array[1, 1, 1] vector[1] value = log_rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_rising_factorial(real,array[,,,,]row_vector)=>array[,,,,]row_vector
    {
      real arg_1 = (1.45 + 0.0625 * seed);
      array[1, 1, 1, 1, 1] row_vector[1] arg_2 = {{{{{[(1.1499999999999999 + 0.0625 * seed)]}}}}};
      array[1, 1, 1, 1, 1] row_vector[1] value = log_rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_rising_factorial(real,array[,]matrix)=>array[,]matrix
    {
      real arg_1 = (1.45 + 0.0625 * seed);
      array[1, 1] matrix[1, 1] arg_2 = {{[[(1.1499999999999999 + 0.0625 * seed)]]}};
      array[1, 1] matrix[1, 1] value = log_rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_rising_factorial(real,array[]vector)=>array[]vector
    {
      real arg_1 = (1.45 + 0.0625 * seed);
      array[1] vector[1] arg_2 = {[(1.1499999999999999 + 0.0625 * seed)]'};
      array[1] vector[1] value = log_rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_sum_exp(array[,,,]real,array[,,,]real)=>array[,,,]real
    {
      array[1, 1, 1, 1] real arg_1 = {{{{(0.45000000000000001 + 0.0625 * seed)}}}};
      array[1, 1, 1, 1] real arg_2 = {{{{(1.2 + 0.0625 * seed)}}}};
      array[1, 1, 1, 1] real value = log_sum_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_sum_exp(array[,,]real,array[,,]real)=>array[,,]real
    {
      array[1, 1, 1] real arg_1 = {{{(0.45000000000000001 + 0.0625 * seed)}}};
      array[1, 1, 1] real arg_2 = {{{(1.2 + 0.0625 * seed)}}};
      array[1, 1, 1] real value = log_sum_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_sum_exp(array[,,]real,int)=>array[,,]real
    {
      array[1, 1, 1] real arg_1 = {{{(0.45000000000000001 + 0.0625 * seed)}}};
      int arg_2 = 1;
      array[1, 1, 1] real value = log_sum_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_sum_exp(int,array[,,,,,,]row_vector)=>array[,,,,,,]row_vector
    {
      int arg_1 = 0;
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] arg_2 = {{{{{{{[(1.2 + 0.0625 * seed)]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] row_vector[1] value = log_sum_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // log_sum_exp(real,array[,]row_vector)=>array[,]row_vector
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      array[1, 1] row_vector[1] arg_2 = {{[(1.2 + 0.0625 * seed)]}};
      array[1, 1] row_vector[1] value = log_sum_exp(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // logical_eq(int,real)=>int
    {
      int value = logical_eq(0, 1.2);
      total += 1.203125 * value;
    }
    // logical_neq(real,real)=>int
    {
      int value = logical_neq(0.45000000000000001, 1.2);
      total += 1.0625 * value;
    }
    // logit(array[,,,]row_vector)=>array[,,,]row_vector
    {
      array[1, 1, 1, 1] row_vector[1] arg_1 = {{{{[(0.29999999999999999 + 0.0625 * seed)]}}}};
      array[1, 1, 1, 1] row_vector[1] value = logit(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // logit(array[]real)=>array[]real
    {
      array[1] real arg_1 = {(0.29999999999999999 + 0.0625 * seed)};
      array[1] real value = logit(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // matrix_exp(matrix)=>matrix
    {
      matrix[1, 1] arg_1 = [[(0.45000000000000001 + 0.0625 * seed)]];
      matrix[1, 1] value = matrix_exp(arg_1);
      total += 1.140625 * sum(value);
    }
    // modified_bessel_first_kind(array[,,,,,,,]int,array[,,,,,,,]real)=>array[,,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1, 1] int arg_1 = {{{{{{{{2}}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1, 1] real arg_2 = {{{{{{{{(1.3499999999999999 + 0.0625 * seed)}}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1, 1] real value = modified_bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // modified_bessel_first_kind(array[,,,]int,array[,,]row_vector)=>array[,,]row_vector
    {
      array[1, 1, 1, 1] int arg_1 = {{{{2}}}};
      array[1, 1, 1] row_vector[1] arg_2 = {{{[(1.3499999999999999 + 0.0625 * seed)]}}};
      array[1, 1, 1] row_vector[1] value = modified_bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // modified_bessel_first_kind(array[,]int,array[]vector)=>array[]vector
    {
      array[1, 1] int arg_1 = {{2}};
      array[1] vector[1] arg_2 = {[(1.3499999999999999 + 0.0625 * seed)]'};
      array[1] vector[1] value = modified_bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // modified_bessel_first_kind(int,array[,,,,,,]matrix)=>array[,,,,,,]matrix
    {
      int arg_1 = 2;
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] arg_2 = {{{{{{{[[(1.3499999999999999 + 0.0625 * seed)]]}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] matrix[1, 1] value = modified_bessel_first_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // modified_bessel_second_kind(int,array[,,]matrix)=>array[,,]matrix
    {
      int arg_1 = 2;
      array[1, 1, 1] matrix[1, 1] arg_2 = {{{[[(1.3499999999999999 + 0.0625 * seed)]]}}};
      array[1, 1, 1] matrix[1, 1] value = modified_bessel_second_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // modified_bessel_second_kind(int,array[,,]row_vector)=>array[,,]row_vector
    {
      int arg_1 = 2;
      array[1, 1, 1] row_vector[1] arg_2 = {{{[(1.3499999999999999 + 0.0625 * seed)]}}};
      array[1, 1, 1] row_vector[1] value = modified_bessel_second_kind(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // modified_bessel_second_kind(int,real)=>real
    {
      int arg_1 = 2;
      real arg_2 = (1.3499999999999999 + 0.0625 * seed);
      real value = modified_bessel_second_kind(arg_1, arg_2);
      total += 1.03125 * value;
    }
    // multiply_lower_tri_self_transpose(matrix)=>matrix
    {
      matrix[1, 1] arg_1 = [[(0.45000000000000001 + 0.0625 * seed)]];
      matrix[1, 1] value = multiply_lower_tri_self_transpose(arg_1);
      total += 1.09375 * sum(value);
    }
    // num_elements(array[,,,,,]row_vector)=>int
    {
      array[1, 1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{{[(0.45000000000000001 + 0.0625 * seed)]}}}}}};
      int value = num_elements(arg_1);
      total += 1.046875 * value;
    }
    // num_elements(array[,,,,]real)=>int
    {
      array[1, 1, 1, 1, 1] real arg_1 = {{{{{(0.45000000000000001 + 0.0625 * seed)}}}}};
      int value = num_elements(arg_1);
      total += 1.21875 * value;
    }
    // owens_t(array[,,]row_vector,real)=>array[,,]row_vector
    {
      array[1, 1, 1] row_vector[1] arg_1 = {{{[(0.45000000000000001 + 0.0625 * seed)]}}};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1, 1, 1] row_vector[1] value = owens_t(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // owens_t(array[]vector,real)=>array[]vector
    {
      array[1] vector[1] arg_1 = {[(0.45000000000000001 + 0.0625 * seed)]'};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1] vector[1] value = owens_t(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // pow(array[,,,,]vector,int)=>array[,,,,]vector
    {
      array[1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}}};
      int arg_2 = 1;
      array[1, 1, 1, 1, 1] vector[1] value = pow(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // pow(array[,,,]int,array[,,,]int)=>array[,,,]real
    {
      array[1, 1, 1, 1] int arg_1 = {{{{0}}}};
      array[1, 1, 1, 1] int arg_2 = {{{{1}}}};
      array[1, 1, 1, 1] real value = pow(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // pow(array[,,]matrix,real)=>array[,,]matrix
    {
      array[1, 1, 1] matrix[1, 1] arg_1 = {{{[[(0.45000000000000001 + 0.0625 * seed)]]}}};
      real arg_2 = (1.2 + 0.0625 * seed);
      array[1, 1, 1] matrix[1, 1] value = pow(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // quad_form(matrix,matrix)=>matrix
    {
      matrix[1, 1] arg_1 = [[(0.45000000000000001 + 0.0625 * seed)]];
      matrix[1, 1] arg_2 = [[(1.2 + 0.0625 * seed)]];
      matrix[1, 1] value = quad_form(arg_1, arg_2);
      total += 1.203125 * sum(value);
    }
    // rep_array(array[]row_vector,int,int,int)=>array[,,,]row_vector
    {
      array[1] row_vector[1] arg_1 = {[(0.45000000000000001 + 0.0625 * seed)]};
      array[1, 1, 1, 1] row_vector[1] value = rep_array(arg_1, 1, 1, 1);
      if (seed > 1e100)
        print(value);
    }
    // reverse(array[,,,,]matrix)=>array[,,,,]matrix
    {
      array[1, 1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}}};
      array[1, 1, 1, 1, 1] matrix[1, 1] value = reverse(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // reverse(array[,,,,]vector)=>array[,,,,]vector
    {
      array[1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}}};
      array[1, 1, 1, 1, 1] vector[1] value = reverse(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // reverse(array[,,]real)=>array[,,]real
    {
      array[1, 1, 1] real arg_1 = {{{(0.45000000000000001 + 0.0625 * seed)}}};
      array[1, 1, 1] real value = reverse(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // rising_factorial(array[,,,,,,]real,array[,,,,,,]int)=>array[,,,,,,]real
    {
      array[1, 1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{{(1.45 + 0.0625 * seed)}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] int arg_2 = {{{{{{{2}}}}}}};
      array[1, 1, 1, 1, 1, 1, 1] real value = rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // rising_factorial(array[,,,,]vector,int)=>array[,,,,]vector
    {
      array[1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{[(1.45 + 0.0625 * seed)]'}}}}};
      int arg_2 = 2;
      array[1, 1, 1, 1, 1] vector[1] value = rising_factorial(arg_1, arg_2);
      if (seed > 1e100)
        print(value);
    }
    // rising_factorial(matrix,array[,]int)=>matrix
    {
      matrix[1, 1] arg_1 = [[(1.45 + 0.0625 * seed)]];
      array[1, 1] int arg_2 = {{2}};
      matrix[1, 1] value = rising_factorial(arg_1, arg_2);
      total += 1.03125 * sum(value);
    }
    // round(array[,]real)=>array[,]real
    {
      array[1, 1] real arg_1 = {{(0.45000000000000001 + 0.0625 * seed)}};
      array[1, 1] real value = round(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // sin(array[]matrix)=>array[]matrix
    {
      array[1] matrix[1, 1] arg_1 = {[[(0.45000000000000001 + 0.0625 * seed)]]};
      array[1] matrix[1, 1] value = sin(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // sinh(array[]matrix)=>array[]matrix
    {
      array[1] matrix[1, 1] arg_1 = {[[(0.45000000000000001 + 0.0625 * seed)]]};
      array[1] matrix[1, 1] value = sinh(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // size(array[]int)=>int
    {
      array[1] int arg_1 = {2};
      int value = size(arg_1);
      total += 1.109375 * value;
    }
    // size(array[]real)=>int
    {
      array[1] real arg_1 = {(0.45000000000000001 + 0.0625 * seed)};
      int value = size(arg_1);
      total += 1.0625 * value;
    }
    // sqrt(array[]real)=>array[]real
    {
      array[1] real arg_1 = {(1.3499999999999999 + 0.0625 * seed)};
      array[1] real value = sqrt(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // square(array[,,,,]int)=>array[,,,,]real
    {
      array[1, 1, 1, 1, 1] int arg_1 = {{{{{1}}}}};
      array[1, 1, 1, 1, 1] real value = square(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // square(array[,]matrix)=>array[,]matrix
    {
      array[1, 1] matrix[1, 1] arg_1 = {{[[(0.45000000000000001 + 0.0625 * seed)]]}};
      array[1, 1] matrix[1, 1] value = square(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // squared_distance(row_vector,row_vector)=>real
    {
      row_vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)];
      row_vector[1] arg_2 = [(1.2 + 0.0625 * seed)];
      real value = squared_distance(arg_1, arg_2);
      total += 1.140625 * value;
    }
    // squared_distance(vector,vector)=>real
    {
      vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)]';
      vector[1] arg_2 = [(1.2 + 0.0625 * seed)]';
      real value = squared_distance(arg_1, arg_2);
      total += 1.203125 * value;
    }
    // std_normal_log_qf(array[,,,]int)=>array[,,,]real
    {
      array[1, 1, 1, 1] int arg_1 = {{{{-1}}}};
      array[1, 1, 1, 1] real value = std_normal_log_qf(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // std_normal_log_qf(array[,,,]real)=>array[,,,]real
    {
      array[1, 1, 1, 1] real arg_1 = {{{{(-0.55000000000000004 + 0.0625 * seed)}}}};
      array[1, 1, 1, 1] real value = std_normal_log_qf(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // std_normal_log_qf(array[,]matrix)=>array[,]matrix
    {
      array[1, 1] matrix[1, 1] arg_1 = {{[[(-0.55000000000000004 + 0.0625 * seed)]]}};
      array[1, 1] matrix[1, 1] value = std_normal_log_qf(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // std_normal_qf(array[,,,,,]vector)=>array[,,,,,]vector
    {
      array[1, 1, 1, 1, 1, 1] vector[1] arg_1 = {{{{{{[(0.45000000000000001 + 0.0625 * seed)]'}}}}}};
      array[1, 1, 1, 1, 1, 1] vector[1] value = std_normal_qf(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // std_normal_qf(array[,,,,]row_vector)=>array[,,,,]row_vector
    {
      array[1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{[(0.45000000000000001 + 0.0625 * seed)]}}}}};
      array[1, 1, 1, 1, 1] row_vector[1] value = std_normal_qf(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // std_normal_qf(array[,]real)=>array[,]real
    {
      array[1, 1] real arg_1 = {{(0.45000000000000001 + 0.0625 * seed)}};
      array[1, 1] real value = std_normal_qf(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // subtract(row_vector,row_vector)=>row_vector
    {
      row_vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)];
      row_vector[1] arg_2 = [(1.2 + 0.0625 * seed)];
      row_vector[1] value = subtract(arg_1, arg_2);
      total += 1.0625 * sum(value);
    }
    // tan(array[,,,,,]row_vector)=>array[,,,,,]row_vector
    {
      array[1, 1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{{[(0.45000000000000001 + 0.0625 * seed)]}}}}}};
      array[1, 1, 1, 1, 1, 1] row_vector[1] value = tan(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // tan(array[,,,]int)=>array[,,,]real
    {
      array[1, 1, 1, 1] int arg_1 = {{{{1}}}};
      array[1, 1, 1, 1] real value = tan(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // tanh(array[,,,,]row_vector)=>array[,,,,]row_vector
    {
      array[1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{[(0.45000000000000001 + 0.0625 * seed)]}}}}};
      array[1, 1, 1, 1, 1] row_vector[1] value = tanh(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // tanh(real)=>real
    {
      real arg_1 = (0.45000000000000001 + 0.0625 * seed);
      real value = tanh(arg_1);
      total += 1.21875 * value;
    }
    // tgamma(array[,,,,]real)=>array[,,,,]real
    {
      array[1, 1, 1, 1, 1] real arg_1 = {{{{{(0.45000000000000001 + 0.0625 * seed)}}}}};
      array[1, 1, 1, 1, 1] real value = tgamma(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // tgamma(array[,,,,]row_vector)=>array[,,,,]row_vector
    {
      array[1, 1, 1, 1, 1] row_vector[1] arg_1 = {{{{{[(0.45000000000000001 + 0.0625 * seed)]}}}}};
      array[1, 1, 1, 1, 1] row_vector[1] value = tgamma(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // tgamma(array[]real)=>array[]real
    {
      array[1] real arg_1 = {(0.45000000000000001 + 0.0625 * seed)};
      array[1] real value = tgamma(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // to_array_1d(array[,,,,,,,,]real)=>array[]real
    {
      array[1, 1, 1, 1, 1, 1, 1, 1, 1] real arg_1 = {{{{{{{{{(0.45000000000000001 + 0.0625 * seed)}}}}}}}}};
      array[1] real value = to_array_1d(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // to_array_1d(matrix)=>array[]real
    {
      matrix[1, 1] arg_1 = [[(0.45000000000000001 + 0.0625 * seed)]];
      array[1] real value = to_array_1d(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // to_matrix(array[]int,int,int)=>matrix
    {
      array[1] int arg_1 = {0};
      matrix[1, 1] value = to_matrix(arg_1, 1, 1);
      total += 1 * sum(value);
    }
    // to_matrix(row_vector,int,int,int)=>matrix
    {
      row_vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)];
      matrix[1, 1] value = to_matrix(arg_1, 1, 1, 1);
      total += 1.140625 * sum(value);
    }
    // trigamma(array[,,,]real)=>array[,,,]real
    {
      array[1, 1, 1, 1] real arg_1 = {{{{(1.3499999999999999 + 0.0625 * seed)}}}};
      array[1, 1, 1, 1] real value = trigamma(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // trigamma(array[,,]real)=>array[,,]real
    {
      array[1, 1, 1] real arg_1 = {{{(1.3499999999999999 + 0.0625 * seed)}}};
      array[1, 1, 1] real value = trigamma(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // trigamma(array[,,]row_vector)=>array[,,]row_vector
    {
      array[1, 1, 1] row_vector[1] arg_1 = {{{[(1.3499999999999999 + 0.0625 * seed)]}}};
      array[1, 1, 1] row_vector[1] value = trigamma(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // trunc(array[,,,]matrix)=>array[,,,]matrix
    {
      array[1, 1, 1, 1] matrix[1, 1] arg_1 = {{{{[[(0.45000000000000001 + 0.0625 * seed)]]}}}};
      array[1, 1, 1, 1] matrix[1, 1] value = trunc(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // trunc(array[]row_vector)=>array[]row_vector
    {
      array[1] row_vector[1] arg_1 = {[(0.45000000000000001 + 0.0625 * seed)]};
      array[1] row_vector[1] value = trunc(arg_1);
      if (seed > 1e100)
        print(value);
    }
    // trunc(int)=>real
    {
      int arg_1 = 1;
      real value = trunc(arg_1);
      total += 1.109375 * value;
    }
    // variance(row_vector)=>real
    {
      row_vector[1] arg_1 = [(0.45000000000000001 + 0.0625 * seed)];
      real value = variance(arg_1);
      total += 1.1875 * value;
    }
    return total;
  }
}
data {
  real context_seed;
}
transformed data {
  real transformed_data_result = builtin_signatures_21(context_seed);
}
parameters {
  real probe;
}
model {
  probe ~ std_normal();
  target += builtin_signatures_21(probe);
  if (probe > -1e100)
    target += builtin_signatures_21(probe);
}
generated quantities {
  real generated_quantities_result = builtin_signatures_21(probe);
}
