(library
 (name stanli_compiler)
 (wrapped false)
 (libraries
  std
  fmt
  common
  frontend
  middle
  driver
  analysis_and_optimization)
 (modules portable_mir stanli_mir_transforms stanli_pipeline))

(executable
 (name stanli_stancjs)
 (libraries std fmt js_of_ocaml driver stan_math_signatures stanli_compiler)
 (modules conversion stanli_stancjs)
 (preprocess
  (pps js_of_ocaml-ppx))
 (modes js))

(executable
 (name stanli_compiler_cli)
 (libraries fmt frontend stanli_compiler)
 (modules stanli_compiler_cli))

(env
 (release
  (js_of_ocaml
   (flags
    (:standard "--opt" "3" "--target-env" "isomorphic"))))
 (dev
  (js_of_ocaml
   (flags
    "--pretty"
    "--no-inline"
    "--debug-info"
    "--disable"
    "staticeval"
    "--disable"
    "share"
    "--enable"
    "with-js-error"
    "--target-env"
    "isomorphic"))))

(alias
 (name default)
 (deps stanli_stancjs.bc.js stanli_compiler_cli.exe))
