# CMake generated Testfile for 
# Source directory: /Users/xitrium/claud/stanrt-spikes
# Build directory: /Users/xitrium/claud/stanrt-spikes/build-ship
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_smoke "/Users/xitrium/claud/stanrt-spikes/build-ship/test_smoke")
set_tests_properties(test_smoke PROPERTIES  WORKING_DIRECTORY "/Users/xitrium/claud/stanrt-spikes" _BACKTRACE_TRIPLES "/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;210;add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;226;stanli_add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;0;")
add_test(test_executor "/Users/xitrium/claud/stanrt-spikes/build-ship/test_executor")
set_tests_properties(test_executor PROPERTIES  WORKING_DIRECTORY "/Users/xitrium/claud/stanrt-spikes" _BACKTRACE_TRIPLES "/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;210;add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;227;stanli_add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;0;")
add_test(test_recorder "/Users/xitrium/claud/stanrt-spikes/build-ship/test_recorder")
set_tests_properties(test_recorder PROPERTIES  WORKING_DIRECTORY "/Users/xitrium/claud/stanrt-spikes" _BACKTRACE_TRIPLES "/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;210;add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;228;stanli_add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;0;")
add_test(test_densities "/Users/xitrium/claud/stanrt-spikes/build-ship/test_densities")
set_tests_properties(test_densities PROPERTIES  WORKING_DIRECTORY "/Users/xitrium/claud/stanrt-spikes" _BACKTRACE_TRIPLES "/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;210;add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;229;stanli_add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;0;")
add_test(test_matvec "/Users/xitrium/claud/stanrt-spikes/build-ship/test_matvec")
set_tests_properties(test_matvec PROPERTIES  WORKING_DIRECTORY "/Users/xitrium/claud/stanrt-spikes" _BACKTRACE_TRIPLES "/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;210;add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;230;stanli_add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;0;")
add_test(test_legacy "/Users/xitrium/claud/stanrt-spikes/build-ship/test_legacy")
set_tests_properties(test_legacy PROPERTIES  WORKING_DIRECTORY "/Users/xitrium/claud/stanrt-spikes" _BACKTRACE_TRIPLES "/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;210;add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;231;stanli_add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;0;")
add_test(test_eight_schools "/Users/xitrium/claud/stanrt-spikes/build-ship/test_eight_schools")
set_tests_properties(test_eight_schools PROPERTIES  WORKING_DIRECTORY "/Users/xitrium/claud/stanrt-spikes" _BACKTRACE_TRIPLES "/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;210;add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;232;stanli_add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;0;")
add_test(test_glm "/Users/xitrium/claud/stanrt-spikes/build-ship/test_glm")
set_tests_properties(test_glm PROPERTIES  WORKING_DIRECTORY "/Users/xitrium/claud/stanrt-spikes" _BACKTRACE_TRIPLES "/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;210;add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;233;stanli_add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;0;")
add_test(test_nuts "/Users/xitrium/claud/stanrt-spikes/build-ship/test_nuts")
set_tests_properties(test_nuts PROPERTIES  WORKING_DIRECTORY "/Users/xitrium/claud/stanrt-spikes" _BACKTRACE_TRIPLES "/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;210;add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;234;stanli_add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;0;")
add_test(test_sexp "/Users/xitrium/claud/stanrt-spikes/build-ship/test_sexp")
set_tests_properties(test_sexp PROPERTIES  WORKING_DIRECTORY "/Users/xitrium/claud/stanrt-spikes" _BACKTRACE_TRIPLES "/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;210;add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;235;stanli_add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;0;")
add_test(test_mir "/Users/xitrium/claud/stanrt-spikes/build-ship/test_mir")
set_tests_properties(test_mir PROPERTIES  WORKING_DIRECTORY "/Users/xitrium/claud/stanrt-spikes" _BACKTRACE_TRIPLES "/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;210;add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;236;stanli_add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;0;")
add_test(test_transforms "/Users/xitrium/claud/stanrt-spikes/build-ship/test_transforms")
set_tests_properties(test_transforms PROPERTIES  WORKING_DIRECTORY "/Users/xitrium/claud/stanrt-spikes" _BACKTRACE_TRIPLES "/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;210;add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;237;stanli_add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;0;")
add_test(test_eltwise "/Users/xitrium/claud/stanrt-spikes/build-ship/test_eltwise")
set_tests_properties(test_eltwise PROPERTIES  WORKING_DIRECTORY "/Users/xitrium/claud/stanrt-spikes" _BACKTRACE_TRIPLES "/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;210;add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;238;stanli_add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;0;")
add_test(test_lower "/Users/xitrium/claud/stanrt-spikes/build-ship/test_lower")
set_tests_properties(test_lower PROPERTIES  WORKING_DIRECTORY "/Users/xitrium/claud/stanrt-spikes" _BACKTRACE_TRIPLES "/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;210;add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;239;stanli_add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;0;")
add_test(test_data "/Users/xitrium/claud/stanrt-spikes/build-ship/test_data")
set_tests_properties(test_data PROPERTIES  WORKING_DIRECTORY "/Users/xitrium/claud/stanrt-spikes" _BACKTRACE_TRIPLES "/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;210;add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;240;stanli_add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;0;")
add_test(test_e2e "/Users/xitrium/claud/stanrt-spikes/build-ship/test_e2e")
set_tests_properties(test_e2e PROPERTIES  WORKING_DIRECTORY "/Users/xitrium/claud/stanrt-spikes" _BACKTRACE_TRIPLES "/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;210;add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;241;stanli_add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;0;")
add_test(test_reroll "/Users/xitrium/claud/stanrt-spikes/build-ship/test_reroll")
set_tests_properties(test_reroll PROPERTIES  WORKING_DIRECTORY "/Users/xitrium/claud/stanrt-spikes" _BACKTRACE_TRIPLES "/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;210;add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;242;stanli_add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;0;")
add_test(test_profile "/Users/xitrium/claud/stanrt-spikes/build-ship/test_profile")
set_tests_properties(test_profile PROPERTIES  WORKING_DIRECTORY "/Users/xitrium/claud/stanrt-spikes" _BACKTRACE_TRIPLES "/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;210;add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;243;stanli_add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;0;")
add_test(test_inplace "/Users/xitrium/claud/stanrt-spikes/build-ship/test_inplace")
set_tests_properties(test_inplace PROPERTIES  WORKING_DIRECTORY "/Users/xitrium/claud/stanrt-spikes" _BACKTRACE_TRIPLES "/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;210;add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;244;stanli_add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;0;")
add_test(test_pass_safety "/Users/xitrium/claud/stanrt-spikes/build-ship/test_pass_safety")
set_tests_properties(test_pass_safety PROPERTIES  WORKING_DIRECTORY "/Users/xitrium/claud/stanrt-spikes" _BACKTRACE_TRIPLES "/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;210;add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;245;stanli_add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;0;")
add_test(test_sampling "/Users/xitrium/claud/stanrt-spikes/build-ship/test_sampling")
set_tests_properties(test_sampling PROPERTIES  WORKING_DIRECTORY "/Users/xitrium/claud/stanrt-spikes" _BACKTRACE_TRIPLES "/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;210;add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;246;stanli_add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;0;")
add_test(test_ode_prog "/Users/xitrium/claud/stanrt-spikes/build-ship/test_ode_prog")
set_tests_properties(test_ode_prog PROPERTIES  WORKING_DIRECTORY "/Users/xitrium/claud/stanrt-spikes" _BACKTRACE_TRIPLES "/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;210;add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;247;stanli_add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;0;")
add_test(test_constfold "/Users/xitrium/claud/stanrt-spikes/build-ship/test_constfold")
set_tests_properties(test_constfold PROPERTIES  WORKING_DIRECTORY "/Users/xitrium/claud/stanrt-spikes" _BACKTRACE_TRIPLES "/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;210;add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;248;stanli_add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;0;")
add_test(test_write_array "/Users/xitrium/claud/stanrt-spikes/build-ship/test_write_array")
set_tests_properties(test_write_array PROPERTIES  WORKING_DIRECTORY "/Users/xitrium/claud/stanrt-spikes" _BACKTRACE_TRIPLES "/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;210;add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;249;stanli_add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;0;")
add_test(test_mixture "/Users/xitrium/claud/stanrt-spikes/build-ship/test_mixture")
set_tests_properties(test_mixture PROPERTIES  WORKING_DIRECTORY "/Users/xitrium/claud/stanrt-spikes" _BACKTRACE_TRIPLES "/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;210;add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;250;stanli_add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;0;")
add_test(test_island "/Users/xitrium/claud/stanrt-spikes/build-ship/test_island")
set_tests_properties(test_island PROPERTIES  WORKING_DIRECTORY "/Users/xitrium/claud/stanrt-spikes" _BACKTRACE_TRIPLES "/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;210;add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;251;stanli_add_test;/Users/xitrium/claud/stanrt-spikes/CMakeLists.txt;0;")
